package com.ckb.wo.server.dao.masterparam.ibatis.impl;

import com.ckb.wo.client.model.Station;
import com.ckb.wo.client.model.StationExample;
import com.ckb.wo.server.dao.masterparam.StationDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class StationDAOImpl extends SqlMapClientDaoSupport implements StationDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public StationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public int countStationByExample(StationExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_station.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public int deleteStationByExample(StationExample example) {
        int rows = getSqlMapClientTemplate().delete("t_station.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public int deleteStationByPrimaryKey(String stationId) {
        Station key = new Station();
        key.setStationId(stationId);
        int rows = getSqlMapClientTemplate().delete("t_station.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public void insertStation(Station record) {
        getSqlMapClientTemplate().insert("t_station.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public void insertStationSelective(Station record) {
        getSqlMapClientTemplate().insert("t_station.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    @SuppressWarnings("unchecked")
    public List<Station> selectStationByExample(StationExample example) {
        List<Station> list = getSqlMapClientTemplate().queryForList("t_station.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public Station selectStationByPrimaryKey(String stationId) {
        Station key = new Station();
        key.setStationId(stationId);
        Station record = (Station) getSqlMapClientTemplate().queryForObject("t_station.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public int updateStationByExampleSelective(Station record, StationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_station.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public int updateStationByExample(Station record, StationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_station.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public int updateStationByPrimaryKeySelective(Station record) {
        int rows = getSqlMapClientTemplate().update("t_station.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public int updateStationByPrimaryKey(Station record) {
        int rows = getSqlMapClientTemplate().update("t_station.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    private static class UpdateByExampleParms extends StationExample {
        private Object record;

        public UpdateByExampleParms(Object record, StationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}