package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.Area;
import com.ckb.wo.client.model.AreaExample;
import com.ckb.wo.server.dao.AreaDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AreaDAOImpl extends SqlMapClientDaoSupport implements AreaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public AreaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int countAreaByExample(AreaExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tarea.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int deleteAreaByExample(AreaExample example) {
        int rows = getSqlMapClientTemplate().delete("tarea.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int deleteAreaByPrimaryKey(String areaId) {
        Area key = new Area();
        key.setAreaId(areaId);
        int rows = getSqlMapClientTemplate().delete("tarea.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public void insertArea(Area record) {
        getSqlMapClientTemplate().insert("tarea.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public void insertAreaSelective(Area record) {
        getSqlMapClientTemplate().insert("tarea.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    @SuppressWarnings("unchecked")
    public List<Area> selectAreaByExample(AreaExample example) {
        List<Area> list = getSqlMapClientTemplate().queryForList("tarea.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public Area selectAreaByPrimaryKey(String areaId) {
        Area key = new Area();
        key.setAreaId(areaId);
        Area record = (Area) getSqlMapClientTemplate().queryForObject("tarea.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int updateAreaByExampleSelective(Area record, AreaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tarea.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int updateAreaByExample(Area record, AreaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tarea.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int updateAreaByPrimaryKeySelective(Area record) {
        int rows = getSqlMapClientTemplate().update("tarea.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int updateAreaByPrimaryKey(Area record) {
        int rows = getSqlMapClientTemplate().update("tarea.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tarea
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    private static class UpdateByExampleParms extends AreaExample {
        private Object record;

        public UpdateByExampleParms(Object record, AreaExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}