package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.Department;
import com.ckb.wo.client.model.DepartmentExample;
import com.ckb.wo.server.dao.DepartmentDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DepartmentDAOImpl extends SqlMapClientDaoSupport implements DepartmentDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public DepartmentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int countDepartmentByExample(DepartmentExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tdepartment.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int deleteDepartmentByExample(DepartmentExample example) {
        int rows = getSqlMapClientTemplate().delete("tdepartment.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int deleteDepartmentByPrimaryKey(String departmentId) {
        Department key = new Department();
        key.setDepartmentId(departmentId);
        int rows = getSqlMapClientTemplate().delete("tdepartment.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public void insertDepartment(Department record) {
        getSqlMapClientTemplate().insert("tdepartment.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public void insertDepartmentSelective(Department record) {
        getSqlMapClientTemplate().insert("tdepartment.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    @SuppressWarnings("unchecked")
    public List<Department> selectDepartmentByExample(DepartmentExample example) {
        List<Department> list = getSqlMapClientTemplate().queryForList("tdepartment.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public Department selectDepartmentByPrimaryKey(String departmentId) {
        Department key = new Department();
        key.setDepartmentId(departmentId);
        Department record = (Department) getSqlMapClientTemplate().queryForObject("tdepartment.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int updateDepartmentByExampleSelective(Department record, DepartmentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tdepartment.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int updateDepartmentByExample(Department record, DepartmentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tdepartment.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int updateDepartmentByPrimaryKeySelective(Department record) {
        int rows = getSqlMapClientTemplate().update("tdepartment.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public int updateDepartmentByPrimaryKey(Department record) {
        int rows = getSqlMapClientTemplate().update("tdepartment.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    private static class UpdateByExampleParms extends DepartmentExample {
        private Object record;

        public UpdateByExampleParms(Object record, DepartmentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}