package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.Location;
import com.ckb.wo.client.model.LocationExample;
import com.ckb.wo.server.dao.LocationDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LocationDAOImpl extends SqlMapClientDaoSupport implements LocationDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public LocationDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public int countLocationByExample(LocationExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"tlocation.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public int deleteLocationByExample(LocationExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"tlocation.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public int deleteLocationByPrimaryKey(Long tlocationPk) {
		Location key = new Location();
		key.setTlocationPk(tlocationPk);
		int rows = getSqlMapClientTemplate().delete(
				"tlocation.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public Long insertLocation(Location record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"tlocation.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public Long insertLocationSelective(Location record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"tlocation.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Location> selectLocationByExample(LocationExample example) {
		List<Location> list = getSqlMapClientTemplate().queryForList(
				"tlocation.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public Location selectLocationByPrimaryKey(Long tlocationPk) {
		Location key = new Location();
		key.setTlocationPk(tlocationPk);
		Location record = (Location) getSqlMapClientTemplate().queryForObject(
				"tlocation.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public int updateLocationByExampleSelective(Location record,
			LocationExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"tlocation.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public int updateLocationByExample(Location record, LocationExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"tlocation.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public int updateLocationByPrimaryKeySelective(Location record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"tlocation.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	public int updateLocationByPrimaryKey(Location record) {
		int rows = getSqlMapClientTemplate().update(
				"tlocation.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

    @Override
    public List<Location> selectLocationWithJoinByExample(LocationExample example) {
        List<Location> list = getSqlMapClientTemplate().queryForList(
				"tlocation.ibatorgenerated_selectWithJoinByExample", example);
        return list;
    }

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tlocation
	 * @ibatorgenerated  Mon Jul 26 17:59:51 SGT 2010
	 */
	private static class UpdateByExampleParms extends LocationExample {
		private Object record;

		public UpdateByExampleParms(Object record, LocationExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}