package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.Order;
import com.ckb.wo.client.model.OrderExample;
import com.ckb.wo.server.dao.OrderDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OrderDAOImpl extends SqlMapClientDaoSupport implements OrderDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    public OrderDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param example
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public int countOrderByExample(OrderExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("torder.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param example
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public int deleteOrderByExample(OrderExample example) {
        int rows = getSqlMapClientTemplate().delete("torder.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param torderPk
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public int deleteOrderByPrimaryKey(Long torderPk) {
        Order key = new Order();
        key.setTorderPk(torderPk);
        int rows = getSqlMapClientTemplate().delete("torder.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param record
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public Long insertOrder(Order record) {
        Object newKey = getSqlMapClientTemplate().insert("torder.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param record
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public Long insertOrderSelective(Order record) {
        Object newKey = getSqlMapClientTemplate().insert("torder.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param example
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @SuppressWarnings("unchecked")
    @Override
    public List<Order> selectOrderByExample(OrderExample example) {
        List<Order> list = getSqlMapClientTemplate().queryForList("torder.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param torderPk
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public Order selectOrderByPrimaryKey(Long torderPk) {
        Order key = new Order();
        key.setTorderPk(torderPk);
        Order record = (Order) getSqlMapClientTemplate().queryForObject("torder.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public int updateOrderByExampleSelective(Order record, OrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("torder.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public int updateOrderByExample(Order record, OrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("torder.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param record
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public int updateOrderByPrimaryKeySelective(Order record) {
        int rows = getSqlMapClientTemplate().update("torder.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table torder
     *
     * @param record
     * @return
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    @Override
    public int updateOrderByPrimaryKey(Order record) {
        int rows = getSqlMapClientTemplate().update("torder.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds
     * to the database table torder
     *
     * @ibatorgenerated Tue Jun 29 17:37:52 SGT 2010
     */
    private static class UpdateByExampleParms extends OrderExample {

        private Object record;

        public UpdateByExampleParms(Object record, OrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
