package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.OriContainer;
import com.ckb.wo.client.model.OriContainerExample;
import com.ckb.wo.server.dao.OriContainerDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OriContainerDAOImpl extends SqlMapClientDaoSupport implements OriContainerDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public OriContainerDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int countOriContainerByExample(OriContainerExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"oricontainer.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int deleteOriContainerByExample(OriContainerExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"oricontainer.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public void insertOriContainer(OriContainer record) {
		getSqlMapClientTemplate().insert("oricontainer.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public void insertOriContainerSelective(OriContainer record) {
		getSqlMapClientTemplate().insert(
				"oricontainer.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	@SuppressWarnings("unchecked")
	public List<OriContainer> selectOriContainerByExample(
			OriContainerExample example) {
		List<OriContainer> list = getSqlMapClientTemplate().queryForList(
				"oricontainer.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int updateOriContainerByExampleSelective(OriContainer record,
			OriContainerExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"oricontainer.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int updateOriContainerByExample(OriContainer record,
			OriContainerExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"oricontainer.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	private static class UpdateByExampleParms extends OriContainerExample {
		private Object record;

		public UpdateByExampleParms(Object record, OriContainerExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}