package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.OriVendorRate;
import com.ckb.wo.client.model.OriVendorRateExample;
import com.ckb.wo.server.dao.OriVendorRateDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OriVendorRateDAOImpl extends SqlMapClientDaoSupport implements OriVendorRateDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table orivendorrate
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public OriVendorRateDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table orivendorrate
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int countOriVendorRateByExample(OriVendorRateExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"orivendorrate.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table orivendorrate
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int deleteOriVendorRateByExample(OriVendorRateExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"orivendorrate.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table orivendorrate
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public void insertOriVendorRate(OriVendorRate record) {
		getSqlMapClientTemplate().insert(
				"orivendorrate.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table orivendorrate
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public void insertOriVendorRateSelective(OriVendorRate record) {
		getSqlMapClientTemplate().insert(
				"orivendorrate.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table orivendorrate
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	@SuppressWarnings("unchecked")
	public List<OriVendorRate> selectOriVendorRateByExample(
			OriVendorRateExample example) {
		List<OriVendorRate> list = getSqlMapClientTemplate().queryForList(
				"orivendorrate.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table orivendorrate
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int updateOriVendorRateByExampleSelective(OriVendorRate record,
			OriVendorRateExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"orivendorrate.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table orivendorrate
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int updateOriVendorRateByExample(OriVendorRate record,
			OriVendorRateExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"orivendorrate.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table orivendorrate
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	private static class UpdateByExampleParms extends OriVendorRateExample {
		private Object record;

		public UpdateByExampleParms(Object record, OriVendorRateExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}