package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.Permission;
import com.ckb.wo.client.model.PermissionExample;
import com.ckb.wo.server.dao.PermissionDAO;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PermissionDAOImpl extends SqlMapClientDaoSupport implements PermissionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public PermissionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int countPermissionByExample(PermissionExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"tpermission.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int deletePermissionByExample(PermissionExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"tpermission.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int deletePermissionByPrimaryKey(Long tpermissionPk) {
		Permission key = new Permission();
		key.setTpermissionPk(tpermissionPk);
		int rows = getSqlMapClientTemplate().delete(
				"tpermission.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public Long insertPermission(Permission record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"tpermission.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public Long insertPermissionSelective(Permission record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"tpermission.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Permission> selectPermissionByExample(PermissionExample example) {
		List<Permission> list = getSqlMapClientTemplate().queryForList(
				"tpermission.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public Permission selectPermissionByPrimaryKey(Long tpermissionPk) {
		Permission key = new Permission();
		key.setTpermissionPk(tpermissionPk);
		Permission record = (Permission) getSqlMapClientTemplate()
				.queryForObject(
						"tpermission.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updatePermissionByExampleSelective(Permission record,
			PermissionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"tpermission.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updatePermissionByExample(Permission record,
			PermissionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"tpermission.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updatePermissionByPrimaryKeySelective(Permission record) {
		int rows = getSqlMapClientTemplate().update(
				"tpermission.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updatePermissionByPrimaryKey(Permission record) {
		int rows = getSqlMapClientTemplate().update(
				"tpermission.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	private static class UpdateByExampleParms extends PermissionExample {
		private Object record;

		public UpdateByExampleParms(Object record, PermissionExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
	
	// custom method
	public Integer doesUserHavePermission(String employeeId, String actionId){
		Map<String, String> map = new HashMap<String, String>();
		map.put("employeeId", employeeId);
		map.put("permissionCode", actionId);
		Integer total = (Integer) getSqlMapClientTemplate().queryForObject("tpermission.doesUserHavePermission", map);
		return total;
	}
}