package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.RolesUsers;
import com.ckb.wo.client.model.RolesUsersExample;
import com.ckb.wo.server.dao.RolesUsersDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RolesUsersDAOImpl extends SqlMapClientDaoSupport implements RolesUsersDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public RolesUsersDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int countRolesUsersByExample(RolesUsersExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"trole_tuser.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int deleteRolesUsersByExample(RolesUsersExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"trole_tuser.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int deleteRolesUsersByPrimaryKey(Long troleTuserPk) {
		RolesUsers key = new RolesUsers();
		key.setTroleTuserPk(troleTuserPk);
		int rows = getSqlMapClientTemplate().delete(
				"trole_tuser.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public Long insertRolesUsers(RolesUsers record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"trole_tuser.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public Long insertRolesUsersSelective(RolesUsers record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"trole_tuser.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	@SuppressWarnings("unchecked")
	public List<RolesUsers> selectRolesUsersByExample(RolesUsersExample example) {
		List<RolesUsers> list = getSqlMapClientTemplate().queryForList(
				"trole_tuser.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public RolesUsers selectRolesUsersByPrimaryKey(Long troleTuserPk) {
		RolesUsers key = new RolesUsers();
		key.setTroleTuserPk(troleTuserPk);
		RolesUsers record = (RolesUsers) getSqlMapClientTemplate()
				.queryForObject(
						"trole_tuser.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updateRolesUsersByExampleSelective(RolesUsers record,
			RolesUsersExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"trole_tuser.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updateRolesUsersByExample(RolesUsers record,
			RolesUsersExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"trole_tuser.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updateRolesUsersByPrimaryKeySelective(RolesUsers record) {
		int rows = getSqlMapClientTemplate().update(
				"trole_tuser.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updateRolesUsersByPrimaryKey(RolesUsers record) {
		int rows = getSqlMapClientTemplate().update(
				"trole_tuser.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table trole_tuser
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	private static class UpdateByExampleParms extends RolesUsersExample {
		private Object record;

		public UpdateByExampleParms(Object record, RolesUsersExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}