package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.Role;
import com.ckb.wo.client.model.RoleExample;
import com.ckb.wo.server.dao.RoleDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RoleDAOImpl extends SqlMapClientDaoSupport implements RoleDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public RoleDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int countRoleByExample(RoleExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"trole.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int deleteRoleByExample(RoleExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"trole.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int deleteRoleByPrimaryKey(Long trolePk) {
		Role key = new Role();
		key.setTrolePk(trolePk);
		int rows = getSqlMapClientTemplate().delete(
				"trole.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public Long insertRole(Role record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"trole.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public Long insertRoleSelective(Role record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"trole.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Role> selectRoleByExample(RoleExample example) {
		List<Role> list = getSqlMapClientTemplate().queryForList(
				"trole.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public Role selectRoleByPrimaryKey(Long trolePk) {
		Role key = new Role();
		key.setTrolePk(trolePk);
		Role record = (Role) getSqlMapClientTemplate().queryForObject(
				"trole.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updateRoleByExampleSelective(Role record, RoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"trole.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updateRoleByExample(Role record, RoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"trole.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updateRoleByPrimaryKeySelective(Role record) {
		int rows = getSqlMapClientTemplate().update(
				"trole.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	public int updateRoleByPrimaryKey(Role record) {
		int rows = getSqlMapClientTemplate().update(
				"trole.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table trole
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	private static class UpdateByExampleParms extends RoleExample {
		private Object record;

		public UpdateByExampleParms(Object record, RoleExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
	
	public Role selectRoleWithPermissionByPrimaryKey(Long rolePk){		
		return (Role)getSqlMapClientTemplate().queryForObject("trole.selectRoleWithPermission",rolePk);
	}
	
	
}