package com.ckb.wo.server.dao.ibatis.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ckb.wo.client.model.ServiceMode;
import com.ckb.wo.client.model.ServiceModeExample;
import com.ckb.wo.server.dao.ServiceModeDAO;

public class ServiceModeDAOImpl extends SqlMapClientDaoSupport implements ServiceModeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public ServiceModeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int countServiceModeByExample(ServiceModeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"tservicemode.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int deleteServiceModeByExample(ServiceModeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"tservicemode.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int deleteServiceModeByPrimaryKey(Long tservicemodePk) {
		ServiceMode key = new ServiceMode();
		key.setTservicemodePk(tservicemodePk);
		int rows = getSqlMapClientTemplate().delete(
				"tservicemode.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public Long insertServiceMode(ServiceMode record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"tservicemode.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public Long insertServiceModeSelective(ServiceMode record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"tservicemode.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	@SuppressWarnings("unchecked")
	public List<ServiceMode> selectServiceModeByExample(
			ServiceModeExample example) {
		List<ServiceMode> list = getSqlMapClientTemplate().queryForList(
				"tservicemode.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public ServiceMode selectServiceModeByPrimaryKey(Long tservicemodePk) {
		ServiceMode key = new ServiceMode();
		key.setTservicemodePk(tservicemodePk);
		ServiceMode record = (ServiceMode) getSqlMapClientTemplate()
				.queryForObject(
						"tservicemode.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int updateServiceModeByExampleSelective(ServiceMode record,
			ServiceModeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"tservicemode.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int updateServiceModeByExample(ServiceMode record,
			ServiceModeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"tservicemode.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int updateServiceModeByPrimaryKeySelective(ServiceMode record) {
		int rows = getSqlMapClientTemplate().update(
				"tservicemode.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	public int updateServiceModeByPrimaryKey(ServiceMode record) {
		int rows = getSqlMapClientTemplate().update(
				"tservicemode.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	private static class UpdateByExampleParms extends ServiceModeExample {
		private Object record;

		public UpdateByExampleParms(Object record, ServiceModeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}