package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.ServiceModeDetail;
import com.ckb.wo.client.model.ServiceModeDetailExample;
import com.ckb.wo.server.dao.ServiceModeDetailDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ServiceModeDetailDAOImpl extends SqlMapClientDaoSupport implements ServiceModeDetailDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public ServiceModeDetailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public int countServiceModeDetailByExample(ServiceModeDetailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"tservicemodedetail.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public int deleteServiceModeDetailByExample(ServiceModeDetailExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"tservicemodedetail.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public int deleteServiceModeDetailByPrimaryKey(Long tservicemodedetailPk) {
		ServiceModeDetail key = new ServiceModeDetail();
		key.setTservicemodedetailPk(tservicemodedetailPk);
		int rows = getSqlMapClientTemplate().delete(
				"tservicemodedetail.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public Long insertServiceModeDetail(ServiceModeDetail record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"tservicemodedetail.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public Long insertServiceModeDetailSelective(ServiceModeDetail record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"tservicemodedetail.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	@SuppressWarnings("unchecked")
	public List<ServiceModeDetail> selectServiceModeDetailByExample(
			ServiceModeDetailExample example) {
		List<ServiceModeDetail> list = getSqlMapClientTemplate().queryForList(
				"tservicemodedetail.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public ServiceModeDetail selectServiceModeDetailByPrimaryKey(
			Long tservicemodedetailPk) {
		ServiceModeDetail key = new ServiceModeDetail();
		key.setTservicemodedetailPk(tservicemodedetailPk);
		ServiceModeDetail record = (ServiceModeDetail) getSqlMapClientTemplate()
				.queryForObject(
						"tservicemodedetail.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public int updateServiceModeDetailByExampleSelective(
			ServiceModeDetail record, ServiceModeDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"tservicemodedetail.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public int updateServiceModeDetailByExample(ServiceModeDetail record,
			ServiceModeDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"tservicemodedetail.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public int updateServiceModeDetailByPrimaryKeySelective(
			ServiceModeDetail record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"tservicemodedetail.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	public int updateServiceModeDetailByPrimaryKey(ServiceModeDetail record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"tservicemodedetail.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tservicemodedetail
	 * @ibatorgenerated  Fri Jul 16 21:07:58 SGT 2010
	 */
	private static class UpdateByExampleParms extends ServiceModeDetailExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				ServiceModeDetailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}