package com.ckb.wo.server.dao.ibatis.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.ckb.wo.client.model.User;
import com.ckb.wo.client.model.UserExample;
import com.ckb.wo.server.dao.UserDAO;

public class UserDAOImpl extends SqlMapClientDaoSupport implements UserDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public UserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param example
     * @return
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public int countUserByExample(UserExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tuser.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param example
     * @return
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public int deleteUserByExample(UserExample example) {
        int rows = getSqlMapClientTemplate().delete("tuser.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param employeeId
     * @return
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public int deleteUserByPrimaryKey(String employeeId) {
        User key = new User();
        key.setEmployeeId(employeeId);
        int rows = getSqlMapClientTemplate().delete("tuser.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param record
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public void insertUser(User record) {
        getSqlMapClientTemplate().insert("tuser.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param record
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public void insertUserSelective(User record) {
        getSqlMapClientTemplate().insert("tuser.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param example
     * @return
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @SuppressWarnings("unchecked")
    @Override
    public List<User> selectUserByExample(UserExample example) {
        List<User> list = getSqlMapClientTemplate().queryForList("tuser.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param employeeId
     * @return
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public User selectUserByPrimaryKey(String employeeId) {
        User key = new User();
        key.setEmployeeId(employeeId);
        User record = (User) getSqlMapClientTemplate().queryForObject("tuser.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public int updateUserByExampleSelective(User record, UserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tuser.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public int updateUserByExample(User record, UserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tuser.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param record
     * @return
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public int updateUserByPrimaryKeySelective(User record) {
        int rows = getSqlMapClientTemplate().update("tuser.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param record
     * @return
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public int updateUserByPrimaryKey(User record) {
        int rows = getSqlMapClientTemplate().update("tuser.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    @Override
    public List<User> getUserAlreadyCreateWO() {
        List<User> result = getSqlMapClientTemplate().queryForList("tuser.getAllUserAlreadyCreateWO");
        return result;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds
     * to the database table tuser
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private static class UpdateByExampleParms extends UserExample {

        private Object record;

        public UpdateByExampleParms(Object record, UserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    // custom query
    @Override
    public List<String> selectselectEmployeeIdByExample(UserExample example) {
        List<String> list = getSqlMapClientTemplate().queryForList("tuser.selectEmployeeIdByExample", example);
        return list;
    }

    //custom method
    @Override
    public Integer getUserLevelValueByEmployeeId(String employeeId) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tuser.getUserLevelValueByEmployeeId", employeeId);
        return count;
    }

    /*
     * (non-Javadoc) get User who has given final approval to WO (oldwostatus = 'APPROVED', and recorded in tworkorderflow table
     * @see com.ckb.wo.server.dao.UserDAO#getFinalUserApprovalWO(java.lang.Long)
     */
    @Override
    public User getFinalUserApprovalWO(Long tworkorderPk) {
        List<User> lUser = getSqlMapClientTemplate().queryForList("tuser.getFinalUserApprovalWO", tworkorderPk);
        if (lUser != null && lUser.size() > 0) {
            return lUser.get(0);
        } else {
            return null;
        }
        //return (User) getSqlMapClientTemplate().queryForObject("tuser.getFinalUserApprovalWO",tworkorderPk);
    }

    @Override
    public User getFinalUserCancellationWO(Long tworkorderPk) {
        List<User> lUser = getSqlMapClientTemplate().queryForList("tuser.getFinalUserCancellationWO", tworkorderPk);
        if (lUser != null && lUser.size() > 0) {
            return lUser.get(0);
        } else {
            return null;
        }
    }

    @Override
    public User getNextUserForThisWorkOrder(Long tworkorderPk) {
        return (User) getSqlMapClientTemplate().queryForObject("tuser.getNextUserForThisWorkOrder", tworkorderPk);
    }

    @Override
    public List<User> selectUserByExampleWithJoin(UserExample example) {
        return getSqlMapClientTemplate().queryForList("tuser.selectByExampleWithJoin", example);
    }

    @Override
    public User selectUserByPrimaryKeyWithJoin(String employeeId) {
        User key = new User();
        key.setEmployeeId(employeeId);
        User record = (User) getSqlMapClientTemplate().queryForObject("tuser.selectByPrimaryKeyWithJoin", key);
        return record;
    }

    @Override
    public User selectUserByPrimaryKeyWithRoles(String employeeId) {
        return (User) getSqlMapClientTemplate().queryForObject("tuser.selectByPrimaryKeyWithRoles", employeeId);
    }

    @Override
    public List<User> selectUserByExampleWithRoles(UserExample example) {
        return getSqlMapClientTemplate().queryForList("tuser.selectByExampleWithRoles", example);
    }

    @Override
    public int countUsersOneLevelAbove(UserExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tuser.countUsersOneLevelAbove", example);
        return count;
    }

    @Override
    public List<User> selectUsersOneLevelAbove(UserExample example) {
        return getSqlMapClientTemplate().queryForList("tuser.selectUsersOneLevelAbove", example);
    }

}
