package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.Vendor;
import com.ckb.wo.client.model.VendorExample;
import com.ckb.wo.server.dao.VendorDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VendorDAOImpl extends SqlMapClientDaoSupport implements VendorDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    public VendorDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public int countVendorByExample(VendorExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "tvendor.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public int deleteVendorByExample(VendorExample example) {
        int rows = getSqlMapClientTemplate().delete(
                "tvendor.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param tvendorPk
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public int deleteVendorByPrimaryKey(Long tvendorPk) {
        Vendor key = new Vendor();
        key.setTvendorPk(tvendorPk);
        int rows = getSqlMapClientTemplate().delete(
                "tvendor.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public Long insertVendor(Vendor record) {
        Object newKey = getSqlMapClientTemplate().insert(
                "tvendor.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public Long insertVendorSelective(Vendor record) {
        Object newKey = getSqlMapClientTemplate().insert(
                "tvendor.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @SuppressWarnings("unchecked")
    @Override
    public List<Vendor> selectVendorByExample(VendorExample example) {
        List<Vendor> list = getSqlMapClientTemplate().queryForList(
                "tvendor.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param tvendorPk
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public Vendor selectVendorByPrimaryKey(Long tvendorPk) {
        Vendor key = new Vendor();
        key.setTvendorPk(tvendorPk);
        Vendor record = (Vendor) getSqlMapClientTemplate().queryForObject(
                "tvendor.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public int updateVendorByExampleSelective(Vendor record, VendorExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update(
                "tvendor.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public int updateVendorByExample(Vendor record, VendorExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update(
                "tvendor.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public int updateVendorByPrimaryKeySelective(Vendor record) {
        int rows = getSqlMapClientTemplate().update(
                "tvendor.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tvendor
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public int updateVendorByPrimaryKey(Vendor record) {
        int rows = getSqlMapClientTemplate().update(
                "tvendor.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds
     * to the database table tvendor
     *
     * @ibatorgenerated Mon Aug 02 19:17:49 SGT 2010
     */
    private static class UpdateByExampleParms extends VendorExample {

        private final Object record;

        public UpdateByExampleParms(Object record, VendorExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    @Override
    public List<Vendor> selectByVendorCodeAndIsAfterEventEqualsTrue(String vendorCode) {
        List<Vendor> list = getSqlMapClientTemplate().queryForList(
                "tvendor.selectByVendorCodeAndIsAfterEventEqualsTrue", vendorCode);
        return list;
    }
}
