package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.ExtendedWorkOrderExample;
import com.ckb.wo.client.model.WoDaManStatus;
import com.ckb.wo.client.model.WorkOrder;
import com.ckb.wo.client.model.WorkOrderExample;
import com.ckb.wo.server.dao.WorkOrderDAO;
import java.util.ArrayList;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WorkOrderDAOImpl extends SqlMapClientDaoSupport implements WorkOrderDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public WorkOrderDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int extendedCountWorkOrderByExample(ExtendedWorkOrderExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tworkorder.extCountByExample", example);
        return count;
    }

    /**
     *
     * @param example
     * @return
     */
    @Override
    public int countWorkOrderByExample(WorkOrderExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tworkorder.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int deleteWorkOrderByExample(WorkOrderExample example) {
        int rows = getSqlMapClientTemplate().delete("tworkorder.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param tworkorderPk
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int deleteWorkOrderByPrimaryKey(Long tworkorderPk) {
        WorkOrder key = new WorkOrder();
        key.setTworkorderPk(tworkorderPk);
        int rows = getSqlMapClientTemplate().delete("tworkorder.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public Long insertWorkOrder(WorkOrder record) {
        Object newKey = getSqlMapClientTemplate().insert("tworkorder.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public Long insertWorkOrderSelective(WorkOrder record) {
        Object newKey = getSqlMapClientTemplate().insert("tworkorder.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @SuppressWarnings("unchecked")
    @Override
    public List<WorkOrder> selectWorkOrderByExampleWithBLOBs(WorkOrderExample example) {
        List<WorkOrder> list = getSqlMapClientTemplate().queryForList("tworkorder.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @SuppressWarnings("unchecked")
    @Override
    public List<WorkOrder> selectWorkOrderByExampleWithoutBLOBs(WorkOrderExample example) {
        List<WorkOrder> list = getSqlMapClientTemplate().queryForList("tworkorder.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param tworkorderPk
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public WorkOrder selectWorkOrderByPrimaryKey(Long tworkorderPk) {
        WorkOrder key = new WorkOrder();
        key.setTworkorderPk(tworkorderPk);
        WorkOrder record = (WorkOrder) getSqlMapClientTemplate().queryForObject("tworkorder.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int updateWorkOrderByExampleSelective(WorkOrder record, WorkOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tworkorder.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int updateWorkOrderByExampleWithBLOBs(WorkOrder record, WorkOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tworkorder.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int updateWorkOrderByExampleWithoutBLOBs(WorkOrder record, WorkOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tworkorder.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int updateWorkOrderByPrimaryKeySelective(WorkOrder record) {
        int rows = getSqlMapClientTemplate().update("tworkorder.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int updateWorkOrderByPrimaryKeyWithBLOBs(WorkOrder record) {
        int rows = getSqlMapClientTemplate().update("tworkorder.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int updateWorkOrderByPrimaryKeyWithoutBLOBs(WorkOrder record) {
        int rows = getSqlMapClientTemplate().update("tworkorder.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
    
    @Override
    public List<WoDaManStatus> selectWoDaManStatusByMan(List<String> reffNoList) {
        return getSqlMapClientTemplate().queryForList("tworkorder.selectWoDaManByMan", reffNoList);
    }
    
    @Override
    public List<WoDaManStatus> selectWoDaManStatusByDa(List<String> reffNoList) {
        return getSqlMapClientTemplate().queryForList("tworkorder.selectWoDaManByDa", reffNoList);
    }

    @Override
    public List<WoDaManStatus> selectWoDaManStatusByWo(List<String> reffNoList) {
        return getSqlMapClientTemplate().queryForList("tworkorder.selectWoDaManByWo", reffNoList);
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds
     * to the database table tworkorder
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private static class UpdateByExampleParms extends WorkOrderExample {

        private final Object record;

        public UpdateByExampleParms(Object record, WorkOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    public List<Long> extendedSelectWorkOrderPKOnlyByExample(ExtendedWorkOrderExample example) {
        List<Long> lworkorderPk = getSqlMapClientTemplate().queryForList("tworkorder.extSelectOnlyTWorkorderPkByExampleWithJoin", example);
        return lworkorderPk;
    }

    @Override
    public List<Long> selectWorkOrderPKOnlyByExample(ExtendedWorkOrderExample example) {
//        List<Long> lworkorderPk = getSqlMapClientTemplate().queryForList(
//                "tworkorder.selectOnlyTWorkorderPkByExampleWithJoin", example);
//        return lworkorderPk;
        return extendedSelectWorkOrderPKOnlyByExample(example);
    }

    @Override
    public List<WorkOrder> selectWorkOrderByExampleWithJoin(ExtendedWorkOrderExample example) {
//        List<Long> lworkorderPk = getSqlMapClientTemplate().queryForList(
//                "tworkorder.selectOnlyTWorkorderPkByExampleWithJoin", example);
//        if (lworkorderPk == null || lworkorderPk.isEmpty()) {
//            return null;
//        }
        List<Long> lworkorderPk = getSqlMapClientTemplate().queryForList("tworkorder.extSelectOnlyTWorkorderPkByExampleWithJoin", example);
        if (lworkorderPk == null || lworkorderPk.isEmpty()) {
            return null;
        }

        WorkOrderExample realExample = new WorkOrderExample();
        realExample.createCriteria().andTworkorderPkIn(lworkorderPk);
        List<WorkOrder> list = getSqlMapClientTemplate().queryForList("tworkorder.selectByExampleWithJoinOptimized", realExample);
        //tworkorder.selectByExampleWithJoinOptimized
//        <result property="creatorUser" resultMap="tuser.ibatorgenerated_BaseResultMap" />
        return list;
    }

    @Override
    public WorkOrder selectWorkOrderByPrimaryKeyWithJoin(Long tworkorderPk) {
        WorkOrder key = new WorkOrder();
        key.setTworkorderPk(tworkorderPk);
        WorkOrder record = (WorkOrder) getSqlMapClientTemplate().queryForObject("tworkorder.selectByPrimaryKeyWithJoinOptimized", key);
        // tworkorder.selectByPrimaryKeyWithJoin
        return record;
    }

    @Override
    public List<WorkOrder> selectWorkOrderByExampleWithJoinToFast(WorkOrderExample example) {
        List<WorkOrder> list = getSqlMapClientTemplate().queryForList("tworkorder.selectByExampleWithJoinOptimized", example);
        return list;
        //tworkorder.selectByExampleWithJoinToFast
    }

    @Override
    public WorkOrder selectWorkOrderByPrimaryKeyWithJoinToFast(Long tworkorderPk) {
        WorkOrder key = new WorkOrder();
        key.setTworkorderPk(tworkorderPk);
        WorkOrder record = (WorkOrder) getSqlMapClientTemplate().queryForObject("tworkorder.selectByPrimaryKeyWithJoinOptimized", key);
        return record;
    }

    //selectByPrimaryKeyWithJoinToFast
    @Override
    public List<WorkOrder> selectWorkOrderApprovedByThisUser(String employeeId, String wonumber, String limitClause, String orderByClause) {
        Map<String, Object> map = getParameterForWorkOrderApprovedByThisUser(employeeId, wonumber, limitClause, orderByClause);//, true);
        if (map.get("wopks") == null || ((List) map.get("wopks")).isEmpty()) {
            return null;
        }
        return getSqlMapClientTemplate().queryForList("tworkorder.selectWorkOrderApprovedByThisUser", map);
    }

    @Override
    public Integer countWorkOrderApprovedByThisUser(String employeeId, String wonumber) {
        Map<String, Object> map = new HashMap();
        map.put("employeeid", employeeId);
        map.put("nomorwo", wonumber == null ? "%" : wonumber);
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tworkorder.countWorkOrderApprovedByThisUser", map);
        return count;
    }

    private Map getParameterForWorkOrderApprovedByThisUser(String employeeId, String wonumber, String limitClause, String orderByClause) {//, boolean fetch) {
        List<String> status = new ArrayList<>();
//        if (wostatus == null || wostatus.isEmpty()) {
//            status.add(WorkOrder.APPROVED_STATUS);
//            status.add(WorkOrder.PRINTED_STATUS);
//            status.add(WorkOrder.CANCELLED_STATUS);
//            status.add(WorkOrder.CANCEL_RECIEVED);
//            status.add(WorkOrder.EDIT_STATUS);
//            status.add(WorkOrder.INPROGRESS_STATUS);
//            status.add(WorkOrder.REVISION_STATUS);
//        } else {
//            status.add(wostatus);
//        }
        Map<String, Object> map = new HashMap<>();
//        map.put("wostatus", WorkOrder.RECEIVED_STATUS);

        map.put("nomorwo", wonumber == null ? "%" : wonumber);
        map.put("wostatus", status);
        map.put("employeeid", employeeId);
        if (limitClause != null && limitClause.length() > 0) {
            map.put("limitClause", limitClause);
        }

//        if (fetch) {
        List<Long> wopks = getSqlMapClientTemplate().queryForList("tworkorder.selectOnlyTWorkorderPkActionByThisUser", map);
        map = new HashMap<>();
        map.put("wopks", wopks);
//        }
        if (orderByClause != null && orderByClause.length() > 0) {
            map.put("orderByClause", orderByClause);
        }
        return map;
    }

    private Map getParameterForWorkOrderValidatedByThisUser(String employeeId, String orderByClause, String limitClause) {
        Map<String, Object> map = new HashMap<>();
        map.put("wostatus", WorkOrder.RECEIVED_STATUS);
        map.put("employeeid", employeeId);
        if (orderByClause != null && orderByClause.length() > 0) {
            map.put("orderByClause", orderByClause);
        }
        if (limitClause != null && limitClause.length() > 0) {
            map.put("limitClause", limitClause);
        }
        map.put("oldwostatus", WorkOrder.VALIDATION_STATUS);
        return map;
    }

    @Override
    public Integer countWorkOrderValidatedByThisUser(String employeeId) {
        Map<String, Object> map = getParameterForWorkOrderValidatedByThisUser(employeeId, null, null);
        return (Integer) getSqlMapClientTemplate().queryForObject("tworkorder.countWorkOrderValidatedByThisUser", map);
    }

    @Override
    public List<WorkOrder> selectWorkOrderValidatedByThisUser(String employeeId, String orderByClause, String limitClause) {
        Map<String, Object> map = getParameterForWorkOrderValidatedByThisUser(employeeId, orderByClause, limitClause);
        return getSqlMapClientTemplate().queryForList("tworkorder.selectWorkOrderValidatedByThisUser", map);
    }

    @Override
    public List<WorkOrder> selectByExampleWithJoinForFinance(ExtendedWorkOrderExample example) {
        return getSqlMapClientTemplate().queryForList("tworkorder.selectByExampleWithJoinForFinance", example);
    }

    @Override
    public Integer countByExampleWithJoinForFinance(ExtendedWorkOrderExample example) {
        return (Integer) getSqlMapClientTemplate().queryForObject("tworkorder.countByExampleWithJoinForFinance", example);
    }
    
    @Override
    public List<WorkOrder> selectWorkOrderByExampleWithJoinWithoutDa(ExtendedWorkOrderExample example) {
        List<Long> lworkorderPk = getSqlMapClientTemplate().queryForList("tworkorder.extSelectOnlyTWorkorderPkByExampleWithJoin", example);
        if (lworkorderPk == null || lworkorderPk.isEmpty()) {
            return null;
        }

        WorkOrderExample realExample = new WorkOrderExample();
        realExample.createCriteria().andTworkorderPkIn(lworkorderPk);
        List<WorkOrder> list = getSqlMapClientTemplate().queryForList("tworkorder.selectByExampleWithJoinWithoutDaOptimized", realExample); 
        return list; 
    }
}
