package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.ExtendedWorkOrderDAExample;
import com.ckb.wo.client.model.WorkOrderDA;
import com.ckb.wo.client.model.WorkOrderDAExample;
import com.ckb.wo.server.dao.WorkOrderDADAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WorkOrderDADAOImpl extends SqlMapClientDaoSupport implements WorkOrderDADAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    public WorkOrderDADAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int countWorkOrderDAByExample(WorkOrderDAExample example) {
        Integer count = (Integer) getSqlMapClientTemplate()
                .queryForObject("tworkorder_da.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int deleteWorkOrderDAByExample(WorkOrderDAExample example) {
        int rows = getSqlMapClientTemplate()
                .delete("tworkorder_da.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param tworkorderDaPk
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int deleteWorkOrderDAByPrimaryKey(Long tworkorderDaPk) {
        WorkOrderDA key = new WorkOrderDA();
        key.setTworkorderDaPk(tworkorderDaPk);
        int rows = getSqlMapClientTemplate()
                .delete("tworkorder_da.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public Long insertWorkOrderDA(WorkOrderDA record) {
        Object newKey = getSqlMapClientTemplate()
                .insert("tworkorder_da.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public Long insertWorkOrderDASelective(WorkOrderDA record) {
        Object newKey = getSqlMapClientTemplate()
                .insert("tworkorder_da.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @SuppressWarnings("unchecked")
    @Override
    public List<WorkOrderDA> selectWorkOrderDAByExample(WorkOrderDAExample example) {
        List<WorkOrderDA> list = getSqlMapClientTemplate()
                .queryForList("tworkorder_da.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param tworkorderDaPk
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public WorkOrderDA selectWorkOrderDAByPrimaryKey(Long tworkorderDaPk) {
        WorkOrderDA key = new WorkOrderDA();
        key.setTworkorderDaPk(tworkorderDaPk);
        WorkOrderDA record = (WorkOrderDA) getSqlMapClientTemplate()
                .queryForObject("tworkorder_da.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int updateWorkOrderDAByExampleSelective(WorkOrderDA record, WorkOrderDAExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate()
                .update("tworkorder_da.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int updateWorkOrderDAByExample(WorkOrderDA record, WorkOrderDAExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate()
                .update("tworkorder_da.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int updateWorkOrderDAByPrimaryKeySelective(WorkOrderDA record) {
        int rows = getSqlMapClientTemplate()
                .update("tworkorder_da.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_da
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int updateWorkOrderDAByPrimaryKey(WorkOrderDA record) {
        int rows = getSqlMapClientTemplate()
                .update("tworkorder_da.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds
     * to the database table tworkorder_da
     *
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    private static class UpdateByExampleParms extends WorkOrderDAExample {

        private Object record;

        public UpdateByExampleParms(Object record, WorkOrderDAExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    @Override
    public List<WorkOrderDA> selectWorkOrderDAByExampleWithJoin(WorkOrderDAExample example) {
        return null;
    }

    @Override
    public List<WorkOrderDA> selectAlreadyUsedDA(List<Long> listNoDA, Long tvendor_fk, Long tlocation_fk) {
        ExtendedWorkOrderDAExample example = new ExtendedWorkOrderDAExample();
        ExtendedWorkOrderDAExample.ExtendedCriteria crit = (ExtendedWorkOrderDAExample.ExtendedCriteria) example.createCriteria();
//                ExtendedWorkOrderDAExample.ExtendedCriteria crit2 = (ExtendedWorkOrderDAExample.ExtendedCriteria) example.createCriteria();
//                ExtendedWorkOrderDAExample.ExtendedCriteria crit3 = (ExtendedWorkOrderDAExample.ExtendedCriteria) example.createCriteria();
        crit.andDaIn(listNoDA);
        crit.andTLocationFkEqualTo(tlocation_fk);
        crit.andTVendorFkEqualTo(tvendor_fk);
//                example.or(crit2.andTLocationFkEqualTo(tlocation_fk));
//                example.or(crit3.andTVendorFkEqualTo(tvendor_fk));

        crit.excludeCanceledWO();
        List<WorkOrderDA> list = getSqlMapClientTemplate().queryForList(
                "tworkorder_da.selectAlreadyUsedDA", example);
        return list;
    }

}
