package com.ckb.wo.server.dao.ibatis.impl;

import com.ckb.wo.client.model.WorkOrderManifest;
import com.ckb.wo.client.model.WorkOrderManifestExample;
import com.ckb.wo.server.dao.WorkOrderManifestDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WorkOrderManifestDAOImpl extends SqlMapClientDaoSupport implements WorkOrderManifestDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    public WorkOrderManifestDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int countWorkOrderManifestByExample(WorkOrderManifestExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tworkorder_manifest.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param example
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int deleteWorkOrderManifestByExample(WorkOrderManifestExample example) {
        int rows = getSqlMapClientTemplate().delete("tworkorder_manifest.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param tworkorderManifestPk
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int deleteWorkOrderManifestByPrimaryKey(Long tworkorderManifestPk) {
        WorkOrderManifest key = new WorkOrderManifest();
        key.setTworkorderManifestPk(tworkorderManifestPk);
        int rows = getSqlMapClientTemplate().delete("tworkorder_manifest.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public Long insertWorkOrderManifest(WorkOrderManifest record) {
        Object newKey = getSqlMapClientTemplate().insert("tworkorder_manifest.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public Long insertWorkOrderManifestSelective(WorkOrderManifest record) {
        Object newKey = getSqlMapClientTemplate().insert("tworkorder_manifest.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param manifestNo
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int countUsedManifest(Long manifestNo) {
        return (Integer) getSqlMapClientTemplate().queryForObject("tworkorder_manifest.countUsedManifest", manifestNo);
    }

    @SuppressWarnings("unchecked")
    @Override
    public List<WorkOrderManifest> selectWorkOrderManifestByExample(WorkOrderManifestExample example) {
        List<WorkOrderManifest> list = getSqlMapClientTemplate().queryForList("tworkorder_manifest.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param tworkorderManifestPk
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public WorkOrderManifest selectWorkOrderManifestByPrimaryKey(Long tworkorderManifestPk) {
        WorkOrderManifest key = new WorkOrderManifest();
        key.setTworkorderManifestPk(tworkorderManifestPk);
        WorkOrderManifest record = (WorkOrderManifest) getSqlMapClientTemplate().queryForObject("tworkorder_manifest.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int updateWorkOrderManifestByExampleSelective(WorkOrderManifest record, WorkOrderManifestExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tworkorder_manifest.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int updateWorkOrderManifestByExample(WorkOrderManifest record, WorkOrderManifestExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tworkorder_manifest.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int updateWorkOrderManifestByPrimaryKeySelective(WorkOrderManifest record) {
        int rows = getSqlMapClientTemplate().update("tworkorder_manifest.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder_manifest
     *
     * @param record
     * @return
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    @Override
    public int updateWorkOrderManifestByPrimaryKey(WorkOrderManifest record) {
        int rows = getSqlMapClientTemplate().update("tworkorder_manifest.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds
     * to the database table tworkorder_manifest
     *
     * @ibatorgenerated Mon Jul 05 17:58:15 SGT 2010
     */
    private static class UpdateByExampleParms extends WorkOrderManifestExample {

        private Object record;

        public UpdateByExampleParms(Object record, WorkOrderManifestExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
