package com.ckb.wo.server.dao.fast.ibatis.impl;

import com.ckb.wo.client.model.FastDivision;
import com.ckb.wo.client.model.FastDivisionExample;
import com.ckb.wo.server.dao.fast.FastDivisionDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class FastDivisionDAOImpl extends SqlMapClientDaoSupport implements FastDivisionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public FastDivisionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int countFastDivisionByExample(FastDivisionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_division.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int deleteFastDivisionByExample(FastDivisionExample example) {
        int rows = getSqlMapClientTemplate().delete("t_division.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int deleteFastDivisionByPrimaryKey(String divisionId) {
        FastDivision key = new FastDivision();
        key.setDivisionId(divisionId);
        int rows = getSqlMapClientTemplate().delete("t_division.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public void insertFastDivision(FastDivision record) {
        getSqlMapClientTemplate().insert("t_division.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public void insertFastDivisionSelective(FastDivision record) {
        getSqlMapClientTemplate().insert("t_division.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    @SuppressWarnings("unchecked")
    public List<FastDivision> selectFastDivisionByExample(FastDivisionExample example) {
        List<FastDivision> list = getSqlMapClientTemplate().queryForList("t_division.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public FastDivision selectFastDivisionByPrimaryKey(String divisionId) {
        FastDivision key = new FastDivision();
        key.setDivisionId(divisionId);
        FastDivision record = (FastDivision) getSqlMapClientTemplate().queryForObject("t_division.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int updateFastDivisionByExampleSelective(FastDivision record, FastDivisionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_division.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int updateFastDivisionByExample(FastDivision record, FastDivisionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_division.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int updateFastDivisionByPrimaryKeySelective(FastDivision record) {
        int rows = getSqlMapClientTemplate().update("t_division.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int updateFastDivisionByPrimaryKey(FastDivision record) {
        int rows = getSqlMapClientTemplate().update("t_division.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_division
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    private static class UpdateByExampleParms extends FastDivisionExample {
        private Object record;

        public UpdateByExampleParms(Object record, FastDivisionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}