package com.ckb.wo.server.dao.fast.ibatis.impl;

import com.ckb.wo.client.model.FastLevel;
import com.ckb.wo.client.model.FastLevelExample;
import com.ckb.wo.server.dao.fast.FastLevelDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class FastLevelDAOImpl extends SqlMapClientDaoSupport implements FastLevelDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public FastLevelDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int countFastLevelByExample(FastLevelExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_level.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int deleteFastLevelByExample(FastLevelExample example) {
        int rows = getSqlMapClientTemplate().delete("t_level.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int deleteFastLevelByPrimaryKey(String levelId) {
        FastLevel key = new FastLevel();
        key.setLevelId(levelId);
        int rows = getSqlMapClientTemplate().delete("t_level.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public void insertFastLevel(FastLevel record) {
        getSqlMapClientTemplate().insert("t_level.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public void insertFastLevelSelective(FastLevel record) {
        getSqlMapClientTemplate().insert("t_level.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    @SuppressWarnings("unchecked")
    public List<FastLevel> selectFastLevelByExample(FastLevelExample example) {
        List<FastLevel> list = getSqlMapClientTemplate().queryForList("t_level.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public FastLevel selectFastLevelByPrimaryKey(String levelId) {
        FastLevel key = new FastLevel();
        key.setLevelId(levelId);
        FastLevel record = (FastLevel) getSqlMapClientTemplate().queryForObject("t_level.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int updateFastLevelByExampleSelective(FastLevel record, FastLevelExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_level.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int updateFastLevelByExample(FastLevel record, FastLevelExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_level.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int updateFastLevelByPrimaryKeySelective(FastLevel record) {
        int rows = getSqlMapClientTemplate().update("t_level.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int updateFastLevelByPrimaryKey(FastLevel record) {
        int rows = getSqlMapClientTemplate().update("t_level.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    private static class UpdateByExampleParms extends FastLevelExample {
        private Object record;

        public UpdateByExampleParms(Object record, FastLevelExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}