package com.ckb.wo.server.dao.fast.ibatis.impl;

import com.ckb.wo.client.model.FastJobTitle;
import com.ckb.wo.client.model.FastJobTitleExample;
import com.ckb.wo.server.dao.fast.FastJobTitleDAO;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class FastJobTitleDAOImpl extends SqlMapClientDaoSupport implements FastJobTitleDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public FastJobTitleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int countFastJobTitleByExample(FastJobTitleExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_job_title.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int deleteFastJobTitleByExample(FastJobTitleExample example) {
        int rows = getSqlMapClientTemplate().delete("t_job_title.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int deleteFastJobTitleByPrimaryKey(String jobTitleId) {
        FastJobTitle key = new FastJobTitle();
        key.setJobTitleId(jobTitleId);
        int rows = getSqlMapClientTemplate().delete("t_job_title.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public void insertFastJobTitle(FastJobTitle record) {
        getSqlMapClientTemplate().insert("t_job_title.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public void insertFastJobTitleSelective(FastJobTitle record) {
        getSqlMapClientTemplate().insert("t_job_title.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    @SuppressWarnings("unchecked")
    public List<FastJobTitle> selectFastJobTitleByExample(FastJobTitleExample example) {
        List<FastJobTitle> list = getSqlMapClientTemplate().queryForList("t_job_title.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public FastJobTitle selectFastJobTitleByPrimaryKey(String jobTitleId) {
        FastJobTitle key = new FastJobTitle();
        key.setJobTitleId(jobTitleId);
        FastJobTitle record = (FastJobTitle) getSqlMapClientTemplate().queryForObject("t_job_title.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public int updateFastJobTitleByExampleSelective(FastJobTitle record, FastJobTitleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_job_title.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int updateFastJobTitleByExample(FastJobTitle record, FastJobTitleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_job_title.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int updateFastJobTitleByPrimaryKeySelective(FastJobTitle record) {
        int rows = getSqlMapClientTemplate().update("t_job_title.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    public int updateFastJobTitleByPrimaryKey(FastJobTitle record) {
        int rows = getSqlMapClientTemplate().update("t_job_title.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_job_title
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    private static class UpdateByExampleParms extends FastJobTitleExample {
        private Object record;

        public UpdateByExampleParms(Object record, FastJobTitleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}