package com.ckb.wo.server.dao;

import com.ckb.wo.client.model.Department;
import com.ckb.wo.client.model.DepartmentExample;
import java.util.List;

public interface DepartmentDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    int countDepartmentByExample(DepartmentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    int deleteDepartmentByExample(DepartmentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    int deleteDepartmentByPrimaryKey(String departmentId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    void insertDepartment(Department record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    void insertDepartmentSelective(Department record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    List<Department> selectDepartmentByExample(DepartmentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    Department selectDepartmentByPrimaryKey(String departmentId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    int updateDepartmentByExampleSelective(Department record, DepartmentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    int updateDepartmentByExample(Department record, DepartmentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    int updateDepartmentByPrimaryKeySelective(Department record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdepartment
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    int updateDepartmentByPrimaryKey(Department record);
}