package com.ckb.wo.server.dao;

import com.ckb.wo.client.model.OriContainer;
import com.ckb.wo.client.model.OriContainerExample;
import java.util.List;

public interface OriContainerDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int countOriContainerByExample(OriContainerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int deleteOriContainerByExample(OriContainerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	void insertOriContainer(OriContainer record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	void insertOriContainerSelective(OriContainer record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	List<OriContainer> selectOriContainerByExample(OriContainerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int updateOriContainerByExampleSelective(OriContainer record,
			OriContainerExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table oricontainer
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int updateOriContainerByExample(OriContainer record,
			OriContainerExample example);
}