package com.ckb.wo.server.dao;

import com.ckb.wo.client.model.RolesPermissions;
import com.ckb.wo.client.model.RolesPermissionsExample;
import java.util.List;

public interface RolesPermissionsDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	int countRolesPermissionsByExample(RolesPermissionsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	int deleteRolesPermissionsByExample(RolesPermissionsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	int deleteRolesPermissionsByPrimaryKey(Long troleTpermissionPk);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	Long insertRolesPermissions(RolesPermissions record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	Long insertRolesPermissionsSelective(RolesPermissions record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	List<RolesPermissions> selectRolesPermissionsByExample(
			RolesPermissionsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	RolesPermissions selectRolesPermissionsByPrimaryKey(Long troleTpermissionPk);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	int updateRolesPermissionsByExampleSelective(RolesPermissions record,
			RolesPermissionsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	int updateRolesPermissionsByExample(RolesPermissions record,
			RolesPermissionsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	int updateRolesPermissionsByPrimaryKeySelective(RolesPermissions record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table trole_tpermission
	 * @ibatorgenerated  Fri Jul 16 14:31:56 SGT 2010
	 */
	int updateRolesPermissionsByPrimaryKey(RolesPermissions record);
}