package com.ckb.wo.server.dao;

import com.ckb.wo.client.model.ServiceMode;
import com.ckb.wo.client.model.ServiceModeExample;
import java.util.List;

public interface ServiceModeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int countServiceModeByExample(ServiceModeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int deleteServiceModeByExample(ServiceModeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int deleteServiceModeByPrimaryKey(Long tservicemodePk);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	Long insertServiceMode(ServiceMode record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	Long insertServiceModeSelective(ServiceMode record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	List<ServiceMode> selectServiceModeByExample(ServiceModeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	ServiceMode selectServiceModeByPrimaryKey(Long tservicemodePk);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int updateServiceModeByExampleSelective(ServiceMode record,
			ServiceModeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int updateServiceModeByExample(ServiceMode record,
			ServiceModeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int updateServiceModeByPrimaryKeySelective(ServiceMode record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tservicemode
	 * @ibatorgenerated  Tue Jun 29 17:37:52 SGT 2010
	 */
	int updateServiceModeByPrimaryKey(ServiceMode record);
}