package com.ckb.wo.server.dao;

import com.ckb.wo.client.model.Vendor;
import com.ckb.wo.client.model.VendorService;
import com.ckb.wo.client.model.VendorServiceExample;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public interface VendorServiceDAO {

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param example
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    int countVendorServiceByExample(VendorServiceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param example
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    int deleteVendorServiceByExample(VendorServiceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param tvendorservicePk
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    int deleteVendorServiceByPrimaryKey(Long tvendorservicePk);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param record
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    Long insertVendorService(VendorService record);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param record
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    Long insertVendorServiceSelective(VendorService record);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param example
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    List<VendorService> selectVendorServiceByExample(VendorServiceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param tvendorservicePk
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    VendorService selectVendorServiceByPrimaryKey(Long tvendorservicePk);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    int updateVendorServiceByExampleSelective(VendorService record, VendorServiceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param record
     * @param example
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    int updateVendorServiceByExample(VendorService record, VendorServiceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param record
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    int updateVendorServiceByPrimaryKeySelective(VendorService record);

    /**
     * This method was generated by Apache iBATIS ibator.This method corresponds
     * to the database table tvendorservice
     *
     * @param record
     * @return
     * @ibatorgenerated Wed Aug 11 08:16:42 SGT 2010
     */
    int updateVendorServiceByPrimaryKey(VendorService record);

    @SuppressWarnings("unchecked")
    public List<VendorService> selectVendorServiceByExampleWithJoin(VendorServiceExample example);

    public VendorService selectVendorServiceByPrimaryKeyWithJoin(Long tvendorservicePk);

    public List<VendorService> selectByVendorNameAndOtherRateAttributeWithJoin(String vendorName, Long origintlocation_fk, Long destinationtlocation_fk, Long tservicemodedetail_fk, String limitClause, String orderByClause);

    public int countByVendorNameAndOtherRateAttribute(String vendorName, Long origintlocation_fk, Long destinationtlocation_fk, Long tservicemodedetail_fk);

    public List<Vendor> selectVendorByRateAttribute(Long origintlocation_fk, Long desttlocation_fk, Date execDate, Long tservicemodedetail_fk, Long tdeliveryterm_fk);

    public VendorService selectVendorServiceByAttribute(Long tvendorServiceId, Long tservicemode_fk, Date execDate, Long origintlocation_fk, Long desttlocation_fk, Long torder_fk, BigDecimal weight, Long tservicemodedetail_fk);
}
