package com.ckb.wo.server.dao;

import com.ckb.wo.client.model.ExtendedWorkOrderFlowExample;
import com.ckb.wo.client.model.WorkOrder;
import com.ckb.wo.client.model.WorkOrderFlow;
import com.ckb.wo.client.model.WorkOrderFlowExample;
import java.util.List;

public interface WorkOrderFlowDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	int countWorkOrderFlowByExample(WorkOrderFlowExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	int deleteWorkOrderFlowByExample(WorkOrderFlowExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	int deleteWorkOrderFlowByPrimaryKey(Long tworkorderflowPk);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	Long insertWorkOrderFlow(WorkOrderFlow record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	Long insertWorkOrderFlowSelective(WorkOrderFlow record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	List<WorkOrderFlow> selectWorkOrderFlowByExample(
			WorkOrderFlowExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	WorkOrderFlow selectWorkOrderFlowByPrimaryKey(Long tworkorderflowPk);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	int updateWorkOrderFlowByExampleSelective(WorkOrderFlow record,
			WorkOrderFlowExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	int updateWorkOrderFlowByExample(WorkOrderFlow record,
			WorkOrderFlowExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	int updateWorkOrderFlowByPrimaryKeySelective(WorkOrderFlow record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorderflow
	 * @ibatorgenerated  Mon Aug 16 17:24:26 SGT 2010
	 */
	int updateWorkOrderFlowByPrimaryKey(WorkOrderFlow record);

	public List<Long> getWorkOrderValidatedByThisUser(String employeeId);

	public List<WorkOrderFlow> selectApprovalHistoryForThisWorkOrder(Long workorderPk);
}