package com.ckb.wo.server.dao.mda.ibatis.impl;

import com.ckb.wo.client.model.Shipment;
import com.ckb.wo.server.dao.mda.ShipmentDAO;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ShipmentDAOImpl extends SqlMapClientDaoSupport implements ShipmentDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table t_shipment
     *
     * @ibatorgenerated Sat Jul 10 13:45:16 SGT 2010
     */
    public ShipmentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table t_shipment
     *
     * @param daNo
     * @param isMPS
     * @return
     * @ibatorgenerated Sat Jul 10 13:45:16 SGT 2010
     */
//    public int countShipmentByExample(ShipmentExample example) {
    @Override
    public int countShipmentByExample(String daNo, boolean isMPS) {
//        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_shipment.ibatorgenerated_countByExample", example);
        int result = 0;
        Map map = new HashMap();
        map.put("da", daNo);
        if (!isMPS) {
            result = (Integer) getSqlMapClientTemplate().queryForObject("t_shipment.countDAByPK", map);
        } else {
            result = (Integer) getSqlMapClientTemplate().queryForObject("t_shipment.countMPSByPK", map);
        }
        return result;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table t_shipment
     *
     * @ibatorgenerated Sat Jul 10 13:45:16 SGT 2010
     */
//    @SuppressWarnings("unchecked")
//    public List<Shipment> selectShipmentByExampleWithBLOBs(ShipmentExample example) {
//        List<Shipment> list = getSqlMapClientTemplate().queryForList("t_shipment.ibatorgenerated_selectByExampleWithBLOBs", example);
//        return list;
//    }
    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table t_shipment
     *
     * @ibatorgenerated Sat Jul 10 13:45:16 SGT 2010
     */
//    @SuppressWarnings("unchecked")
//    public List<Shipment> selectShipmentByExampleWithoutBLOBs(ShipmentExample example) {
//        List<Shipment> list = getSqlMapClientTemplate().queryForList("t_shipment.ibatorgenerated_selectByExample", example);
//        return list;
//    }
    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table t_shipment
     *
     * @param da
     * @return
     * @ibatorgenerated Sat Jul 10 13:45:16 SGT 2010
     */
    @Override
    public Shipment selectShipmentNotPODByPrimaryKey(Long da) {
        Shipment key = new Shipment();
        key.setDa(da);
        Shipment record = (Shipment) getSqlMapClientTemplate().queryForObject("t_shipment.selectDAMPSNotPOD", key);
        return record;
    }

    @Override
    public Shipment selectShipmentByPrimaryKey(Long da) {
        Shipment key = new Shipment();
        key.setDa(da);
        System.out.println("da = " + da);
        Shipment record = (Shipment) getSqlMapClientTemplate().queryForObject("t_shipment.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

//    public List<Shipment> selectShipmentByDANoWithLike(ShipmentExample example){
    @Override
    public List<Shipment> selectShipmentByDAMPSNoWithLike(String daNo, String limitClause, String orderByClause) {
        return selectShipmentByDAMPSNoWithLike(daNo, limitClause, orderByClause, false);
    }

    @Override
    public List<Shipment> selectShipmentByDAMPSNoWithLike(String daNo, String limitClause, String orderByClause, boolean isMPS) {
//        List<Shipment> list = getSqlMapClientTemplate().queryForList("t_shipment.selectShipmentByDANoWithLike", example);
        Map map = new HashMap();
        map.put("da", daNo);
        map.put("limitClause", limitClause);
        map.put("orderByClause", orderByClause);
        List<Shipment> list = null;
        if (!isMPS) {
            list = getSqlMapClientTemplate().queryForList("t_shipment.selectShipmentByDANoWithLike", map);
        } else {
            list = getSqlMapClientTemplate().queryForList("t_shipment.selectShipmentByMPSNoWithLike", map);
        }
        return list;
    }
}
