package com.ckb.wo.server.dao.fast;

import com.ckb.wo.client.model.FastLevel;
import com.ckb.wo.client.model.FastLevelExample;
import java.util.List;

public interface FastLevelDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    int countFastLevelByExample(FastLevelExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    int deleteFastLevelByExample(FastLevelExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    int deleteFastLevelByPrimaryKey(String levelId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    void insertFastLevel(FastLevel record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    void insertFastLevelSelective(FastLevel record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    List<FastLevel> selectFastLevelByExample(FastLevelExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    FastLevel selectFastLevelByPrimaryKey(String levelId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    int updateFastLevelByExampleSelective(FastLevel record, FastLevelExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    int updateFastLevelByExample(FastLevel record, FastLevelExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    int updateFastLevelByPrimaryKeySelective(FastLevel record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_level
     *
     * @ibatorgenerated Thu Jul 01 20:09:01 SGT 2010
     */
    int updateFastLevelByPrimaryKey(FastLevel record);
}