package com.ckb.wo.client.model;

import java.io.Serializable;

public class Division implements Serializable {

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tdivision.division_id
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    private String divisionId;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tdivision.description
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    private String description;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tdivision
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tdivision.division_id
     *
     * @return the value of tdivision.division_id
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public String getDivisionId() {
        return divisionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tdivision.division_id
     *
     * @param divisionId the value for tdivision.division_id
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public void setDivisionId(String divisionId) {
        this.divisionId = divisionId == null ? null : divisionId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tdivision.description
     *
     * @return the value of tdivision.description
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tdivision.description
     *
     * @param description the value for tdivision.description
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdivision
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Division)) {
            return false;
        }
        Division other = (Division) that;
        return this.getDivisionId() == null ? other == null : this.getDivisionId().equals(other.getDivisionId())
                && this.getDescription() == null ? other == null : this.getDescription().equals(other.getDescription());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tdivision
     *
     * @ibatorgenerated Thu Jul 01 20:08:58 SGT 2010
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getDivisionId() != null) {
            hash *= getDivisionId().hashCode();
        }
        if (getDescription() != null) {
            hash *= getDescription().hashCode();
        }
        return hash;
    }
    public static final String SERVICE_CODE = "SSV";
    public static final String FINANCE_CODE = "FIN";
    public static final String OPERATION_CODE = "OPS";
}
