package com.ckb.wo.client.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FastUserExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    protected String limitClause;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public FastUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    protected FastUserExample(FastUserExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.limitClause = example.limitClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public void setLimitClause(String limitClause) {
        this.limitClause = limitClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public String getLimitClause() {
        return limitClause;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_personel
     *
     * @ibatorgenerated Thu Jul 01 20:09:00 SGT 2010
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andEmployeeIdIsNull() {
            addCriterion("employee_id is null");
            return this;
        }

        public Criteria andEmployeeIdIsNotNull() {
            addCriterion("employee_id is not null");
            return this;
        }

        public Criteria andEmployeeIdEqualTo(String value) {
            addCriterion("employee_id =", value, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdNotEqualTo(String value) {
            addCriterion("employee_id <>", value, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdGreaterThan(String value) {
            addCriterion("employee_id >", value, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdGreaterThanOrEqualTo(String value) {
            addCriterion("employee_id >=", value, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdLessThan(String value) {
            addCriterion("employee_id <", value, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdLessThanOrEqualTo(String value) {
            addCriterion("employee_id <=", value, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdLike(String value) {
            addCriterion("employee_id like", value, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdNotLike(String value) {
            addCriterion("employee_id not like", value, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdIn(List<String> values) {
            addCriterion("employee_id in", values, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdNotIn(List<String> values) {
            addCriterion("employee_id not in", values, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdBetween(String value1, String value2) {
            addCriterion("employee_id between", value1, value2, "employeeId");
            return this;
        }

        public Criteria andEmployeeIdNotBetween(String value1, String value2) {
            addCriterion("employee_id not between", value1, value2, "employeeId");
            return this;
        }

        public Criteria andFirstNameIsNull() {
            addCriterion("first_name is null");
            return this;
        }

        public Criteria andFirstNameIsNotNull() {
            addCriterion("first_name is not null");
            return this;
        }

        public Criteria andFirstNameEqualTo(String value) {
            addCriterion("first_name =", value, "firstName");
            return this;
        }

        public Criteria andFirstNameNotEqualTo(String value) {
            addCriterion("first_name <>", value, "firstName");
            return this;
        }

        public Criteria andFirstNameGreaterThan(String value) {
            addCriterion("first_name >", value, "firstName");
            return this;
        }

        public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
            addCriterion("first_name >=", value, "firstName");
            return this;
        }

        public Criteria andFirstNameLessThan(String value) {
            addCriterion("first_name <", value, "firstName");
            return this;
        }

        public Criteria andFirstNameLessThanOrEqualTo(String value) {
            addCriterion("first_name <=", value, "firstName");
            return this;
        }

        public Criteria andFirstNameLike(String value) {
            addCriterion("first_name like", value, "firstName");
            return this;
        }

        public Criteria andFirstNameNotLike(String value) {
            addCriterion("first_name not like", value, "firstName");
            return this;
        }

        public Criteria andFirstNameIn(List<String> values) {
            addCriterion("first_name in", values, "firstName");
            return this;
        }

        public Criteria andFirstNameNotIn(List<String> values) {
            addCriterion("first_name not in", values, "firstName");
            return this;
        }

        public Criteria andFirstNameBetween(String value1, String value2) {
            addCriterion("first_name between", value1, value2, "firstName");
            return this;
        }

        public Criteria andFirstNameNotBetween(String value1, String value2) {
            addCriterion("first_name not between", value1, value2, "firstName");
            return this;
        }

        public Criteria andMiddleNameIsNull() {
            addCriterion("middle_name is null");
            return this;
        }

        public Criteria andMiddleNameIsNotNull() {
            addCriterion("middle_name is not null");
            return this;
        }

        public Criteria andMiddleNameEqualTo(String value) {
            addCriterion("middle_name =", value, "middleName");
            return this;
        }

        public Criteria andMiddleNameNotEqualTo(String value) {
            addCriterion("middle_name <>", value, "middleName");
            return this;
        }

        public Criteria andMiddleNameGreaterThan(String value) {
            addCriterion("middle_name >", value, "middleName");
            return this;
        }

        public Criteria andMiddleNameGreaterThanOrEqualTo(String value) {
            addCriterion("middle_name >=", value, "middleName");
            return this;
        }

        public Criteria andMiddleNameLessThan(String value) {
            addCriterion("middle_name <", value, "middleName");
            return this;
        }

        public Criteria andMiddleNameLessThanOrEqualTo(String value) {
            addCriterion("middle_name <=", value, "middleName");
            return this;
        }

        public Criteria andMiddleNameLike(String value) {
            addCriterion("middle_name like", value, "middleName");
            return this;
        }

        public Criteria andMiddleNameNotLike(String value) {
            addCriterion("middle_name not like", value, "middleName");
            return this;
        }

        public Criteria andMiddleNameIn(List<String> values) {
            addCriterion("middle_name in", values, "middleName");
            return this;
        }

        public Criteria andMiddleNameNotIn(List<String> values) {
            addCriterion("middle_name not in", values, "middleName");
            return this;
        }

        public Criteria andMiddleNameBetween(String value1, String value2) {
            addCriterion("middle_name between", value1, value2, "middleName");
            return this;
        }

        public Criteria andMiddleNameNotBetween(String value1, String value2) {
            addCriterion("middle_name not between", value1, value2, "middleName");
            return this;
        }

        public Criteria andLastNameIsNull() {
            addCriterion("last_name is null");
            return this;
        }

        public Criteria andLastNameIsNotNull() {
            addCriterion("last_name is not null");
            return this;
        }

        public Criteria andLastNameEqualTo(String value) {
            addCriterion("last_name =", value, "lastName");
            return this;
        }

        public Criteria andLastNameNotEqualTo(String value) {
            addCriterion("last_name <>", value, "lastName");
            return this;
        }

        public Criteria andLastNameGreaterThan(String value) {
            addCriterion("last_name >", value, "lastName");
            return this;
        }

        public Criteria andLastNameGreaterThanOrEqualTo(String value) {
            addCriterion("last_name >=", value, "lastName");
            return this;
        }

        public Criteria andLastNameLessThan(String value) {
            addCriterion("last_name <", value, "lastName");
            return this;
        }

        public Criteria andLastNameLessThanOrEqualTo(String value) {
            addCriterion("last_name <=", value, "lastName");
            return this;
        }

        public Criteria andLastNameLike(String value) {
            addCriterion("last_name like", value, "lastName");
            return this;
        }

        public Criteria andLastNameNotLike(String value) {
            addCriterion("last_name not like", value, "lastName");
            return this;
        }

        public Criteria andLastNameIn(List<String> values) {
            addCriterion("last_name in", values, "lastName");
            return this;
        }

        public Criteria andLastNameNotIn(List<String> values) {
            addCriterion("last_name not in", values, "lastName");
            return this;
        }

        public Criteria andLastNameBetween(String value1, String value2) {
            addCriterion("last_name between", value1, value2, "lastName");
            return this;
        }

        public Criteria andLastNameNotBetween(String value1, String value2) {
            addCriterion("last_name not between", value1, value2, "lastName");
            return this;
        }

        public Criteria andLevelIdIsNull() {
            addCriterion("level_id is null");
            return this;
        }

        public Criteria andLevelIdIsNotNull() {
            addCriterion("level_id is not null");
            return this;
        }

        public Criteria andLevelIdEqualTo(String value) {
            addCriterion("level_id =", value, "levelId");
            return this;
        }

        public Criteria andLevelIdNotEqualTo(String value) {
            addCriterion("level_id <>", value, "levelId");
            return this;
        }

        public Criteria andLevelIdGreaterThan(String value) {
            addCriterion("level_id >", value, "levelId");
            return this;
        }

        public Criteria andLevelIdGreaterThanOrEqualTo(String value) {
            addCriterion("level_id >=", value, "levelId");
            return this;
        }

        public Criteria andLevelIdLessThan(String value) {
            addCriterion("level_id <", value, "levelId");
            return this;
        }

        public Criteria andLevelIdLessThanOrEqualTo(String value) {
            addCriterion("level_id <=", value, "levelId");
            return this;
        }

        public Criteria andLevelIdLike(String value) {
            addCriterion("level_id like", value, "levelId");
            return this;
        }

        public Criteria andLevelIdNotLike(String value) {
            addCriterion("level_id not like", value, "levelId");
            return this;
        }

        public Criteria andLevelIdIn(List<String> values) {
            addCriterion("level_id in", values, "levelId");
            return this;
        }

        public Criteria andLevelIdNotIn(List<String> values) {
            addCriterion("level_id not in", values, "levelId");
            return this;
        }

        public Criteria andLevelIdBetween(String value1, String value2) {
            addCriterion("level_id between", value1, value2, "levelId");
            return this;
        }

        public Criteria andLevelIdNotBetween(String value1, String value2) {
            addCriterion("level_id not between", value1, value2, "levelId");
            return this;
        }

        public Criteria andGradeIdIsNull() {
            addCriterion("grade_id is null");
            return this;
        }

        public Criteria andGradeIdIsNotNull() {
            addCriterion("grade_id is not null");
            return this;
        }

        public Criteria andGradeIdEqualTo(Integer value) {
            addCriterion("grade_id =", value, "gradeId");
            return this;
        }

        public Criteria andGradeIdNotEqualTo(Integer value) {
            addCriterion("grade_id <>", value, "gradeId");
            return this;
        }

        public Criteria andGradeIdGreaterThan(Integer value) {
            addCriterion("grade_id >", value, "gradeId");
            return this;
        }

        public Criteria andGradeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade_id >=", value, "gradeId");
            return this;
        }

        public Criteria andGradeIdLessThan(Integer value) {
            addCriterion("grade_id <", value, "gradeId");
            return this;
        }

        public Criteria andGradeIdLessThanOrEqualTo(Integer value) {
            addCriterion("grade_id <=", value, "gradeId");
            return this;
        }

        public Criteria andGradeIdIn(List<Integer> values) {
            addCriterion("grade_id in", values, "gradeId");
            return this;
        }

        public Criteria andGradeIdNotIn(List<Integer> values) {
            addCriterion("grade_id not in", values, "gradeId");
            return this;
        }

        public Criteria andGradeIdBetween(Integer value1, Integer value2) {
            addCriterion("grade_id between", value1, value2, "gradeId");
            return this;
        }

        public Criteria andGradeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("grade_id not between", value1, value2, "gradeId");
            return this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return this;
        }

        public Criteria andAreaIdEqualTo(String value) {
            addCriterion("area_id =", value, "areaId");
            return this;
        }

        public Criteria andAreaIdNotEqualTo(String value) {
            addCriterion("area_id <>", value, "areaId");
            return this;
        }

        public Criteria andAreaIdGreaterThan(String value) {
            addCriterion("area_id >", value, "areaId");
            return this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(String value) {
            addCriterion("area_id >=", value, "areaId");
            return this;
        }

        public Criteria andAreaIdLessThan(String value) {
            addCriterion("area_id <", value, "areaId");
            return this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(String value) {
            addCriterion("area_id <=", value, "areaId");
            return this;
        }

        public Criteria andAreaIdLike(String value) {
            addCriterion("area_id like", value, "areaId");
            return this;
        }

        public Criteria andAreaIdNotLike(String value) {
            addCriterion("area_id not like", value, "areaId");
            return this;
        }

        public Criteria andAreaIdIn(List<String> values) {
            addCriterion("area_id in", values, "areaId");
            return this;
        }

        public Criteria andAreaIdNotIn(List<String> values) {
            addCriterion("area_id not in", values, "areaId");
            return this;
        }

        public Criteria andAreaIdBetween(String value1, String value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return this;
        }

        public Criteria andAreaIdNotBetween(String value1, String value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return this;
        }

        public Criteria andDivisionIdIsNull() {
            addCriterion("division_id is null");
            return this;
        }

        public Criteria andDivisionIdIsNotNull() {
            addCriterion("division_id is not null");
            return this;
        }

        public Criteria andDivisionIdEqualTo(String value) {
            addCriterion("division_id =", value, "divisionId");
            return this;
        }

        public Criteria andDivisionIdNotEqualTo(String value) {
            addCriterion("division_id <>", value, "divisionId");
            return this;
        }

        public Criteria andDivisionIdGreaterThan(String value) {
            addCriterion("division_id >", value, "divisionId");
            return this;
        }

        public Criteria andDivisionIdGreaterThanOrEqualTo(String value) {
            addCriterion("division_id >=", value, "divisionId");
            return this;
        }

        public Criteria andDivisionIdLessThan(String value) {
            addCriterion("division_id <", value, "divisionId");
            return this;
        }

        public Criteria andDivisionIdLessThanOrEqualTo(String value) {
            addCriterion("division_id <=", value, "divisionId");
            return this;
        }

        public Criteria andDivisionIdLike(String value) {
            addCriterion("division_id like", value, "divisionId");
            return this;
        }

        public Criteria andDivisionIdNotLike(String value) {
            addCriterion("division_id not like", value, "divisionId");
            return this;
        }

        public Criteria andDivisionIdIn(List<String> values) {
            addCriterion("division_id in", values, "divisionId");
            return this;
        }

        public Criteria andDivisionIdNotIn(List<String> values) {
            addCriterion("division_id not in", values, "divisionId");
            return this;
        }

        public Criteria andDivisionIdBetween(String value1, String value2) {
            addCriterion("division_id between", value1, value2, "divisionId");
            return this;
        }

        public Criteria andDivisionIdNotBetween(String value1, String value2) {
            addCriterion("division_id not between", value1, value2, "divisionId");
            return this;
        }

        public Criteria andDepartmentIdIsNull() {
            addCriterion("department_id is null");
            return this;
        }

        public Criteria andDepartmentIdIsNotNull() {
            addCriterion("department_id is not null");
            return this;
        }

        public Criteria andDepartmentIdEqualTo(String value) {
            addCriterion("department_id =", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdNotEqualTo(String value) {
            addCriterion("department_id <>", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdGreaterThan(String value) {
            addCriterion("department_id >", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("department_id >=", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdLessThan(String value) {
            addCriterion("department_id <", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdLessThanOrEqualTo(String value) {
            addCriterion("department_id <=", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdLike(String value) {
            addCriterion("department_id like", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdNotLike(String value) {
            addCriterion("department_id not like", value, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdIn(List<String> values) {
            addCriterion("department_id in", values, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdNotIn(List<String> values) {
            addCriterion("department_id not in", values, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdBetween(String value1, String value2) {
            addCriterion("department_id between", value1, value2, "departmentId");
            return this;
        }

        public Criteria andDepartmentIdNotBetween(String value1, String value2) {
            addCriterion("department_id not between", value1, value2, "departmentId");
            return this;
        }

        public Criteria andStationIdIsNull() {
            addCriterion("station_id is null");
            return this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("station_id is not null");
            return this;
        }

        public Criteria andStationIdEqualTo(String value) {
            addCriterion("station_id =", value, "stationId");
            return this;
        }

        public Criteria andStationIdNotEqualTo(String value) {
            addCriterion("station_id <>", value, "stationId");
            return this;
        }

        public Criteria andStationIdGreaterThan(String value) {
            addCriterion("station_id >", value, "stationId");
            return this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(String value) {
            addCriterion("station_id >=", value, "stationId");
            return this;
        }

        public Criteria andStationIdLessThan(String value) {
            addCriterion("station_id <", value, "stationId");
            return this;
        }

        public Criteria andStationIdLessThanOrEqualTo(String value) {
            addCriterion("station_id <=", value, "stationId");
            return this;
        }

        public Criteria andStationIdLike(String value) {
            addCriterion("station_id like", value, "stationId");
            return this;
        }

        public Criteria andStationIdNotLike(String value) {
            addCriterion("station_id not like", value, "stationId");
            return this;
        }

        public Criteria andStationIdIn(List<String> values) {
            addCriterion("station_id in", values, "stationId");
            return this;
        }

        public Criteria andStationIdNotIn(List<String> values) {
            addCriterion("station_id not in", values, "stationId");
            return this;
        }

        public Criteria andStationIdBetween(String value1, String value2) {
            addCriterion("station_id between", value1, value2, "stationId");
            return this;
        }

        public Criteria andStationIdNotBetween(String value1, String value2) {
            addCriterion("station_id not between", value1, value2, "stationId");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return this;
        }

        public Criteria andStrataIdIsNull() {
            addCriterion("strata_id is null");
            return this;
        }

        public Criteria andStrataIdIsNotNull() {
            addCriterion("strata_id is not null");
            return this;
        }

        public Criteria andStrataIdEqualTo(String value) {
            addCriterion("strata_id =", value, "strataId");
            return this;
        }

        public Criteria andStrataIdNotEqualTo(String value) {
            addCriterion("strata_id <>", value, "strataId");
            return this;
        }

        public Criteria andStrataIdGreaterThan(String value) {
            addCriterion("strata_id >", value, "strataId");
            return this;
        }

        public Criteria andStrataIdGreaterThanOrEqualTo(String value) {
            addCriterion("strata_id >=", value, "strataId");
            return this;
        }

        public Criteria andStrataIdLessThan(String value) {
            addCriterion("strata_id <", value, "strataId");
            return this;
        }

        public Criteria andStrataIdLessThanOrEqualTo(String value) {
            addCriterion("strata_id <=", value, "strataId");
            return this;
        }

        public Criteria andStrataIdLike(String value) {
            addCriterion("strata_id like", value, "strataId");
            return this;
        }

        public Criteria andStrataIdNotLike(String value) {
            addCriterion("strata_id not like", value, "strataId");
            return this;
        }

        public Criteria andStrataIdIn(List<String> values) {
            addCriterion("strata_id in", values, "strataId");
            return this;
        }

        public Criteria andStrataIdNotIn(List<String> values) {
            addCriterion("strata_id not in", values, "strataId");
            return this;
        }

        public Criteria andStrataIdBetween(String value1, String value2) {
            addCriterion("strata_id between", value1, value2, "strataId");
            return this;
        }

        public Criteria andStrataIdNotBetween(String value1, String value2) {
            addCriterion("strata_id not between", value1, value2, "strataId");
            return this;
        }

        public Criteria andJobTitleIdIsNull() {
            addCriterion("job_title_id is null");
            return this;
        }

        public Criteria andJobTitleIdIsNotNull() {
            addCriterion("job_title_id is not null");
            return this;
        }

        public Criteria andJobTitleIdEqualTo(String value) {
            addCriterion("job_title_id =", value, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdNotEqualTo(String value) {
            addCriterion("job_title_id <>", value, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdGreaterThan(String value) {
            addCriterion("job_title_id >", value, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdGreaterThanOrEqualTo(String value) {
            addCriterion("job_title_id >=", value, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdLessThan(String value) {
            addCriterion("job_title_id <", value, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdLessThanOrEqualTo(String value) {
            addCriterion("job_title_id <=", value, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdLike(String value) {
            addCriterion("job_title_id like", value, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdNotLike(String value) {
            addCriterion("job_title_id not like", value, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdIn(List<String> values) {
            addCriterion("job_title_id in", values, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdNotIn(List<String> values) {
            addCriterion("job_title_id not in", values, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdBetween(String value1, String value2) {
            addCriterion("job_title_id between", value1, value2, "jobTitleId");
            return this;
        }

        public Criteria andJobTitleIdNotBetween(String value1, String value2) {
            addCriterion("job_title_id not between", value1, value2, "jobTitleId");
            return this;
        }
    }
}