package com.ckb.wo.client.model;

import java.io.Serializable;
import java.util.Date;

public class MdaManifestDetail implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_manifest_detail.da
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	private Long da;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_manifest_detail.manifest_no
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	private Long manifestNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_manifest_detail.comment
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	private String comment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_manifest_detail.cons_no
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	private Double consNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_manifest_detail.user_updated
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	private String userUpdated;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_manifest_detail.datetime_updated
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	private Date datetimeUpdated;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_manifest_detail
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_manifest_detail.da
	 * @return  the value of t_manifest_detail.da
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public Long getDa() {
		return da;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_manifest_detail.da
	 * @param da  the value for t_manifest_detail.da
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public void setDa(Long da) {
		this.da = da;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_manifest_detail.manifest_no
	 * @return  the value of t_manifest_detail.manifest_no
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public Long getManifestNo() {
		return manifestNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_manifest_detail.manifest_no
	 * @param manifestNo  the value for t_manifest_detail.manifest_no
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public void setManifestNo(Long manifestNo) {
		this.manifestNo = manifestNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_manifest_detail.comment
	 * @return  the value of t_manifest_detail.comment
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_manifest_detail.comment
	 * @param comment  the value for t_manifest_detail.comment
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public void setComment(String comment) {
		this.comment = comment == null ? null : comment.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_manifest_detail.cons_no
	 * @return  the value of t_manifest_detail.cons_no
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public Double getConsNo() {
		return consNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_manifest_detail.cons_no
	 * @param consNo  the value for t_manifest_detail.cons_no
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public void setConsNo(Double consNo) {
		this.consNo = consNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_manifest_detail.user_updated
	 * @return  the value of t_manifest_detail.user_updated
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public String getUserUpdated() {
		return userUpdated;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_manifest_detail.user_updated
	 * @param userUpdated  the value for t_manifest_detail.user_updated
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public void setUserUpdated(String userUpdated) {
		this.userUpdated = userUpdated == null ? null : userUpdated.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_manifest_detail.datetime_updated
	 * @return  the value of t_manifest_detail.datetime_updated
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public Date getDatetimeUpdated() {
		return datetimeUpdated;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_manifest_detail.datetime_updated
	 * @param datetimeUpdated  the value for t_manifest_detail.datetime_updated
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	public void setDatetimeUpdated(Date datetimeUpdated) {
		this.datetimeUpdated = datetimeUpdated;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_manifest_detail
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof MdaManifestDetail)) {
			return false;
		}
		MdaManifestDetail other = (MdaManifestDetail) that;
		return this.getDa() == null ? other == null : this.getDa().equals(
				other.getDa())
				&& this.getManifestNo() == null ? other == null : this
				.getManifestNo().equals(other.getManifestNo())
				&& this.getComment() == null ? other == null : this
				.getComment().equals(other.getComment())
				&& this.getConsNo() == null ? other == null : this.getConsNo()
				.equals(other.getConsNo())
				&& this.getUserUpdated() == null ? other == null : this
				.getUserUpdated().equals(other.getUserUpdated())
				&& this.getDatetimeUpdated() == null ? other == null : this
				.getDatetimeUpdated().equals(other.getDatetimeUpdated());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_manifest_detail
	 * @ibatorgenerated  Tue Jul 06 16:43:03 SGT 2010
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getDa() != null) {
			hash *= getDa().hashCode();
		}
		if (getManifestNo() != null) {
			hash *= getManifestNo().hashCode();
		}
		if (getComment() != null) {
			hash *= getComment().hashCode();
		}
		if (getConsNo() != null) {
			hash *= getConsNo().hashCode();
		}
		if (getUserUpdated() != null) {
			hash *= getUserUpdated().hashCode();
		}
		if (getDatetimeUpdated() != null) {
			hash *= getDatetimeUpdated().hashCode();
		}
		return hash;
	}
}