package com.ckb.wo.client.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StationExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    protected List<Criteria> oredCriteria;
    
    protected String limitClause;
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public StationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    protected StationExample(StationExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }
    
    public void setLimitClause(String limitClause) {
        this.limitClause = limitClause;
    }

    public String getLimitClause() {
        return limitClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_station
     *
     * @ibatorgenerated Sat May 28 22:30:09 ICT 2022
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue; 
        protected String andCustomSQL;
        protected String orCustomSQL;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andStationIdIsNull() {
            addCriterion("station_id is null");
            return this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("station_id is not null");
            return this;
        }

        public Criteria andStationIdEqualTo(String value) {
            addCriterion("station_id =", value, "stationId");
            return this;
        }

        public Criteria andStationIdNotEqualTo(String value) {
            addCriterion("station_id <>", value, "stationId");
            return this;
        }

        public Criteria andStationIdGreaterThan(String value) {
            addCriterion("station_id >", value, "stationId");
            return this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(String value) {
            addCriterion("station_id >=", value, "stationId");
            return this;
        }

        public Criteria andStationIdLessThan(String value) {
            addCriterion("station_id <", value, "stationId");
            return this;
        }

        public Criteria andStationIdLessThanOrEqualTo(String value) {
            addCriterion("station_id <=", value, "stationId");
            return this;
        }

        public Criteria andStationIdLike(String value) {
            addCriterion("station_id like", value, "stationId");
            return this;
        }

        public Criteria andStationIdNotLike(String value) {
            addCriterion("station_id not like", value, "stationId");
            return this;
        }

        public Criteria andStationIdIn(List<String> values) {
            addCriterion("station_id in", values, "stationId");
            return this;
        }

        public Criteria andStationIdNotIn(List<String> values) {
            addCriterion("station_id not in", values, "stationId");
            return this;
        }

        public Criteria andStationIdBetween(String value1, String value2) {
            addCriterion("station_id between", value1, value2, "stationId");
            return this;
        }

        public Criteria andStationIdNotBetween(String value1, String value2) {
            addCriterion("station_id not between", value1, value2, "stationId");
            return this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return this;
        }

        public Criteria andCityIdEqualTo(String value) {
            addCriterion("city_id =", value, "cityId");
            return this;
        }

        public Criteria andCityIdNotEqualTo(String value) {
            addCriterion("city_id <>", value, "cityId");
            return this;
        }

        public Criteria andCityIdGreaterThan(String value) {
            addCriterion("city_id >", value, "cityId");
            return this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(String value) {
            addCriterion("city_id >=", value, "cityId");
            return this;
        }

        public Criteria andCityIdLessThan(String value) {
            addCriterion("city_id <", value, "cityId");
            return this;
        }

        public Criteria andCityIdLessThanOrEqualTo(String value) {
            addCriterion("city_id <=", value, "cityId");
            return this;
        }

        public Criteria andCityIdLike(String value) {
            addCriterion("city_id like", value, "cityId");
            return this;
        }

        public Criteria andCityIdNotLike(String value) {
            addCriterion("city_id not like", value, "cityId");
            return this;
        }

        public Criteria andCityIdIn(List<String> values) {
            addCriterion("city_id in", values, "cityId");
            return this;
        }

        public Criteria andCityIdNotIn(List<String> values) {
            addCriterion("city_id not in", values, "cityId");
            return this;
        }

        public Criteria andCityIdBetween(String value1, String value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return this;
        }

        public Criteria andCityIdNotBetween(String value1, String value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return this;
        }

        public Criteria andStationDescIsNull() {
            addCriterion("station_desc is null");
            return this;
        }

        public Criteria andStationDescIsNotNull() {
            addCriterion("station_desc is not null");
            return this;
        }

        public Criteria andStationDescEqualTo(String value) {
            addCriterion("station_desc =", value, "stationDesc");
            return this;
        }

        public Criteria andStationDescNotEqualTo(String value) {
            addCriterion("station_desc <>", value, "stationDesc");
            return this;
        }

        public Criteria andStationDescGreaterThan(String value) {
            addCriterion("station_desc >", value, "stationDesc");
            return this;
        }

        public Criteria andStationDescGreaterThanOrEqualTo(String value) {
            addCriterion("station_desc >=", value, "stationDesc");
            return this;
        }

        public Criteria andStationDescLessThan(String value) {
            addCriterion("station_desc <", value, "stationDesc");
            return this;
        }

        public Criteria andStationDescLessThanOrEqualTo(String value) {
            addCriterion("station_desc <=", value, "stationDesc");
            return this;
        }

        public Criteria andStationDescLike(String value) {
            addCriterion("station_desc like", value, "stationDesc");
            return this;
        }

        public Criteria andStationDescNotLike(String value) {
            addCriterion("station_desc not like", value, "stationDesc");
            return this;
        }

        public Criteria andStationDescIn(List<String> values) {
            addCriterion("station_desc in", values, "stationDesc");
            return this;
        }

        public Criteria andStationDescNotIn(List<String> values) {
            addCriterion("station_desc not in", values, "stationDesc");
            return this;
        }

        public Criteria andStationDescBetween(String value1, String value2) {
            addCriterion("station_desc between", value1, value2, "stationDesc");
            return this;
        }

        public Criteria andStationDescNotBetween(String value1, String value2) {
            addCriterion("station_desc not between", value1, value2, "stationDesc");
            return this;
        }

        public Criteria andAddress1IsNull() {
            addCriterion("address1 is null");
            return this;
        }

        public Criteria andAddress1IsNotNull() {
            addCriterion("address1 is not null");
            return this;
        }

        public Criteria andAddress1EqualTo(String value) {
            addCriterion("address1 =", value, "address1");
            return this;
        }

        public Criteria andAddress1NotEqualTo(String value) {
            addCriterion("address1 <>", value, "address1");
            return this;
        }

        public Criteria andAddress1GreaterThan(String value) {
            addCriterion("address1 >", value, "address1");
            return this;
        }

        public Criteria andAddress1GreaterThanOrEqualTo(String value) {
            addCriterion("address1 >=", value, "address1");
            return this;
        }

        public Criteria andAddress1LessThan(String value) {
            addCriterion("address1 <", value, "address1");
            return this;
        }

        public Criteria andAddress1LessThanOrEqualTo(String value) {
            addCriterion("address1 <=", value, "address1");
            return this;
        }

        public Criteria andAddress1Like(String value) {
            addCriterion("address1 like", value, "address1");
            return this;
        }

        public Criteria andAddress1NotLike(String value) {
            addCriterion("address1 not like", value, "address1");
            return this;
        }

        public Criteria andAddress1In(List<String> values) {
            addCriterion("address1 in", values, "address1");
            return this;
        }

        public Criteria andAddress1NotIn(List<String> values) {
            addCriterion("address1 not in", values, "address1");
            return this;
        }

        public Criteria andAddress1Between(String value1, String value2) {
            addCriterion("address1 between", value1, value2, "address1");
            return this;
        }

        public Criteria andAddress1NotBetween(String value1, String value2) {
            addCriterion("address1 not between", value1, value2, "address1");
            return this;
        }

        public Criteria andAddress2IsNull() {
            addCriterion("address2 is null");
            return this;
        }

        public Criteria andAddress2IsNotNull() {
            addCriterion("address2 is not null");
            return this;
        }

        public Criteria andAddress2EqualTo(String value) {
            addCriterion("address2 =", value, "address2");
            return this;
        }

        public Criteria andAddress2NotEqualTo(String value) {
            addCriterion("address2 <>", value, "address2");
            return this;
        }

        public Criteria andAddress2GreaterThan(String value) {
            addCriterion("address2 >", value, "address2");
            return this;
        }

        public Criteria andAddress2GreaterThanOrEqualTo(String value) {
            addCriterion("address2 >=", value, "address2");
            return this;
        }

        public Criteria andAddress2LessThan(String value) {
            addCriterion("address2 <", value, "address2");
            return this;
        }

        public Criteria andAddress2LessThanOrEqualTo(String value) {
            addCriterion("address2 <=", value, "address2");
            return this;
        }

        public Criteria andAddress2Like(String value) {
            addCriterion("address2 like", value, "address2");
            return this;
        }

        public Criteria andAddress2NotLike(String value) {
            addCriterion("address2 not like", value, "address2");
            return this;
        }

        public Criteria andAddress2In(List<String> values) {
            addCriterion("address2 in", values, "address2");
            return this;
        }

        public Criteria andAddress2NotIn(List<String> values) {
            addCriterion("address2 not in", values, "address2");
            return this;
        }

        public Criteria andAddress2Between(String value1, String value2) {
            addCriterion("address2 between", value1, value2, "address2");
            return this;
        }

        public Criteria andAddress2NotBetween(String value1, String value2) {
            addCriterion("address2 not between", value1, value2, "address2");
            return this;
        }

        public Criteria andPostalCodeIsNull() {
            addCriterion("postal_code is null");
            return this;
        }

        public Criteria andPostalCodeIsNotNull() {
            addCriterion("postal_code is not null");
            return this;
        }

        public Criteria andPostalCodeEqualTo(String value) {
            addCriterion("postal_code =", value, "postalCode");
            return this;
        }

        public Criteria andPostalCodeNotEqualTo(String value) {
            addCriterion("postal_code <>", value, "postalCode");
            return this;
        }

        public Criteria andPostalCodeGreaterThan(String value) {
            addCriterion("postal_code >", value, "postalCode");
            return this;
        }

        public Criteria andPostalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("postal_code >=", value, "postalCode");
            return this;
        }

        public Criteria andPostalCodeLessThan(String value) {
            addCriterion("postal_code <", value, "postalCode");
            return this;
        }

        public Criteria andPostalCodeLessThanOrEqualTo(String value) {
            addCriterion("postal_code <=", value, "postalCode");
            return this;
        }

        public Criteria andPostalCodeLike(String value) {
            addCriterion("postal_code like", value, "postalCode");
            return this;
        }

        public Criteria andPostalCodeNotLike(String value) {
            addCriterion("postal_code not like", value, "postalCode");
            return this;
        }

        public Criteria andPostalCodeIn(List<String> values) {
            addCriterion("postal_code in", values, "postalCode");
            return this;
        }

        public Criteria andPostalCodeNotIn(List<String> values) {
            addCriterion("postal_code not in", values, "postalCode");
            return this;
        }

        public Criteria andPostalCodeBetween(String value1, String value2) {
            addCriterion("postal_code between", value1, value2, "postalCode");
            return this;
        }

        public Criteria andPostalCodeNotBetween(String value1, String value2) {
            addCriterion("postal_code not between", value1, value2, "postalCode");
            return this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return this;
        }

        public Criteria andFaxIsNull() {
            addCriterion("fax is null");
            return this;
        }

        public Criteria andFaxIsNotNull() {
            addCriterion("fax is not null");
            return this;
        }

        public Criteria andFaxEqualTo(String value) {
            addCriterion("fax =", value, "fax");
            return this;
        }

        public Criteria andFaxNotEqualTo(String value) {
            addCriterion("fax <>", value, "fax");
            return this;
        }

        public Criteria andFaxGreaterThan(String value) {
            addCriterion("fax >", value, "fax");
            return this;
        }

        public Criteria andFaxGreaterThanOrEqualTo(String value) {
            addCriterion("fax >=", value, "fax");
            return this;
        }

        public Criteria andFaxLessThan(String value) {
            addCriterion("fax <", value, "fax");
            return this;
        }

        public Criteria andFaxLessThanOrEqualTo(String value) {
            addCriterion("fax <=", value, "fax");
            return this;
        }

        public Criteria andFaxLike(String value) {
            addCriterion("fax like", value, "fax");
            return this;
        }

        public Criteria andFaxNotLike(String value) {
            addCriterion("fax not like", value, "fax");
            return this;
        }

        public Criteria andFaxIn(List<String> values) {
            addCriterion("fax in", values, "fax");
            return this;
        }

        public Criteria andFaxNotIn(List<String> values) {
            addCriterion("fax not in", values, "fax");
            return this;
        }

        public Criteria andFaxBetween(String value1, String value2) {
            addCriterion("fax between", value1, value2, "fax");
            return this;
        }

        public Criteria andFaxNotBetween(String value1, String value2) {
            addCriterion("fax not between", value1, value2, "fax");
            return this;
        }

        public Criteria andProvinceIdIsNull() {
            addCriterion("province_id is null");
            return this;
        }

        public Criteria andProvinceIdIsNotNull() {
            addCriterion("province_id is not null");
            return this;
        }

        public Criteria andProvinceIdEqualTo(String value) {
            addCriterion("province_id =", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdNotEqualTo(String value) {
            addCriterion("province_id <>", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdGreaterThan(String value) {
            addCriterion("province_id >", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdGreaterThanOrEqualTo(String value) {
            addCriterion("province_id >=", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdLessThan(String value) {
            addCriterion("province_id <", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdLessThanOrEqualTo(String value) {
            addCriterion("province_id <=", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdLike(String value) {
            addCriterion("province_id like", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdNotLike(String value) {
            addCriterion("province_id not like", value, "provinceId");
            return this;
        }

        public Criteria andProvinceIdIn(List<String> values) {
            addCriterion("province_id in", values, "provinceId");
            return this;
        }

        public Criteria andProvinceIdNotIn(List<String> values) {
            addCriterion("province_id not in", values, "provinceId");
            return this;
        }

        public Criteria andProvinceIdBetween(String value1, String value2) {
            addCriterion("province_id between", value1, value2, "provinceId");
            return this;
        }

        public Criteria andProvinceIdNotBetween(String value1, String value2) {
            addCriterion("province_id not between", value1, value2, "provinceId");
            return this;
        }

        public Criteria andCountryIdIsNull() {
            addCriterion("country_id is null");
            return this;
        }

        public Criteria andCountryIdIsNotNull() {
            addCriterion("country_id is not null");
            return this;
        }

        public Criteria andCountryIdEqualTo(String value) {
            addCriterion("country_id =", value, "countryId");
            return this;
        }

        public Criteria andCountryIdNotEqualTo(String value) {
            addCriterion("country_id <>", value, "countryId");
            return this;
        }

        public Criteria andCountryIdGreaterThan(String value) {
            addCriterion("country_id >", value, "countryId");
            return this;
        }

        public Criteria andCountryIdGreaterThanOrEqualTo(String value) {
            addCriterion("country_id >=", value, "countryId");
            return this;
        }

        public Criteria andCountryIdLessThan(String value) {
            addCriterion("country_id <", value, "countryId");
            return this;
        }

        public Criteria andCountryIdLessThanOrEqualTo(String value) {
            addCriterion("country_id <=", value, "countryId");
            return this;
        }

        public Criteria andCountryIdLike(String value) {
            addCriterion("country_id like", value, "countryId");
            return this;
        }

        public Criteria andCountryIdNotLike(String value) {
            addCriterion("country_id not like", value, "countryId");
            return this;
        }

        public Criteria andCountryIdIn(List<String> values) {
            addCriterion("country_id in", values, "countryId");
            return this;
        }

        public Criteria andCountryIdNotIn(List<String> values) {
            addCriterion("country_id not in", values, "countryId");
            return this;
        }

        public Criteria andCountryIdBetween(String value1, String value2) {
            addCriterion("country_id between", value1, value2, "countryId");
            return this;
        }

        public Criteria andCountryIdNotBetween(String value1, String value2) {
            addCriterion("country_id not between", value1, value2, "countryId");
            return this;
        }

        public Criteria andKpbcIsNull() {
            addCriterion("kpbc is null");
            return this;
        }

        public Criteria andKpbcIsNotNull() {
            addCriterion("kpbc is not null");
            return this;
        }

        public Criteria andKpbcEqualTo(String value) {
            addCriterion("kpbc =", value, "kpbc");
            return this;
        }

        public Criteria andKpbcNotEqualTo(String value) {
            addCriterion("kpbc <>", value, "kpbc");
            return this;
        }

        public Criteria andKpbcGreaterThan(String value) {
            addCriterion("kpbc >", value, "kpbc");
            return this;
        }

        public Criteria andKpbcGreaterThanOrEqualTo(String value) {
            addCriterion("kpbc >=", value, "kpbc");
            return this;
        }

        public Criteria andKpbcLessThan(String value) {
            addCriterion("kpbc <", value, "kpbc");
            return this;
        }

        public Criteria andKpbcLessThanOrEqualTo(String value) {
            addCriterion("kpbc <=", value, "kpbc");
            return this;
        }

        public Criteria andKpbcLike(String value) {
            addCriterion("kpbc like", value, "kpbc");
            return this;
        }

        public Criteria andKpbcNotLike(String value) {
            addCriterion("kpbc not like", value, "kpbc");
            return this;
        }

        public Criteria andKpbcIn(List<String> values) {
            addCriterion("kpbc in", values, "kpbc");
            return this;
        }

        public Criteria andKpbcNotIn(List<String> values) {
            addCriterion("kpbc not in", values, "kpbc");
            return this;
        }

        public Criteria andKpbcBetween(String value1, String value2) {
            addCriterion("kpbc between", value1, value2, "kpbc");
            return this;
        }

        public Criteria andKpbcNotBetween(String value1, String value2) {
            addCriterion("kpbc not between", value1, value2, "kpbc");
            return this;
        }

        public Criteria andUserUpdatedIsNull() {
            addCriterion("user_updated is null");
            return this;
        }

        public Criteria andUserUpdatedIsNotNull() {
            addCriterion("user_updated is not null");
            return this;
        }

        public Criteria andUserUpdatedEqualTo(String value) {
            addCriterion("user_updated =", value, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedNotEqualTo(String value) {
            addCriterion("user_updated <>", value, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedGreaterThan(String value) {
            addCriterion("user_updated >", value, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedGreaterThanOrEqualTo(String value) {
            addCriterion("user_updated >=", value, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedLessThan(String value) {
            addCriterion("user_updated <", value, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedLessThanOrEqualTo(String value) {
            addCriterion("user_updated <=", value, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedLike(String value) {
            addCriterion("user_updated like", value, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedNotLike(String value) {
            addCriterion("user_updated not like", value, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedIn(List<String> values) {
            addCriterion("user_updated in", values, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedNotIn(List<String> values) {
            addCriterion("user_updated not in", values, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedBetween(String value1, String value2) {
            addCriterion("user_updated between", value1, value2, "userUpdated");
            return this;
        }

        public Criteria andUserUpdatedNotBetween(String value1, String value2) {
            addCriterion("user_updated not between", value1, value2, "userUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedIsNull() {
            addCriterion("datetime_updated is null");
            return this;
        }

        public Criteria andDatetimeUpdatedIsNotNull() {
            addCriterion("datetime_updated is not null");
            return this;
        }

        public Criteria andDatetimeUpdatedEqualTo(Date value) {
            addCriterion("datetime_updated =", value, "datetimeUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedNotEqualTo(Date value) {
            addCriterion("datetime_updated <>", value, "datetimeUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedGreaterThan(Date value) {
            addCriterion("datetime_updated >", value, "datetimeUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("datetime_updated >=", value, "datetimeUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedLessThan(Date value) {
            addCriterion("datetime_updated <", value, "datetimeUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("datetime_updated <=", value, "datetimeUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedIn(List<Date> values) {
            addCriterion("datetime_updated in", values, "datetimeUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedNotIn(List<Date> values) {
            addCriterion("datetime_updated not in", values, "datetimeUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedBetween(Date value1, Date value2) {
            addCriterion("datetime_updated between", value1, value2, "datetimeUpdated");
            return this;
        }

        public Criteria andDatetimeUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("datetime_updated not between", value1, value2, "datetimeUpdated");
            return this;
        }

        public Criteria andCkbBranchIsNull() {
            addCriterion("ckb_branch is null");
            return this;
        }

        public Criteria andCkbBranchIsNotNull() {
            addCriterion("ckb_branch is not null");
            return this;
        }

        public Criteria andCkbBranchEqualTo(String value) {
            addCriterion("ckb_branch =", value, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchNotEqualTo(String value) {
            addCriterion("ckb_branch <>", value, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchGreaterThan(String value) {
            addCriterion("ckb_branch >", value, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchGreaterThanOrEqualTo(String value) {
            addCriterion("ckb_branch >=", value, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchLessThan(String value) {
            addCriterion("ckb_branch <", value, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchLessThanOrEqualTo(String value) {
            addCriterion("ckb_branch <=", value, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchLike(String value) {
            addCriterion("ckb_branch like", value, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchNotLike(String value) {
            addCriterion("ckb_branch not like", value, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchIn(List<String> values) {
            addCriterion("ckb_branch in", values, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchNotIn(List<String> values) {
            addCriterion("ckb_branch not in", values, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchBetween(String value1, String value2) {
            addCriterion("ckb_branch between", value1, value2, "ckbBranch");
            return this;
        }

        public Criteria andCkbBranchNotBetween(String value1, String value2) {
            addCriterion("ckb_branch not between", value1, value2, "ckbBranch");
            return this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return this;
        }

        public Criteria andEnabledEqualTo(String value) {
            addCriterion("enabled =", value, "enabled");
            return this;
        }

        public Criteria andEnabledNotEqualTo(String value) {
            addCriterion("enabled <>", value, "enabled");
            return this;
        }

        public Criteria andEnabledGreaterThan(String value) {
            addCriterion("enabled >", value, "enabled");
            return this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("enabled >=", value, "enabled");
            return this;
        }

        public Criteria andEnabledLessThan(String value) {
            addCriterion("enabled <", value, "enabled");
            return this;
        }

        public Criteria andEnabledLessThanOrEqualTo(String value) {
            addCriterion("enabled <=", value, "enabled");
            return this;
        }

        public Criteria andEnabledLike(String value) {
            addCriterion("enabled like", value, "enabled");
            return this;
        }

        public Criteria andEnabledNotLike(String value) {
            addCriterion("enabled not like", value, "enabled");
            return this;
        }

        public Criteria andEnabledIn(List<String> values) {
            addCriterion("enabled in", values, "enabled");
            return this;
        }

        public Criteria andEnabledNotIn(List<String> values) {
            addCriterion("enabled not in", values, "enabled");
            return this;
        }

        public Criteria andEnabledBetween(String value1, String value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return this;
        }

        public Criteria andEnabledNotBetween(String value1, String value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return this;
        }

        public Criteria andFlagDownloadIsNull() {
            addCriterion("flag_download is null");
            return this;
        }

        public Criteria andFlagDownloadIsNotNull() {
            addCriterion("flag_download is not null");
            return this;
        }

        public Criteria andFlagDownloadEqualTo(String value) {
            addCriterion("flag_download =", value, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadNotEqualTo(String value) {
            addCriterion("flag_download <>", value, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadGreaterThan(String value) {
            addCriterion("flag_download >", value, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadGreaterThanOrEqualTo(String value) {
            addCriterion("flag_download >=", value, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadLessThan(String value) {
            addCriterion("flag_download <", value, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadLessThanOrEqualTo(String value) {
            addCriterion("flag_download <=", value, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadLike(String value) {
            addCriterion("flag_download like", value, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadNotLike(String value) {
            addCriterion("flag_download not like", value, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadIn(List<String> values) {
            addCriterion("flag_download in", values, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadNotIn(List<String> values) {
            addCriterion("flag_download not in", values, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadBetween(String value1, String value2) {
            addCriterion("flag_download between", value1, value2, "flagDownload");
            return this;
        }

        public Criteria andFlagDownloadNotBetween(String value1, String value2) {
            addCriterion("flag_download not between", value1, value2, "flagDownload");
            return this;
        }
        
        public String getAndCustomSQL() {
            return andCustomSQL;
        }

        public Criteria setAndCustomSQL(String value) {
            andCustomSQL = value;
            return this;
        }

        public String getOrCustomSQL() {
            return orCustomSQL;
        }

        public Criteria setOrCustomSQL(String value) {
            orCustomSQL = value;
            return this;
        }
    }
}