package com.ckb.wo.client.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class User implements Serializable {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.employee_id
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String employeeId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.first_name
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String firstName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.middle_name
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String middleName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.last_name
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String lastName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.grantfrom
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private Date grantfrom;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.grantto
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private Date grantto;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.bossemployeeid
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String bossemployeeid;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.email
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String email;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.area_id
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String areaId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.division_id
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String divisionId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.department_id
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String departmentId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.station_id
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String stationId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.job_title_id
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String jobTitleId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.level_id
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private String levelId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tuser.isactiveuser
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private Boolean isactiveuser;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database table tuser
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    private static final long serialVersionUID = 1L;

    private User boss;
    private Area area = new Area();
    private Division division = new Division();
    private Department department = new Department();
    private JobTitle jobtitle = new JobTitle();
    private Level level = new Level();
    private List<Role> roles = new ArrayList<>();

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.employee_id
     *
     * @return the value of tuser.employee_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.employee_id
     *
     * @param employeeId the value for tuser.employee_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.first_name
     *
     * @return the value of tuser.first_name
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.first_name
     *
     * @param firstName the value for tuser.first_name
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.middle_name
     *
     * @return the value of tuser.middle_name
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.middle_name
     *
     * @param middleName the value for tuser.middle_name
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName == null ? null : middleName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.last_name
     *
     * @return the value of tuser.last_name
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.last_name
     *
     * @param lastName the value for tuser.last_name
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.grantfrom
     *
     * @return the value of tuser.grantfrom
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public Date getGrantfrom() {
        return grantfrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.grantfrom
     *
     * @param grantfrom the value for tuser.grantfrom
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setGrantfrom(Date grantfrom) {
        this.grantfrom = grantfrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.grantto
     *
     * @return the value of tuser.grantto
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public Date getGrantto() {
        return grantto;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.grantto
     *
     * @param grantto the value for tuser.grantto
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setGrantto(Date grantto) {
        this.grantto = grantto;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.bossemployeeid
     *
     * @return the value of tuser.bossemployeeid
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getBossemployeeid() {
        return bossemployeeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.bossemployeeid
     *
     * @param bossemployeeid the value for tuser.bossemployeeid
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setBossemployeeid(String bossemployeeid) {
        this.bossemployeeid = bossemployeeid == null ? null : bossemployeeid
                .trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.email
     *
     * @return the value of tuser.email
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.email
     *
     * @param email the value for tuser.email
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.area_id
     *
     * @return the value of tuser.area_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.area_id
     *
     * @param areaId the value for tuser.area_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.division_id
     *
     * @return the value of tuser.division_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getDivisionId() {
        return divisionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.division_id
     *
     * @param divisionId the value for tuser.division_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setDivisionId(String divisionId) {
        this.divisionId = divisionId == null ? null : divisionId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.department_id
     *
     * @return the value of tuser.department_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.department_id
     *
     * @param departmentId the value for tuser.department_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.station_id
     *
     * @return the value of tuser.station_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.station_id
     *
     * @param stationId the value for tuser.station_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.job_title_id
     *
     * @return the value of tuser.job_title_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getJobTitleId() {
        return jobTitleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.job_title_id
     *
     * @param jobTitleId the value for tuser.job_title_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setJobTitleId(String jobTitleId) {
        this.jobTitleId = jobTitleId == null ? null : jobTitleId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.level_id
     *
     * @return the value of tuser.level_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public String getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.level_id
     *
     * @param levelId the value for tuser.level_id
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setLevelId(String levelId) {
        this.levelId = levelId == null ? null : levelId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tuser.isactiveuser
     *
     * @return the value of tuser.isactiveuser
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public Boolean getIsactiveuser() {
        return isactiveuser;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tuser.isactiveuser
     *
     * @param isactiveuser the value for tuser.isactiveuser
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    public void setIsactiveuser(Boolean isactiveuser) {
        this.isactiveuser = isactiveuser;
    }

    public User getBoss() {
        return boss;
    }

    public void setBoss(User boss) {
        this.boss = boss;
    }

    public Area getArea() {
        return area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    public Division getDivision() {
        return division;
    }

    public void setDivision(Division division) {
        this.division = division;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public JobTitle getJobtitle() {
        return jobtitle;
    }

    public void setJobtitle(JobTitle jobtitle) {
        this.jobtitle = jobtitle;
    }

    public Level getLevel() {
        return level;
    }

    public void setLevel(Level level) {
        this.level = level;
    }

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @param that
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof User)) {
            return false;
        }
        User other = (User) that;
        return this.getEmployeeId() == null ? other == null : this
                .getEmployeeId().equals(other.getEmployeeId())
                && this.getFirstName() == null ? other == null : this
                .getFirstName().equals(other.getFirstName())
                && this.getMiddleName() == null ? other == null : this
                .getMiddleName().equals(other.getMiddleName())
                && this.getLastName() == null ? other == null : this
                .getLastName().equals(other.getLastName())
                && this.getGrantfrom() == null ? other == null : this
                .getGrantfrom().equals(other.getGrantfrom())
                && this.getGrantto() == null ? other == null : this
                .getGrantto().equals(other.getGrantto())
                && this.getBossemployeeid() == null ? other == null : this
                .getBossemployeeid().equals(other.getBossemployeeid())
                && this.getEmail() == null ? other == null : this.getEmail()
                .equals(other.getEmail())
                && this.getAreaId() == null ? other == null : this.getAreaId()
                .equals(other.getAreaId())
                && this.getDivisionId() == null ? other == null : this
                .getDivisionId().equals(other.getDivisionId())
                && this.getDepartmentId() == null ? other == null : this
                .getDepartmentId().equals(other.getDepartmentId())
                && this.getStationId() == null ? other == null : this
                .getStationId().equals(other.getStationId())
                && this.getJobTitleId() == null ? other == null : this
                .getJobTitleId().equals(other.getJobTitleId())
                && this.getLevelId() == null ? other == null : this
                .getLevelId().equals(other.getLevelId())
                && this.getIsactiveuser() == null ? other == null : this
                .getIsactiveuser().equals(other.getIsactiveuser());
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tuser
     *
     * @ibatorgenerated Thu Aug 05 13:34:27 SGT 2010
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getEmployeeId() != null) {
            hash *= getEmployeeId().hashCode();
        }
        if (getFirstName() != null) {
            hash *= getFirstName().hashCode();
        }
        if (getMiddleName() != null) {
            hash *= getMiddleName().hashCode();
        }
        if (getLastName() != null) {
            hash *= getLastName().hashCode();
        }
        if (getGrantfrom() != null) {
            hash *= getGrantfrom().hashCode();
        }
        if (getGrantto() != null) {
            hash *= getGrantto().hashCode();
        }
        if (getBossemployeeid() != null) {
            hash *= getBossemployeeid().hashCode();
        }
        if (getEmail() != null) {
            hash *= getEmail().hashCode();
        }
        if (getAreaId() != null) {
            hash *= getAreaId().hashCode();
        }
        if (getDivisionId() != null) {
            hash *= getDivisionId().hashCode();
        }
        if (getDepartmentId() != null) {
            hash *= getDepartmentId().hashCode();
        }
        if (getStationId() != null) {
            hash *= getStationId().hashCode();
        }
        if (getJobTitleId() != null) {
            hash *= getJobTitleId().hashCode();
        }
        if (getLevelId() != null) {
            hash *= getLevelId().hashCode();
        }
        if (getIsactiveuser() != null) {
            hash *= getIsactiveuser().hashCode();
        }
        return hash;
    }

    @Override
    public String toString() {
        return "User{" + "employeeId=" + employeeId + ", firstName=" + firstName + ", middleName=" + middleName + ", lastName=" + lastName + ", grantfrom=" + grantfrom + ", grantto=" + grantto + ", bossemployeeid=" + bossemployeeid + ", email=" + email + ", areaId=" + areaId + ", divisionId=" + divisionId + ", departmentId=" + departmentId + ", stationId=" + stationId + ", jobTitleId=" + jobTitleId + ", levelId=" + levelId + ", isactiveuser=" + isactiveuser + ", boss=" + boss + ", area=" + area + ", division=" + division + ", department=" + department + ", jobtitle=" + jobtitle + ", level=" + level + ", roles=" + roles + '}';
    }

}
