package com.ckb.wo.client.model;

import java.io.Serializable;
import java.util.Date;
import java.math.BigDecimal;

public class Vendor implements Serializable {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.tvendor_pk
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private Long tvendorPk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.vendorcode
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String vendorSAPID;

    public String getVendorSAPID() {
        return vendorSAPID;
    }

    public void setVendorSAPID(String vendorSAPID) {
        this.vendorSAPID = vendorSAPID;
    }
    private String vendorcode;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.vendorname
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String vendorname;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.ppn
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private BigDecimal ppn;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.pph
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private BigDecimal pph;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.address1
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String address1;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.address2
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String address2;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.tlocation_fk
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private Long tlocationFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.postalcode
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String postalcode;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.website
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String website;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.email
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String email;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.isactive
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private Boolean isactive;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.contactname
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String contactname;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.contactphone
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String contactphone;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.contactfax
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String contactfax;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.contactemail
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String contactemail;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.terms
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private Integer terms;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.flag_gst
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private Boolean flagGst;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.vendornpwp
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String vendornpwp;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.gl_no
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String glNo;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.remittanceaddress
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String remittanceaddress;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.vendorowner
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String vendorowner;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.updatedbyemployeeid
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private Integer updatedbyemployeeid;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.lastupdated
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private Date lastupdated;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.inactivefrom
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private Date inactivefrom;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.inactiveto
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private Date inactiveto;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tvendor.inactivereason
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private String inactivereason;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tvendor
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.tvendor_pk
     * @return  the value of tvendor.tvendor_pk
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public Long getTvendorPk() {
        return tvendorPk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.tvendor_pk
     * @param tvendorPk  the value for tvendor.tvendor_pk
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setTvendorPk(Long tvendorPk) {
        this.tvendorPk = tvendorPk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.vendorcode
     * @return  the value of tvendor.vendorcode
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getVendorcode() {
        return vendorcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.vendorcode
     * @param vendorcode  the value for tvendor.vendorcode
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setVendorcode(String vendorcode) {
        this.vendorcode = vendorcode == null ? null : vendorcode.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.vendorname
     * @return  the value of tvendor.vendorname
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getVendorname() {
        return vendorname;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.vendorname
     * @param vendorname  the value for tvendor.vendorname
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setVendorname(String vendorname) {
        this.vendorname = vendorname == null ? null : vendorname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.ppn
     * @return  the value of tvendor.ppn
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public BigDecimal getPpn() {
        return ppn;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.ppn
     * @param ppn  the value for tvendor.ppn
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setPpn(BigDecimal ppn) {
        this.ppn = ppn;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.pph
     * @return  the value of tvendor.pph
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public BigDecimal getPph() {
        return pph;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.pph
     * @param pph  the value for tvendor.pph
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setPph(BigDecimal pph) {
        this.pph = pph;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.address1
     * @return  the value of tvendor.address1
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.address1
     * @param address1  the value for tvendor.address1
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setAddress1(String address1) {
        this.address1 = address1 == null ? null : address1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.address2
     * @return  the value of tvendor.address2
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.address2
     * @param address2  the value for tvendor.address2
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.tlocation_fk
     * @return  the value of tvendor.tlocation_fk
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public Long getTlocationFk() {
        return tlocationFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.tlocation_fk
     * @param tlocationFk  the value for tvendor.tlocation_fk
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setTlocationFk(Long tlocationFk) {
        this.tlocationFk = tlocationFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.postalcode
     * @return  the value of tvendor.postalcode
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.postalcode
     * @param postalcode  the value for tvendor.postalcode
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.website
     * @return  the value of tvendor.website
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.website
     * @param website  the value for tvendor.website
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.email
     * @return  the value of tvendor.email
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.email
     * @param email  the value for tvendor.email
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.isactive
     * @return  the value of tvendor.isactive
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public Boolean getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.isactive
     * @param isactive  the value for tvendor.isactive
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.contactname
     * @return  the value of tvendor.contactname
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.contactname
     * @param contactname  the value for tvendor.contactname
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.contactphone
     * @return  the value of tvendor.contactphone
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getContactphone() {
        return contactphone;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.contactphone
     * @param contactphone  the value for tvendor.contactphone
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone == null ? null : contactphone.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.contactfax
     * @return  the value of tvendor.contactfax
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getContactfax() {
        return contactfax;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.contactfax
     * @param contactfax  the value for tvendor.contactfax
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setContactfax(String contactfax) {
        this.contactfax = contactfax == null ? null : contactfax.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.contactemail
     * @return  the value of tvendor.contactemail
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getContactemail() {
        return contactemail;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.contactemail
     * @param contactemail  the value for tvendor.contactemail
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setContactemail(String contactemail) {
        this.contactemail = contactemail == null ? null : contactemail.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.terms
     * @return  the value of tvendor.terms
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public Integer getTerms() {
        return terms;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.terms
     * @param terms  the value for tvendor.terms
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setTerms(Integer terms) {
        this.terms = terms;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.flag_gst
     * @return  the value of tvendor.flag_gst
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public Boolean getFlagGst() {
        return flagGst;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.flag_gst
     * @param flagGst  the value for tvendor.flag_gst
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setFlagGst(Boolean flagGst) {
        this.flagGst = flagGst;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.vendornpwp
     * @return  the value of tvendor.vendornpwp
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getVendornpwp() {
        return vendornpwp;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.vendornpwp
     * @param vendornpwp  the value for tvendor.vendornpwp
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setVendornpwp(String vendornpwp) {
        this.vendornpwp = vendornpwp == null ? null : vendornpwp.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.gl_no
     * @return  the value of tvendor.gl_no
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getGlNo() {
        return glNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.gl_no
     * @param glNo  the value for tvendor.gl_no
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setGlNo(String glNo) {
        this.glNo = glNo == null ? null : glNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.remittanceaddress
     * @return  the value of tvendor.remittanceaddress
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getRemittanceaddress() {
        return remittanceaddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.remittanceaddress
     * @param remittanceaddress  the value for tvendor.remittanceaddress
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setRemittanceaddress(String remittanceaddress) {
        this.remittanceaddress = remittanceaddress == null ? null
                : remittanceaddress.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.vendorowner
     * @return  the value of tvendor.vendorowner
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getVendorowner() {
        return vendorowner;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.vendorowner
     * @param vendorowner  the value for tvendor.vendorowner
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setVendorowner(String vendorowner) {
        this.vendorowner = vendorowner == null ? null : vendorowner.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.updatedbyemployeeid
     * @return  the value of tvendor.updatedbyemployeeid
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public Integer getUpdatedbyemployeeid() {
        return updatedbyemployeeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.updatedbyemployeeid
     * @param updatedbyemployeeid  the value for tvendor.updatedbyemployeeid
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setUpdatedbyemployeeid(Integer updatedbyemployeeid) {
        this.updatedbyemployeeid = updatedbyemployeeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.lastupdated
     * @return  the value of tvendor.lastupdated
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public Date getLastupdated() {
        return lastupdated;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.lastupdated
     * @param lastupdated  the value for tvendor.lastupdated
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setLastupdated(Date lastupdated) {
        this.lastupdated = lastupdated;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.inactivefrom
     * @return  the value of tvendor.inactivefrom
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public Date getInactivefrom() {
        return inactivefrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.inactivefrom
     * @param inactivefrom  the value for tvendor.inactivefrom
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setInactivefrom(Date inactivefrom) {
        this.inactivefrom = inactivefrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.inactiveto
     * @return  the value of tvendor.inactiveto
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public Date getInactiveto() {
        return inactiveto;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.inactiveto
     * @param inactiveto  the value for tvendor.inactiveto
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setInactiveto(Date inactiveto) {
        this.inactiveto = inactiveto;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tvendor.inactivereason
     * @return  the value of tvendor.inactivereason
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public String getInactivereason() {
        return inactivereason;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tvendor.inactivereason
     * @param inactivereason  the value for tvendor.inactivereason
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    public void setInactivereason(String inactivereason) {
        this.inactivereason = inactivereason == null ? null : inactivereason.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tvendor
     * @param that
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Vendor)) {
            return false;
        }
        Vendor other = (Vendor) that;
        return this.getTvendorPk() == null ? other == null : this.getTvendorPk().equals(other.getTvendorPk())
                && this.getVendorcode() == null ? other == null : this.getVendorcode().equals(other.getVendorcode())
                && this.getVendorname() == null ? other == null : this.getVendorname().equals(other.getVendorname())
                && this.getPpn() == null ? other == null : this.getPpn().equals(other.getPpn())
                && this.getPph() == null ? other == null : this.getPph().equals(other.getPph())
                && this.getAddress1() == null ? other == null : this.getAddress1().equals(other.getAddress1())
                && this.getAddress2() == null ? other == null : this.getAddress2().equals(other.getAddress2())
                && this.getTlocationFk() == null ? other == null : this.getTlocationFk().equals(other.getTlocationFk())
                && this.getPostalcode() == null ? other == null : this.getPostalcode().equals(other.getPostalcode())
                && this.getWebsite() == null ? other == null : this.getWebsite().equals(other.getWebsite())
                && this.getEmail() == null ? other == null : this.getEmail().equals(other.getEmail())
                && this.getIsactive() == null ? other == null : this.getIsactive().equals(other.getIsactive())
                && this.getContactname() == null ? other == null : this.getContactname().equals(other.getContactname())
                && this.getContactphone() == null ? other == null : this.getContactphone().equals(other.getContactphone())
                && this.getContactfax() == null ? other == null : this.getContactfax().equals(other.getContactfax())
                && this.getContactemail() == null ? other == null : this.getContactemail().equals(other.getContactemail())
                && this.getTerms() == null ? other == null : this.getTerms().equals(other.getTerms())
                && this.getFlagGst() == null ? other == null : this.getFlagGst().equals(other.getFlagGst())
                && this.getVendornpwp() == null ? other == null : this.getVendornpwp().equals(other.getVendornpwp())
                && this.getGlNo() == null ? other == null : this.getGlNo().equals(other.getGlNo())
                && this.getRemittanceaddress() == null ? other == null : this.getRemittanceaddress().equals(other.getRemittanceaddress())
                && this.getVendorowner() == null ? other == null : this.getVendorowner().equals(other.getVendorowner())
                && this.getUpdatedbyemployeeid() == null ? other == null : this.getUpdatedbyemployeeid().equals(other.getUpdatedbyemployeeid())
                && this.getLastupdated() == null ? other == null : this.getLastupdated().equals(other.getLastupdated())
                && this.getInactivefrom() == null ? other == null : this.getInactivefrom().equals(other.getInactivefrom())
                && this.getInactiveto() == null ? other == null : this.getInactiveto().equals(other.getInactiveto())
                && this.getInactivereason() == null ? other == null : this.getInactivereason().equals(other.getInactivereason());
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tvendor
     * @ibatorgenerated  Mon Aug 02 19:17:49 SGT 2010
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getTvendorPk() != null) {
            hash *= getTvendorPk().hashCode();
        }
        if (getVendorcode() != null) {
            hash *= getVendorcode().hashCode();
        }
        if (getVendorname() != null) {
            hash *= getVendorname().hashCode();
        }
        if (getPpn() != null) {
            hash *= getPpn().hashCode();
        }
        if (getPph() != null) {
            hash *= getPph().hashCode();
        }
        if (getAddress1() != null) {
            hash *= getAddress1().hashCode();
        }
        if (getAddress2() != null) {
            hash *= getAddress2().hashCode();
        }
        if (getTlocationFk() != null) {
            hash *= getTlocationFk().hashCode();
        }
        if (getPostalcode() != null) {
            hash *= getPostalcode().hashCode();
        }
        if (getWebsite() != null) {
            hash *= getWebsite().hashCode();
        }
        if (getEmail() != null) {
            hash *= getEmail().hashCode();
        }
        if (getIsactive() != null) {
            hash *= getIsactive().hashCode();
        }
        if (getContactname() != null) {
            hash *= getContactname().hashCode();
        }
        if (getContactphone() != null) {
            hash *= getContactphone().hashCode();
        }
        if (getContactfax() != null) {
            hash *= getContactfax().hashCode();
        }
        if (getContactemail() != null) {
            hash *= getContactemail().hashCode();
        }
        if (getTerms() != null) {
            hash *= getTerms().hashCode();
        }
        if (getFlagGst() != null) {
            hash *= getFlagGst().hashCode();
        }
        if (getVendornpwp() != null) {
            hash *= getVendornpwp().hashCode();
        }
        if (getGlNo() != null) {
            hash *= getGlNo().hashCode();
        }
        if (getRemittanceaddress() != null) {
            hash *= getRemittanceaddress().hashCode();
        }
        if (getVendorowner() != null) {
            hash *= getVendorowner().hashCode();
        }
        if (getUpdatedbyemployeeid() != null) {
            hash *= getUpdatedbyemployeeid().hashCode();
        }
        if (getLastupdated() != null) {
            hash *= getLastupdated().hashCode();
        }
        if (getInactivefrom() != null) {
            hash *= getInactivefrom().hashCode();
        }
        if (getInactiveto() != null) {
            hash *= getInactiveto().hashCode();
        }
        if (getInactivereason() != null) {
            hash *= getInactivereason().hashCode();
        }
        return hash;
    }

    private int isAfterEvent;

    public int getIsAfterEvent() {
        return isAfterEvent;
    }

    public void setIsAfterEvent(int isAfterEvent) {
        this.isAfterEvent = isAfterEvent;
    }

    @Override
    public String toString() {
        return "Vendor{" + "tvendorPk=" + tvendorPk + ", vendorSAPID=" + vendorSAPID + ", vendorcode=" + vendorcode + ", vendorname=" + vendorname + ", ppn=" + ppn + ", pph=" + pph + ", address1=" + address1 + ", address2=" + address2 + ", tlocationFk=" + tlocationFk + ", postalcode=" + postalcode + ", website=" + website + ", email=" + email + ", isactive=" + isactive + ", contactname=" + contactname + ", contactphone=" + contactphone + ", contactfax=" + contactfax + ", contactemail=" + contactemail + ", terms=" + terms + ", flagGst=" + flagGst + ", vendornpwp=" + vendornpwp + ", glNo=" + glNo + ", remittanceaddress=" + remittanceaddress + ", vendorowner=" + vendorowner + ", updatedbyemployeeid=" + updatedbyemployeeid + ", lastupdated=" + lastupdated + ", inactivefrom=" + inactivefrom + ", inactiveto=" + inactiveto + ", inactivereason=" + inactivereason + ", isAfterEvent=" + isAfterEvent + '}';
    }

}
