package com.ckb.wo.client.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class WorkOrderExample {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    protected String orderByClause;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    protected List<Criteria> oredCriteria;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    protected String limitClause;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public WorkOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    protected WorkOrderExample(WorkOrderExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.limitClause = example.limitClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public void setLimitClause(String limitClause) {
        this.limitClause = limitClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public String getLimitClause() {
        return limitClause;
    }

    /**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tworkorder
     * @ibatorgenerated  Mon Aug 02 20:50:40 SGT 2010
     */
    public static class Criteria {

        protected List<String> criteriaWithoutValue;
        protected List<Map<String, Object>> criteriaWithSingleValue;
        protected List<Map<String, Object>> criteriaWithListValue;
        protected List<Map<String, Object>> criteriaWithBetweenValue;
        protected String andCustomSQL;
        protected String orCustomSQL;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                    || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0
                    || criteriaWithBetweenValue.size() > 0;
        }

        public String getAndCustomSQL() {
            return andCustomSQL;
        }

        public String getOrCustomSQL() {
            return orCustomSQL;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value,
                String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property
                        + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition,
                List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property
                        + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1,
                Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property
                        + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value,
                String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()),
                    property);
        }

        protected void addCriterionForJDBCDate(String condition,
                List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property
                        + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1,
                Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property
                        + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()),
                    new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andTworkorderPkIsNull() {
            addCriterion("atworkorder.tworkorder_pk is null");
            return this;
        }

        public Criteria andTworkorderPkIsNotNull() {
            addCriterion("atworkorder.tworkorder_pk is not null");
            return this;
        }

        public Criteria andTworkorderPkEqualTo(Long value) {
            addCriterion("atworkorder.tworkorder_pk =", value, "tworkorderPk");
            return this;
        }

        public Criteria andTworkorderPkNotEqualTo(Long value) {
            addCriterion("atworkorder.tworkorder_pk <>", value, "tworkorderPk");
            return this;
        }

        public Criteria andTworkorderPkGreaterThan(Long value) {
            addCriterion("atworkorder.tworkorder_pk >", value, "tworkorderPk");
            return this;
        }

        public Criteria andTworkorderPkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tworkorder_pk >=", value, "tworkorderPk");
            return this;
        }

        public Criteria andTworkorderPkLessThan(Long value) {
            addCriterion("atworkorder.tworkorder_pk <", value, "tworkorderPk");
            return this;
        }

        public Criteria andTworkorderPkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tworkorder_pk <=", value, "tworkorderPk");
            return this;
        }

        public Criteria andTworkorderPkIn(List<Long> values) {
            addCriterion("atworkorder.tworkorder_pk in", values, "tworkorderPk");
            return this;
        }

        public Criteria andTworkorderPkNotIn(List<Long> values) {
            addCriterion("atworkorder.tworkorder_pk not in", values,
                    "tworkorderPk");
            return this;
        }

        public Criteria andTworkorderPkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tworkorder_pk between", value1, value2,
                    "tworkorderPk");
            return this;
        }

        public Criteria andTworkorderPkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tworkorder_pk not between", value1,
                    value2, "tworkorderPk");
            return this;
        }

        public Criteria andNomorwoIsNull() {
            addCriterion("atworkorder.nomorwo is null");
            return this;
        }

        public Criteria andNomorwoIsNotNull() {
            addCriterion("atworkorder.nomorwo is not null");
            return this;
        }

        public Criteria andNomorwoEqualTo(String value) {
            addCriterion("atworkorder.nomorwo =", value, "nomorwo");
            return this;
        }

        public Criteria andNomorwoNotEqualTo(String value) {
            addCriterion("atworkorder.nomorwo <>", value, "nomorwo");
            return this;
        }

        public Criteria andNomorwoGreaterThan(String value) {
            addCriterion("atworkorder.nomorwo >", value, "nomorwo");
            return this;
        }

        public Criteria andNomorwoGreaterThanOrEqualTo(String value) {
            addCriterion("atworkorder.nomorwo >=", value, "nomorwo");
            return this;
        }

        public Criteria andNomorwoLessThan(String value) {
            addCriterion("atworkorder.nomorwo <", value, "nomorwo");
            return this;
        }

        public Criteria andNomorwoLessThanOrEqualTo(String value) {
            addCriterion("atworkorder.nomorwo <=", value, "nomorwo");
            return this;
        }

        public Criteria andNomorwoLike(String value) {
            addCriterion("atworkorder.nomorwo like", value, "nomorwo");
            return this;
        }

        public Criteria andNomorwoNotLike(String value) {
            addCriterion("atworkorder.nomorwo not like", value, "nomorwo");
            return this;
        }

        public Criteria andNomorwoIn(List<String> values) {
            addCriterion("atworkorder.nomorwo in", values, "nomorwo");
            return this;
        }

        public Criteria andNomorwoNotIn(List<String> values) {
            addCriterion("atworkorder.nomorwo not in", values, "nomorwo");
            return this;
        }

        public Criteria andNomorwoBetween(String value1, String value2) {
            addCriterion("atworkorder.nomorwo between", value1, value2,
                    "nomorwo");
            return this;
        }

        public Criteria andNomorwoNotBetween(String value1, String value2) {
            addCriterion("atworkorder.nomorwo not between", value1, value2,
                    "nomorwo");
            return this;
        }

        public Criteria andTvendorserviceFkIsNull() {
            addCriterion("atworkorder.tvendorservice_fk is null");
            return this;
        }

        public Criteria andTvendorserviceFkIsNotNull() {
            addCriterion("atworkorder.tvendorservice_fk is not null");
            return this;
        }

        public Criteria andTvendorserviceFkEqualTo(Long value) {
            addCriterion("atworkorder.tvendorservice_fk =", value,
                    "tvendorserviceFk");
            return this;
        }

        public Criteria andTvendorserviceFkNotEqualTo(Long value) {
            addCriterion("atworkorder.tvendorservice_fk <>", value,
                    "tvendorserviceFk");
            return this;
        }

        public Criteria andTvendorserviceFkGreaterThan(Long value) {
            addCriterion("atworkorder.tvendorservice_fk >", value,
                    "tvendorserviceFk");
            return this;
        }

        public Criteria andTvendorserviceFkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tvendorservice_fk >=", value,
                    "tvendorserviceFk");
            return this;
        }

        public Criteria andTvendorserviceFkLessThan(Long value) {
            addCriterion("atworkorder.tvendorservice_fk <", value,
                    "tvendorserviceFk");
            return this;
        }

        public Criteria andTvendorserviceFkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tvendorservice_fk <=", value,
                    "tvendorserviceFk");
            return this;
        }

        public Criteria andTvendorserviceFkIn(List<Long> values) {
            addCriterion("atworkorder.tvendorservice_fk in", values,
                    "tvendorserviceFk");
            return this;
        }

        public Criteria andTvendorserviceFkNotIn(List<Long> values) {
            addCriterion("atworkorder.tvendorservice_fk not in", values,
                    "tvendorserviceFk");
            return this;
        }

        public Criteria andTvendorserviceFkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tvendorservice_fk between", value1,
                    value2, "tvendorserviceFk");
            return this;
        }

        public Criteria andTvendorserviceFkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tvendorservice_fk not between", value1,
                    value2, "tvendorserviceFk");
            return this;
        }

        public Criteria andAdhocIsNull() {
            addCriterion("atworkorder.adhoc is null");
            return this;
        }

        public Criteria andAdhocIsNotNull() {
            addCriterion("atworkorder.adhoc is not null");
            return this;
        }

        public Criteria andAdhocEqualTo(Boolean value) {
            addCriterion("atworkorder.adhoc =", value, "adhoc");
            return this;
        }

        public Criteria andAdhocNotEqualTo(Boolean value) {
            addCriterion("atworkorder.adhoc <>", value, "adhoc");
            return this;
        }

        public Criteria andAdhocGreaterThan(Boolean value) {
            addCriterion("atworkorder.adhoc >", value, "adhoc");
            return this;
        }

        public Criteria andAdhocGreaterThanOrEqualTo(Boolean value) {
            addCriterion("atworkorder.adhoc >=", value, "adhoc");
            return this;
        }

        public Criteria andAdhocLessThan(Boolean value) {
            addCriterion("atworkorder.adhoc <", value, "adhoc");
            return this;
        }

        public Criteria andAdhocLessThanOrEqualTo(Boolean value) {
            addCriterion("atworkorder.adhoc <=", value, "adhoc");
            return this;
        }

        public Criteria andAdhocIn(List<Boolean> values) {
            addCriterion("atworkorder.adhoc in", values, "adhoc");
            return this;
        }

        public Criteria andAdhocNotIn(List<Boolean> values) {
            addCriterion("atworkorder.adhoc not in", values, "adhoc");
            return this;
        }

        public Criteria andAdhocBetween(Boolean value1, Boolean value2) {
            addCriterion("atworkorder.adhoc between", value1, value2, "adhoc");
            return this;
        }

        public Criteria andAdhocNotBetween(Boolean value1, Boolean value2) {
            addCriterion("atworkorder.adhoc not between", value1, value2,
                    "adhoc");
            return this;
        }

        public Criteria andOrigintlocationFkIsNull() {
            addCriterion("atworkorder.origintlocation_fk is null");
            return this;
        }

        public Criteria andOrigintlocationFkIsNotNull() {
            addCriterion("atworkorder.origintlocation_fk is not null");
            return this;
        }

        public Criteria andOrigintlocationFkEqualTo(Long value) {
            addCriterion("atworkorder.origintlocation_fk =", value,
                    "origintlocationFk");
            return this;
        }

        public Criteria andOrigintlocationFkNotEqualTo(Long value) {
            addCriterion("atworkorder.origintlocation_fk <>", value,
                    "origintlocationFk");
            return this;
        }

        public Criteria andOrigintlocationFkGreaterThan(Long value) {
            addCriterion("atworkorder.origintlocation_fk >", value,
                    "origintlocationFk");
            return this;
        }

        public Criteria andOrigintlocationFkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.origintlocation_fk >=", value,
                    "origintlocationFk");
            return this;
        }

        public Criteria andOrigintlocationFkLessThan(Long value) {
            addCriterion("atworkorder.origintlocation_fk <", value,
                    "origintlocationFk");
            return this;
        }

        public Criteria andOrigintlocationFkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.origintlocation_fk <=", value,
                    "origintlocationFk");
            return this;
        }

        public Criteria andOrigintlocationFkIn(List<Long> values) {
            addCriterion("atworkorder.origintlocation_fk in", values,
                    "origintlocationFk");
            return this;
        }

        public Criteria andOrigintlocationFkNotIn(List<Long> values) {
            addCriterion("atworkorder.origintlocation_fk not in", values,
                    "origintlocationFk");
            return this;
        }

        public Criteria andOrigintlocationFkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.origintlocation_fk between", value1,
                    value2, "origintlocationFk");
            return this;
        }

        public Criteria andOrigintlocationFkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.origintlocation_fk not between", value1,
                    value2, "origintlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkIsNull() {
            addCriterion("atworkorder.destinationtlocation_fk is null");
            return this;
        }

        public Criteria andDestinationtlocationFkIsNotNull() {
            addCriterion("atworkorder.destinationtlocation_fk is not null");
            return this;
        }

        public Criteria andDestinationtlocationFkEqualTo(Long value) {
            addCriterion("atworkorder.destinationtlocation_fk =", value,
                    "destinationtlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkNotEqualTo(Long value) {
            addCriterion("atworkorder.destinationtlocation_fk <>", value,
                    "destinationtlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkGreaterThan(Long value) {
            addCriterion("atworkorder.destinationtlocation_fk >", value,
                    "destinationtlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.destinationtlocation_fk >=", value,
                    "destinationtlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkLessThan(Long value) {
            addCriterion("atworkorder.destinationtlocation_fk <", value,
                    "destinationtlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.destinationtlocation_fk <=", value,
                    "destinationtlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkIn(List<Long> values) {
            addCriterion("atworkorder.destinationtlocation_fk in", values,
                    "destinationtlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkNotIn(List<Long> values) {
            addCriterion("atworkorder.destinationtlocation_fk not in", values,
                    "destinationtlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkBetween(Long value1,
                Long value2) {
            addCriterion("atworkorder.destinationtlocation_fk between", value1,
                    value2, "destinationtlocationFk");
            return this;
        }

        public Criteria andDestinationtlocationFkNotBetween(Long value1,
                Long value2) {
            addCriterion("atworkorder.destinationtlocation_fk not between",
                    value1, value2, "destinationtlocationFk");
            return this;
        }

        public Criteria andTservicemodeFkIsNull() {
            addCriterion("atworkorder.tservicemode_fk is null");
            return this;
        }

        public Criteria andTservicemodeFkIsNotNull() {
            addCriterion("atworkorder.tservicemode_fk is not null");
            return this;
        }

        public Criteria andTservicemodeFkEqualTo(Long value) {
            addCriterion("atworkorder.tservicemode_fk =", value,
                    "tservicemodeFk");
            return this;
        }

        public Criteria andTservicemodeFkNotEqualTo(Long value) {
            addCriterion("atworkorder.tservicemode_fk <>", value,
                    "tservicemodeFk");
            return this;
        }

        public Criteria andTservicemodeFkGreaterThan(Long value) {
            addCriterion("atworkorder.tservicemode_fk >", value,
                    "tservicemodeFk");
            return this;
        }

        public Criteria andTservicemodeFkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tservicemode_fk >=", value,
                    "tservicemodeFk");
            return this;
        }

        public Criteria andTservicemodeFkLessThan(Long value) {
            addCriterion("atworkorder.tservicemode_fk <", value,
                    "tservicemodeFk");
            return this;
        }

        public Criteria andTservicemodeFkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tservicemode_fk <=", value,
                    "tservicemodeFk");
            return this;
        }

        public Criteria andTservicemodeFkIn(List<Long> values) {
            addCriterion("atworkorder.tservicemode_fk in", values,
                    "tservicemodeFk");
            return this;
        }

        public Criteria andTservicemodeFkNotIn(List<Long> values) {
            addCriterion("atworkorder.tservicemode_fk not in", values,
                    "tservicemodeFk");
            return this;
        }

        public Criteria andTservicemodeFkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tservicemode_fk between", value1, value2,
                    "tservicemodeFk");
            return this;
        }

        public Criteria andTservicemodeFkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tservicemode_fk not between", value1,
                    value2, "tservicemodeFk");
            return this;
        }

        public Criteria andTorderFkIsNull() {
            addCriterion("atworkorder.torder_fk is null");
            return this;
        }

        public Criteria andTorderFkIsNotNull() {
            addCriterion("atworkorder.torder_fk is not null");
            return this;
        }

        public Criteria andTorderFkEqualTo(Long value) {
            addCriterion("atworkorder.torder_fk =", value, "torderFk");
            return this;
        }

        public Criteria andTorderFkNotEqualTo(Long value) {
            addCriterion("atworkorder.torder_fk <>", value, "torderFk");
            return this;
        }

        public Criteria andTorderFkGreaterThan(Long value) {
            addCriterion("atworkorder.torder_fk >", value, "torderFk");
            return this;
        }

        public Criteria andTorderFkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.torder_fk >=", value, "torderFk");
            return this;
        }

        public Criteria andTorderFkLessThan(Long value) {
            addCriterion("atworkorder.torder_fk <", value, "torderFk");
            return this;
        }

        public Criteria andTorderFkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.torder_fk <=", value, "torderFk");
            return this;
        }

        public Criteria andTorderFkIn(List<Long> values) {
            addCriterion("atworkorder.torder_fk in", values, "torderFk");
            return this;
        }

        public Criteria andTorderFkNotIn(List<Long> values) {
            addCriterion("atworkorder.torder_fk not in", values, "torderFk");
            return this;
        }

        public Criteria andTorderFkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.torder_fk between", value1, value2,
                    "torderFk");
            return this;
        }

        public Criteria andTorderFkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.torder_fk not between", value1, value2,
                    "torderFk");
            return this;
        }

        public Criteria andTservicetypeFkIsNull() {
            addCriterion("atworkorder.tservicetype_fk is null");
            return this;
        }

        public Criteria andTservicetypeFkIsNotNull() {
            addCriterion("atworkorder.tservicetype_fk is not null");
            return this;
        }

        public Criteria andTservicetypeFkEqualTo(Long value) {
            addCriterion("atworkorder.tservicetype_fk =", value,
                    "tservicetypeFk");
            return this;
        }

        public Criteria andTservicetypeFkNotEqualTo(Long value) {
            addCriterion("atworkorder.tservicetype_fk <>", value,
                    "tservicetypeFk");
            return this;
        }

        public Criteria andTservicetypeFkGreaterThan(Long value) {
            addCriterion("atworkorder.tservicetype_fk >", value,
                    "tservicetypeFk");
            return this;
        }

        public Criteria andTservicetypeFkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tservicetype_fk >=", value,
                    "tservicetypeFk");
            return this;
        }

        public Criteria andTservicetypeFkLessThan(Long value) {
            addCriterion("atworkorder.tservicetype_fk <", value,
                    "tservicetypeFk");
            return this;
        }

        public Criteria andTservicetypeFkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tservicetype_fk <=", value,
                    "tservicetypeFk");
            return this;
        }

        public Criteria andTservicetypeFkIn(List<Long> values) {
            addCriterion("atworkorder.tservicetype_fk in", values,
                    "tservicetypeFk");
            return this;
        }

        public Criteria andTservicetypeFkNotIn(List<Long> values) {
            addCriterion("atworkorder.tservicetype_fk not in", values,
                    "tservicetypeFk");
            return this;
        }

        public Criteria andTservicetypeFkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tservicetype_fk between", value1, value2,
                    "tservicetypeFk");
            return this;
        }

        public Criteria andTservicetypeFkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tservicetype_fk not between", value1,
                    value2, "tservicetypeFk");
            return this;
        }

        public Criteria andTvendorFkIsNull() {
            addCriterion("atworkorder.tvendor_fk is null");
            return this;
        }

        public Criteria andTvendorFkIsNotNull() {
            addCriterion("atworkorder.tvendor_fk is not null");
            return this;
        }

        public Criteria andTvendorFkEqualTo(Long value) {
            addCriterion("atworkorder.tvendor_fk =", value, "tvendorFk");
            return this;
        }

        public Criteria andTvendorFkNotEqualTo(Long value) {
            addCriterion("atworkorder.tvendor_fk <>", value, "tvendorFk");
            return this;
        }

        public Criteria andTvendorFkGreaterThan(Long value) {
            addCriterion("atworkorder.tvendor_fk >", value, "tvendorFk");
            return this;
        }

        public Criteria andTvendorFkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tvendor_fk >=", value, "tvendorFk");
            return this;
        }

        public Criteria andTvendorFkLessThan(Long value) {
            addCriterion("atworkorder.tvendor_fk <", value, "tvendorFk");
            return this;
        }

        public Criteria andTvendorFkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tvendor_fk <=", value, "tvendorFk");
            return this;
        }

        public Criteria andTvendorFkIn(List<Long> values) {
            addCriterion("atworkorder.tvendor_fk in", values, "tvendorFk");
            return this;
        }

        public Criteria andTvendorFkNotIn(List<Long> values) {
            addCriterion("atworkorder.tvendor_fk not in", values, "tvendorFk");
            return this;
        }

        public Criteria andTvendorFkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tvendor_fk between", value1, value2,
                    "tvendorFk");
            return this;
        }

        public Criteria andTvendorFkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tvendor_fk not between", value1, value2,
                    "tvendorFk");
            return this;
        }

        public Criteria andMaxlevelIsNull() {
            addCriterion("atworkorder.maxlevel is null");
            return this;
        }

        public Criteria andMaxlevelIsNotNull() {
            addCriterion("atworkorder.maxlevel is not null");
            return this;
        }

        public Criteria andMaxlevelEqualTo(Integer value) {
            addCriterion("atworkorder.maxlevel =", value, "maxlevel");
            return this;
        }

        public Criteria andMaxlevelNotEqualTo(Integer value) {
            addCriterion("atworkorder.maxlevel <>", value, "maxlevel");
            return this;
        }

        public Criteria andMaxlevelGreaterThan(Integer value) {
            addCriterion("atworkorder.maxlevel >", value, "maxlevel");
            return this;
        }

        public Criteria andMaxlevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.maxlevel >=", value, "maxlevel");
            return this;
        }

        public Criteria andMaxlevelLessThan(Integer value) {
            addCriterion("atworkorder.maxlevel <", value, "maxlevel");
            return this;
        }

        public Criteria andMaxlevelLessThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.maxlevel <=", value, "maxlevel");
            return this;
        }

        public Criteria andMaxlevelIn(List<Integer> values) {
            addCriterion("atworkorder.maxlevel in", values, "maxlevel");
            return this;
        }

        public Criteria andMaxlevelNotIn(List<Integer> values) {
            addCriterion("atworkorder.maxlevel not in", values, "maxlevel");
            return this;
        }

        public Criteria andMaxlevelBetween(Integer value1, Integer value2) {
            addCriterion("atworkorder.maxlevel between", value1, value2,
                    "maxlevel");
            return this;
        }

        public Criteria andMaxlevelNotBetween(Integer value1, Integer value2) {
            addCriterion("atworkorder.maxlevel not between", value1, value2,
                    "maxlevel");
            return this;
        }

        public Criteria andTotalweightIsNull() {
            addCriterion("atworkorder.totalweight is null");
            return this;
        }

        public Criteria andTotalweightIsNotNull() {
            addCriterion("atworkorder.totalweight is not null");
            return this;
        }

        public Criteria andTotalweightEqualTo(BigDecimal value) {
            addCriterion("atworkorder.totalweight =", value, "totalweight");
            return this;
        }

        public Criteria andTotalweightNotEqualTo(BigDecimal value) {
            addCriterion("atworkorder.totalweight <>", value, "totalweight");
            return this;
        }

        public Criteria andTotalweightGreaterThan(BigDecimal value) {
            addCriterion("atworkorder.totalweight >", value, "totalweight");
            return this;
        }

        public Criteria andTotalweightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.totalweight >=", value, "totalweight");
            return this;
        }

        public Criteria andTotalweightLessThan(BigDecimal value) {
            addCriterion("atworkorder.totalweight <", value, "totalweight");
            return this;
        }

        public Criteria andTotalweightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.totalweight <=", value, "totalweight");
            return this;
        }

        public Criteria andTotalweightIn(List<BigDecimal> values) {
            addCriterion("atworkorder.totalweight in", values, "totalweight");
            return this;
        }

        public Criteria andTotalweightNotIn(List<BigDecimal> values) {
            addCriterion("atworkorder.totalweight not in", values,
                    "totalweight");
            return this;
        }

        public Criteria andTotalweightBetween(BigDecimal value1,
                BigDecimal value2) {
            addCriterion("atworkorder.totalweight between", value1, value2,
                    "totalweight");
            return this;
        }

        public Criteria andTotalweightNotBetween(BigDecimal value1,
                BigDecimal value2) {
            addCriterion("atworkorder.totalweight not between", value1, value2,
                    "totalweight");
            return this;
        }

        public Criteria andTotalvolumeIsNull() {
            addCriterion("atworkorder.totalvolume is null");
            return this;
        }

        public Criteria andTotalvolumeIsNotNull() {
            addCriterion("atworkorder.totalvolume is not null");
            return this;
        }

        public Criteria andTotalvolumeEqualTo(BigDecimal value) {
            addCriterion("atworkorder.totalvolume =", value, "totalvolume");
            return this;
        }

        public Criteria andTotalvolumeNotEqualTo(BigDecimal value) {
            addCriterion("atworkorder.totalvolume <>", value, "totalvolume");
            return this;
        }

        public Criteria andTotalvolumeGreaterThan(BigDecimal value) {
            addCriterion("atworkorder.totalvolume >", value, "totalvolume");
            return this;
        }

        public Criteria andTotalvolumeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.totalvolume >=", value, "totalvolume");
            return this;
        }

        public Criteria andTotalvolumeLessThan(BigDecimal value) {
            addCriterion("atworkorder.totalvolume <", value, "totalvolume");
            return this;
        }

        public Criteria andTotalvolumeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.totalvolume <=", value, "totalvolume");
            return this;
        }

        public Criteria andTotalvolumeIn(List<BigDecimal> values) {
            addCriterion("atworkorder.totalvolume in", values, "totalvolume");
            return this;
        }

        public Criteria andTotalvolumeNotIn(List<BigDecimal> values) {
            addCriterion("atworkorder.totalvolume not in", values,
                    "totalvolume");
            return this;
        }

        public Criteria andTotalvolumeBetween(BigDecimal value1,
                BigDecimal value2) {
            addCriterion("atworkorder.totalvolume between", value1, value2,
                    "totalvolume");
            return this;
        }

        public Criteria andTotalvolumeNotBetween(BigDecimal value1,
                BigDecimal value2) {
            addCriterion("atworkorder.totalvolume not between", value1, value2,
                    "totalvolume");
            return this;
        }

        public Criteria andTdeliverytermFkIsNull() {
            addCriterion("atworkorder.tdeliveryterm_fk is null");
            return this;
        }

        public Criteria andTdeliverytermFkIsNotNull() {
            addCriterion("atworkorder.tdeliveryterm_fk is not null");
            return this;
        }

        public Criteria andTdeliverytermFkEqualTo(Long value) {
            addCriterion("atworkorder.tdeliveryterm_fk =", value,
                    "tdeliverytermFk");
            return this;
        }

        public Criteria andTdeliverytermFkNotEqualTo(Long value) {
            addCriterion("atworkorder.tdeliveryterm_fk <>", value,
                    "tdeliverytermFk");
            return this;
        }

        public Criteria andTdeliverytermFkGreaterThan(Long value) {
            addCriterion("atworkorder.tdeliveryterm_fk >", value,
                    "tdeliverytermFk");
            return this;
        }

        public Criteria andTdeliverytermFkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tdeliveryterm_fk >=", value,
                    "tdeliverytermFk");
            return this;
        }

        public Criteria andTdeliverytermFkLessThan(Long value) {
            addCriterion("atworkorder.tdeliveryterm_fk <", value,
                    "tdeliverytermFk");
            return this;
        }

        public Criteria andTdeliverytermFkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tdeliveryterm_fk <=", value,
                    "tdeliverytermFk");
            return this;
        }

        public Criteria andTdeliverytermFkIn(List<Long> values) {
            addCriterion("atworkorder.tdeliveryterm_fk in", values,
                    "tdeliverytermFk");
            return this;
        }

        public Criteria andTdeliverytermFkNotIn(List<Long> values) {
            addCriterion("atworkorder.tdeliveryterm_fk not in", values,
                    "tdeliverytermFk");
            return this;
        }

        public Criteria andTdeliverytermFkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tdeliveryterm_fk between", value1,
                    value2, "tdeliverytermFk");
            return this;
        }

        public Criteria andTdeliverytermFkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tdeliveryterm_fk not between", value1,
                    value2, "tdeliverytermFk");
            return this;
        }

        public Criteria andChargeIsNull() {
            addCriterion("atworkorder.charge is null");
            return this;
        }

        public Criteria andChargeIsNotNull() {
            addCriterion("atworkorder.charge is not null");
            return this;
        }

        public Criteria andChargeEqualTo(BigDecimal value) {
            addCriterion("atworkorder.charge =", value, "charge");
            return this;
        }

        public Criteria andChargeNotEqualTo(BigDecimal value) {
            addCriterion("atworkorder.charge <>", value, "charge");
            return this;
        }

        public Criteria andChargeGreaterThan(BigDecimal value) {
            addCriterion("atworkorder.charge >", value, "charge");
            return this;
        }

        public Criteria andChargeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.charge >=", value, "charge");
            return this;
        }

        public Criteria andChargeLessThan(BigDecimal value) {
            addCriterion("atworkorder.charge <", value, "charge");
            return this;
        }

        public Criteria andChargeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.charge <=", value, "charge");
            return this;
        }

        public Criteria andChargeIn(List<BigDecimal> values) {
            addCriterion("atworkorder.charge in", values, "charge");
            return this;
        }

        public Criteria andChargeNotIn(List<BigDecimal> values) {
            addCriterion("atworkorder.charge not in", values, "charge");
            return this;
        }

        public Criteria andChargeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("atworkorder.charge between", value1, value2, "charge");
            return this;
        }

        public Criteria andChargeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("atworkorder.charge not between", value1, value2,
                    "charge");
            return this;
        }

        public Criteria andTcurrencyFkIsNull() {
            addCriterion("atworkorder.tcurrency_fk is null");
            return this;
        }

        public Criteria andTcurrencyFkIsNotNull() {
            addCriterion("atworkorder.tcurrency_fk is not null");
            return this;
        }

        public Criteria andTcurrencyFkEqualTo(Long value) {
            addCriterion("atworkorder.tcurrency_fk =", value, "tcurrencyFk");
            return this;
        }

        public Criteria andTcurrencyFkNotEqualTo(Long value) {
            addCriterion("atworkorder.tcurrency_fk <>", value, "tcurrencyFk");
            return this;
        }

        public Criteria andTcurrencyFkGreaterThan(Long value) {
            addCriterion("atworkorder.tcurrency_fk >", value, "tcurrencyFk");
            return this;
        }

        public Criteria andTcurrencyFkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tcurrency_fk >=", value, "tcurrencyFk");
            return this;
        }

        public Criteria andTcurrencyFkLessThan(Long value) {
            addCriterion("atworkorder.tcurrency_fk <", value, "tcurrencyFk");
            return this;
        }

        public Criteria andTcurrencyFkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.tcurrency_fk <=", value, "tcurrencyFk");
            return this;
        }

        public Criteria andTcurrencyFkIn(List<Long> values) {
            addCriterion("atworkorder.tcurrency_fk in", values, "tcurrencyFk");
            return this;
        }

        public Criteria andTcurrencyFkNotIn(List<Long> values) {
            addCriterion("atworkorder.tcurrency_fk not in", values,
                    "tcurrencyFk");
            return this;
        }

        public Criteria andTcurrencyFkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tcurrency_fk between", value1, value2,
                    "tcurrencyFk");
            return this;
        }

        public Criteria andTcurrencyFkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.tcurrency_fk not between", value1,
                    value2, "tcurrencyFk");
            return this;
        }

        public Criteria andAgreementdateIsNull() {
            addCriterion("atworkorder.agreementdate is null");
            return this;
        }

        public Criteria andAgreementdateIsNotNull() {
            addCriterion("atworkorder.agreementdate is not null");
            return this;
        }

        public Criteria andAgreementdateEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.agreementdate =", value,
                    "agreementdate");
            return this;
        }

        public Criteria andAgreementdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.agreementdate <>", value,
                    "agreementdate");
            return this;
        }

        public Criteria andAgreementdateGreaterThan(Date value) {
            addCriterionForJDBCDate("atworkorder.agreementdate >", value,
                    "agreementdate");
            return this;
        }

        public Criteria andAgreementdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.agreementdate >=", value,
                    "agreementdate");
            return this;
        }

        public Criteria andAgreementdateLessThan(Date value) {
            addCriterionForJDBCDate("atworkorder.agreementdate <", value,
                    "agreementdate");
            return this;
        }

        public Criteria andAgreementdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.agreementdate <=", value,
                    "agreementdate");
            return this;
        }

        public Criteria andAgreementdateIn(List<Date> values) {
            addCriterionForJDBCDate("atworkorder.agreementdate in", values,
                    "agreementdate");
            return this;
        }

        public Criteria andAgreementdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("atworkorder.agreementdate not in", values,
                    "agreementdate");
            return this;
        }

        public Criteria andAgreementdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("atworkorder.agreementdate between",
                    value1, value2, "agreementdate");
            return this;
        }

        public Criteria andAgreementdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("atworkorder.agreementdate not between",
                    value1, value2, "agreementdate");
            return this;
        }

        public Criteria andAgreementnoIsNull() {
            addCriterion("atworkorder.agreementno is null");
            return this;
        }

        public Criteria andAgreementnoIsNotNull() {
            addCriterion("atworkorder.agreementno is not null");
            return this;
        }

        public Criteria andAgreementnoEqualTo(String value) {
            addCriterion("atworkorder.agreementno =", value, "agreementno");
            return this;
        }

        public Criteria andAgreementnoNotEqualTo(String value) {
            addCriterion("atworkorder.agreementno <>", value, "agreementno");
            return this;
        }

        public Criteria andAgreementnoGreaterThan(String value) {
            addCriterion("atworkorder.agreementno >", value, "agreementno");
            return this;
        }

        public Criteria andAgreementnoGreaterThanOrEqualTo(String value) {
            addCriterion("atworkorder.agreementno >=", value, "agreementno");
            return this;
        }

        public Criteria andAgreementnoLessThan(String value) {
            addCriterion("atworkorder.agreementno <", value, "agreementno");
            return this;
        }

        public Criteria andAgreementnoLessThanOrEqualTo(String value) {
            addCriterion("atworkorder.agreementno <=", value, "agreementno");
            return this;
        }

        public Criteria andAgreementnoLike(String value) {
            addCriterion("atworkorder.agreementno like", value, "agreementno");
            return this;
        }

        public Criteria andAgreementnoNotLike(String value) {
            addCriterion("atworkorder.agreementno not like", value,
                    "agreementno");
            return this;
        }

        public Criteria andAgreementnoIn(List<String> values) {
            addCriterion("atworkorder.agreementno in", values, "agreementno");
            return this;
        }

        public Criteria andAgreementnoNotIn(List<String> values) {
            addCriterion("atworkorder.agreementno not in", values,
                    "agreementno");
            return this;
        }

        public Criteria andAgreementnoBetween(String value1, String value2) {
            addCriterion("atworkorder.agreementno between", value1, value2,
                    "agreementno");
            return this;
        }

        public Criteria andAgreementnoNotBetween(String value1, String value2) {
            addCriterion("atworkorder.agreementno not between", value1, value2,
                    "agreementno");
            return this;
        }

        public Criteria andPphIsNull() {
            addCriterion("atworkorder.pph is null");
            return this;
        }

        public Criteria andPphIsNotNull() {
            addCriterion("atworkorder.pph is not null");
            return this;
        }

        public Criteria andPphEqualTo(BigDecimal value) {
            addCriterion("atworkorder.pph =", value, "pph");
            return this;
        }

        public Criteria andPphNotEqualTo(BigDecimal value) {
            addCriterion("atworkorder.pph <>", value, "pph");
            return this;
        }

        public Criteria andPphGreaterThan(BigDecimal value) {
            addCriterion("atworkorder.pph >", value, "pph");
            return this;
        }

        public Criteria andPphGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.pph >=", value, "pph");
            return this;
        }

        public Criteria andPphLessThan(BigDecimal value) {
            addCriterion("atworkorder.pph <", value, "pph");
            return this;
        }

        public Criteria andPphLessThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.pph <=", value, "pph");
            return this;
        }

        public Criteria andPphIn(List<BigDecimal> values) {
            addCriterion("atworkorder.pph in", values, "pph");
            return this;
        }

        public Criteria andPphNotIn(List<BigDecimal> values) {
            addCriterion("atworkorder.pph not in", values, "pph");
            return this;
        }

        public Criteria andPphBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("atworkorder.pph between", value1, value2, "pph");
            return this;
        }

        public Criteria andPphNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("atworkorder.pph not between", value1, value2, "pph");
            return this;
        }

        public Criteria andPpnIsNull() {
            addCriterion("atworkorder.ppn is null");
            return this;
        }

        public Criteria andPpnIsNotNull() {
            addCriterion("atworkorder.ppn is not null");
            return this;
        }

        public Criteria andPpnEqualTo(BigDecimal value) {
            addCriterion("atworkorder.ppn =", value, "ppn");
            return this;
        }

        public Criteria andPpnNotEqualTo(BigDecimal value) {
            addCriterion("atworkorder.ppn <>", value, "ppn");
            return this;
        }

        public Criteria andPpnGreaterThan(BigDecimal value) {
            addCriterion("atworkorder.ppn >", value, "ppn");
            return this;
        }

        public Criteria andPpnGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.ppn >=", value, "ppn");
            return this;
        }

        public Criteria andPpnLessThan(BigDecimal value) {
            addCriterion("atworkorder.ppn <", value, "ppn");
            return this;
        }

        public Criteria andPpnLessThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.ppn <=", value, "ppn");
            return this;
        }

        public Criteria andPpnIn(List<BigDecimal> values) {
            addCriterion("atworkorder.ppn in", values, "ppn");
            return this;
        }

        public Criteria andPpnNotIn(List<BigDecimal> values) {
            addCriterion("atworkorder.ppn not in", values, "ppn");
            return this;
        }

        public Criteria andPpnBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("atworkorder.ppn between", value1, value2, "ppn");
            return this;
        }

        public Criteria andPpnNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("atworkorder.ppn not between", value1, value2, "ppn");
            return this;
        }

        public Criteria andExecutiondateIsNull() {
            addCriterion("atworkorder.executiondate is null");
            return this;
        }

        public Criteria andExecutiondateIsNotNull() {
            addCriterion("atworkorder.executiondate is not null");
            return this;
        }

        public Criteria andExecutiondateEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.executiondate =", value,
                    "executiondate");
            return this;
        }

        public Criteria andExecutiondateNotEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.executiondate <>", value,
                    "executiondate");
            return this;
        }

        public Criteria andExecutiondateGreaterThan(Date value) {
            addCriterionForJDBCDate("atworkorder.executiondate >", value,
                    "executiondate");
            return this;
        }

        public Criteria andExecutiondateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.executiondate >=", value,
                    "executiondate");
            return this;
        }

        public Criteria andExecutiondateLessThan(Date value) {
            addCriterionForJDBCDate("atworkorder.executiondate <", value,
                    "executiondate");
            return this;
        }

        public Criteria andExecutiondateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.executiondate <=", value,
                    "executiondate");
            return this;
        }

        public Criteria andExecutiondateIn(List<Date> values) {
            addCriterionForJDBCDate("atworkorder.executiondate in", values,
                    "executiondate");
            return this;
        }

        public Criteria andExecutiondateNotIn(List<Date> values) {
            addCriterionForJDBCDate("atworkorder.executiondate not in", values,
                    "executiondate");
            return this;
        }

        public Criteria andExecutiondateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("atworkorder.executiondate between",
                    value1, value2, "executiondate");
            return this;
        }

        public Criteria andExecutiondateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("atworkorder.executiondate not between",
                    value1, value2, "executiondate");
            return this;
        }

        public Criteria andEditcounterIsNull() {
            addCriterion("atworkorder.editcounter is null");
            return this;
        }

        public Criteria andEditcounterIsNotNull() {
            addCriterion("atworkorder.editcounter is not null");
            return this;
        }

        public Criteria andEditcounterEqualTo(Integer value) {
            addCriterion("atworkorder.editcounter =", value, "editcounter");
            return this;
        }

        public Criteria andEditcounterNotEqualTo(Integer value) {
            addCriterion("atworkorder.editcounter <>", value, "editcounter");
            return this;
        }

        public Criteria andEditcounterGreaterThan(Integer value) {
            addCriterion("atworkorder.editcounter >", value, "editcounter");
            return this;
        }

        public Criteria andEditcounterGreaterThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.editcounter >=", value, "editcounter");
            return this;
        }

        public Criteria andEditcounterLessThan(Integer value) {
            addCriterion("atworkorder.editcounter <", value, "editcounter");
            return this;
        }

        public Criteria andEditcounterLessThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.editcounter <=", value, "editcounter");
            return this;
        }

        public Criteria andEditcounterIn(List<Integer> values) {
            addCriterion("atworkorder.editcounter in", values, "editcounter");
            return this;
        }

        public Criteria andEditcounterNotIn(List<Integer> values) {
            addCriterion("atworkorder.editcounter not in", values,
                    "editcounter");
            return this;
        }

        public Criteria andEditcounterBetween(Integer value1, Integer value2) {
            addCriterion("atworkorder.editcounter between", value1, value2,
                    "editcounter");
            return this;
        }

        public Criteria andEditcounterNotBetween(Integer value1, Integer value2) {
            addCriterion("atworkorder.editcounter not between", value1, value2,
                    "editcounter");
            return this;
        }

        public Criteria andRevisioncounterIsNull() {
            addCriterion("atworkorder.revisioncounter is null");
            return this;
        }

        public Criteria andRevisioncounterIsNotNull() {
            addCriterion("atworkorder.revisioncounter is not null");
            return this;
        }

        public Criteria andRevisioncounterEqualTo(Integer value) {
            addCriterion("atworkorder.revisioncounter =", value,
                    "revisioncounter");
            return this;
        }

        public Criteria andRevisioncounterNotEqualTo(Integer value) {
            addCriterion("atworkorder.revisioncounter <>", value,
                    "revisioncounter");
            return this;
        }

        public Criteria andRevisioncounterGreaterThan(Integer value) {
            addCriterion("atworkorder.revisioncounter >", value,
                    "revisioncounter");
            return this;
        }

        public Criteria andRevisioncounterGreaterThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.revisioncounter >=", value,
                    "revisioncounter");
            return this;
        }

        public Criteria andRevisioncounterLessThan(Integer value) {
            addCriterion("atworkorder.revisioncounter <", value,
                    "revisioncounter");
            return this;
        }

        public Criteria andRevisioncounterLessThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.revisioncounter <=", value,
                    "revisioncounter");
            return this;
        }

        public Criteria andRevisioncounterIn(List<Integer> values) {
            addCriterion("atworkorder.revisioncounter in", values,
                    "revisioncounter");
            return this;
        }

        public Criteria andRevisioncounterNotIn(List<Integer> values) {
            addCriterion("atworkorder.revisioncounter not in", values,
                    "revisioncounter");
            return this;
        }

        public Criteria andRevisioncounterBetween(Integer value1, Integer value2) {
            addCriterion("atworkorder.revisioncounter between", value1, value2,
                    "revisioncounter");
            return this;
        }

        public Criteria andRevisioncounterNotBetween(Integer value1,
                Integer value2) {
            addCriterion("atworkorder.revisioncounter not between", value1,
                    value2, "revisioncounter");
            return this;
        }

        public Criteria andLasttlevelIsNull() {
            addCriterion("atworkorder.lasttlevel is null");
            return this;
        }

        public Criteria andLasttlevelIsNotNull() {
            addCriterion("atworkorder.lasttlevel is not null");
            return this;
        }

        public Criteria andLasttlevelEqualTo(Integer value) {
            addCriterion("atworkorder.lasttlevel =", value, "lasttlevel");
            return this;
        }

        public Criteria andLasttlevelNotEqualTo(Integer value) {
            addCriterion("atworkorder.lasttlevel <>", value, "lasttlevel");
            return this;
        }

        public Criteria andLasttlevelGreaterThan(Integer value) {
            addCriterion("atworkorder.lasttlevel >", value, "lasttlevel");
            return this;
        }

        public Criteria andLasttlevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.lasttlevel >=", value, "lasttlevel");
            return this;
        }

        public Criteria andLasttlevelLessThan(Integer value) {
            addCriterion("atworkorder.lasttlevel <", value, "lasttlevel");
            return this;
        }

        public Criteria andLasttlevelLessThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.lasttlevel <=", value, "lasttlevel");
            return this;
        }

        public Criteria andLasttlevelIn(List<Integer> values) {
            addCriterion("atworkorder.lasttlevel in", values, "lasttlevel");
            return this;
        }

        public Criteria andLasttlevelNotIn(List<Integer> values) {
            addCriterion("atworkorder.lasttlevel not in", values, "lasttlevel");
            return this;
        }

        public Criteria andLasttlevelBetween(Integer value1, Integer value2) {
            addCriterion("atworkorder.lasttlevel between", value1, value2,
                    "lasttlevel");
            return this;
        }

        public Criteria andLasttlevelNotBetween(Integer value1, Integer value2) {
            addCriterion("atworkorder.lasttlevel not between", value1, value2,
                    "lasttlevel");
            return this;
        }

        public Criteria andNexttlevelIsNull() {
            addCriterion("atworkorder.nexttlevel is null");
            return this;
        }

        public Criteria andNexttlevelIsNotNull() {
            addCriterion("atworkorder.nexttlevel is not null");
            return this;
        }

        public Criteria andNexttlevelEqualTo(Integer value) {
            addCriterion("atworkorder.nexttlevel =", value, "nexttlevel");
            return this;
        }

        public Criteria andNexttlevelNotEqualTo(Integer value) {
            addCriterion("atworkorder.nexttlevel <>", value, "nexttlevel");
            return this;
        }

        public Criteria andNexttlevelGreaterThan(Integer value) {
            addCriterion("atworkorder.nexttlevel >", value, "nexttlevel");
            return this;
        }

        public Criteria andNexttlevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.nexttlevel >=", value, "nexttlevel");
            return this;
        }

        public Criteria andNexttlevelLessThan(Integer value) {
            addCriterion("atworkorder.nexttlevel <", value, "nexttlevel");
            return this;
        }

        public Criteria andNexttlevelLessThanOrEqualTo(Integer value) {
            addCriterion("atworkorder.nexttlevel <=", value, "nexttlevel");
            return this;
        }

        public Criteria andNexttlevelIn(List<Integer> values) {
            addCriterion("atworkorder.nexttlevel in", values, "nexttlevel");
            return this;
        }

        public Criteria andNexttlevelNotIn(List<Integer> values) {
            addCriterion("atworkorder.nexttlevel not in", values, "nexttlevel");
            return this;
        }

        public Criteria andNexttlevelBetween(Integer value1, Integer value2) {
            addCriterion("atworkorder.nexttlevel between", value1, value2,
                    "nexttlevel");
            return this;
        }

        public Criteria andNexttlevelNotBetween(Integer value1, Integer value2) {
            addCriterion("atworkorder.nexttlevel not between", value1, value2,
                    "nexttlevel");
            return this;
        }

        public Criteria andCreateddateIsNull() {
            addCriterion("atworkorder.createddate is null");
            return this;
        }

        public Criteria andCreateddateIsNotNull() {
            addCriterion("atworkorder.createddate is not null");
            return this;
        }

        public Criteria andCreateddateEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.createddate =", value,
                    "createddate");
            return this;
        }

        public Criteria andCreateddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.createddate <>", value,
                    "createddate");
            return this;
        }

        public Criteria andCreateddateGreaterThan(Date value) {
            addCriterionForJDBCDate("atworkorder.createddate >", value,
                    "createddate");
            return this;
        }

        public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.createddate >=", value,
                    "createddate");
            return this;
        }

        public Criteria andCreateddateLessThan(Date value) {
            addCriterionForJDBCDate("atworkorder.createddate <", value,
                    "createddate");
            return this;
        }

        public Criteria andCreateddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("atworkorder.createddate <=", value,
                    "createddate");
            return this;
        }

        public Criteria andCreateddateIn(List<Date> values) {
            addCriterionForJDBCDate("atworkorder.createddate in", values,
                    "createddate");
            return this;
        }

        public Criteria andCreateddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("atworkorder.createddate not in", values,
                    "createddate");
            return this;
        }

        public Criteria andCreateddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("atworkorder.createddate between", value1,
                    value2, "createddate");
            return this;
        }

        public Criteria andCreateddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("atworkorder.createddate not between",
                    value1, value2, "createddate");
            return this;
        }

        public Criteria andCreatedbyemployeeidIsNull() {
            addCriterion("atworkorder.createdbyemployeeid is null");
            return this;
        }

        public Criteria andCreatedbyemployeeidIsNotNull() {
            addCriterion("atworkorder.createdbyemployeeid is not null");
            return this;
        }

        public Criteria andCreatedbyemployeeidEqualTo(String value) {
            addCriterion("atworkorder.createdbyemployeeid =", value,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidNotEqualTo(String value) {
            addCriterion("atworkorder.createdbyemployeeid <>", value,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidGreaterThan(String value) {
            addCriterion("atworkorder.createdbyemployeeid >", value,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidGreaterThanOrEqualTo(String value) {
            addCriterion("atworkorder.createdbyemployeeid >=", value,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidLessThan(String value) {
            addCriterion("atworkorder.createdbyemployeeid <", value,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidLessThanOrEqualTo(String value) {
            addCriterion("atworkorder.createdbyemployeeid <=", value,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidLike(String value) {
            addCriterion("atworkorder.createdbyemployeeid like", value,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidNotLike(String value) {
            addCriterion("atworkorder.createdbyemployeeid not like", value,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidIn(List<String> values) {
            addCriterion("atworkorder.createdbyemployeeid in", values,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidNotIn(List<String> values) {
            addCriterion("atworkorder.createdbyemployeeid not in", values,
                    "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidBetween(String value1,
                String value2) {
            addCriterion("atworkorder.createdbyemployeeid between", value1,
                    value2, "createdbyemployeeid");
            return this;
        }

        public Criteria andCreatedbyemployeeidNotBetween(String value1,
                String value2) {
            addCriterion("atworkorder.createdbyemployeeid not between", value1,
                    value2, "createdbyemployeeid");
            return this;
        }

        public Criteria andWostatusIsNull() {
            addCriterion("atworkorder.wostatus is null");
            return this;
        }

        public Criteria andWostatusIsNotNull() {
            addCriterion("atworkorder.wostatus is not null");
            return this;
        }

        public Criteria andWostatusEqualTo(String value) {
            addCriterion("atworkorder.wostatus =", value, "wostatus");
            return this;
        }

        public Criteria andWostatusNotEqualTo(String value) {
            addCriterion("atworkorder.wostatus <>", value, "wostatus");
            return this;
        }

        public Criteria andWostatusGreaterThan(String value) {
            addCriterion("atworkorder.wostatus >", value, "wostatus");
            return this;
        }

        public Criteria andWostatusGreaterThanOrEqualTo(String value) {
            addCriterion("atworkorder.wostatus >=", value, "wostatus");
            return this;
        }

        public Criteria andWostatusLessThan(String value) {
            addCriterion("atworkorder.wostatus <", value, "wostatus");
            return this;
        }

        public Criteria andWostatusLessThanOrEqualTo(String value) {
            addCriterion("atworkorder.wostatus <=", value, "wostatus");
            return this;
        }

        public Criteria andWostatusLike(String value) {
            addCriterion("atworkorder.wostatus like", value, "wostatus");
            return this;
        }

        public Criteria andWostatusNotLike(String value) {
            addCriterion("atworkorder.wostatus not like", value, "wostatus");
            return this;
        }

        public Criteria andWostatusIn(List<String> values) {
            addCriterion("atworkorder.wostatus in", values, "wostatus");
            return this;
        }

        public Criteria andWostatusNotIn(List<String> values) {
            addCriterion("atworkorder.wostatus not in", values, "wostatus");
            return this;
        }

        public Criteria andWostatusBetween(String value1, String value2) {
            addCriterion("atworkorder.wostatus between", value1, value2,
                    "wostatus");
            return this;
        }

        public Criteria andWostatusNotBetween(String value1, String value2) {
            addCriterion("atworkorder.wostatus not between", value1, value2,
                    "wostatus");
            return this;
        }

        public Criteria andApprovalreasonIsNull() {
            addCriterion("atworkorder.approvalreason is null");
            return this;
        }

        public Criteria andApprovalreasonIsNotNull() {
            addCriterion("atworkorder.approvalreason is not null");
            return this;
        }

        public Criteria andApprovalreasonEqualTo(String value) {
            addCriterion("atworkorder.approvalreason =", value,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonNotEqualTo(String value) {
            addCriterion("atworkorder.approvalreason <>", value,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonGreaterThan(String value) {
            addCriterion("atworkorder.approvalreason >", value,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonGreaterThanOrEqualTo(String value) {
            addCriterion("atworkorder.approvalreason >=", value,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonLessThan(String value) {
            addCriterion("atworkorder.approvalreason <", value,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonLessThanOrEqualTo(String value) {
            addCriterion("atworkorder.approvalreason <=", value,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonLike(String value) {
            addCriterion("atworkorder.approvalreason like", value,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonNotLike(String value) {
            addCriterion("atworkorder.approvalreason not like", value,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonIn(List<String> values) {
            addCriterion("atworkorder.approvalreason in", values,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonNotIn(List<String> values) {
            addCriterion("atworkorder.approvalreason not in", values,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonBetween(String value1, String value2) {
            addCriterion("atworkorder.approvalreason between", value1, value2,
                    "approvalreason");
            return this;
        }

        public Criteria andApprovalreasonNotBetween(String value1, String value2) {
            addCriterion("atworkorder.approvalreason not between", value1,
                    value2, "approvalreason");
            return this;
        }

        public Criteria andCancelreasonIsNull() {
            addCriterion("atworkorder.cancelreason is null");
            return this;
        }

        public Criteria andCancelreasonIsNotNull() {
            addCriterion("atworkorder.cancelreason is not null");
            return this;
        }

        public Criteria andCancelreasonEqualTo(String value) {
            addCriterion("atworkorder.cancelreason =", value, "cancelreason");
            return this;
        }

        public Criteria andCancelreasonNotEqualTo(String value) {
            addCriterion("atworkorder.cancelreason <>", value, "cancelreason");
            return this;
        }

        public Criteria andCancelreasonGreaterThan(String value) {
            addCriterion("atworkorder.cancelreason >", value, "cancelreason");
            return this;
        }

        public Criteria andCancelreasonGreaterThanOrEqualTo(String value) {
            addCriterion("atworkorder.cancelreason >=", value, "cancelreason");
            return this;
        }

        public Criteria andCancelreasonLessThan(String value) {
            addCriterion("atworkorder.cancelreason <", value, "cancelreason");
            return this;
        }

        public Criteria andCancelreasonLessThanOrEqualTo(String value) {
            addCriterion("atworkorder.cancelreason <=", value, "cancelreason");
            return this;
        }

        public Criteria andCancelreasonLike(String value) {
            addCriterion("atworkorder.cancelreason like", value, "cancelreason");
            return this;
        }

        public Criteria andCancelreasonNotLike(String value) {
            addCriterion("atworkorder.cancelreason not like", value,
                    "cancelreason");
            return this;
        }

        public Criteria andCancelreasonIn(List<String> values) {
            addCriterion("atworkorder.cancelreason in", values, "cancelreason");
            return this;
        }

        public Criteria andCancelreasonNotIn(List<String> values) {
            addCriterion("atworkorder.cancelreason not in", values,
                    "cancelreason");
            return this;
        }

        public Criteria andCancelreasonBetween(String value1, String value2) {
            addCriterion("atworkorder.cancelreason between", value1, value2,
                    "cancelreason");
            return this;
        }

        public Criteria andCancelreasonNotBetween(String value1, String value2) {
            addCriterion("atworkorder.cancelreason not between", value1,
                    value2, "cancelreason");
            return this;
        }

        public Criteria andEditreasonIsNull() {
            addCriterion("atworkorder.editreason is null");
            return this;
        }

        public Criteria andEditreasonIsNotNull() {
            addCriterion("atworkorder.editreason is not null");
            return this;
        }

        public Criteria andEditreasonEqualTo(String value) {
            addCriterion("atworkorder.editreason =", value, "editreason");
            return this;
        }

        public Criteria andEditreasonNotEqualTo(String value) {
            addCriterion("atworkorder.editreason <>", value, "editreason");
            return this;
        }

        public Criteria andEditreasonGreaterThan(String value) {
            addCriterion("atworkorder.editreason >", value, "editreason");
            return this;
        }

        public Criteria andEditreasonGreaterThanOrEqualTo(String value) {
            addCriterion("atworkorder.editreason >=", value, "editreason");
            return this;
        }

        public Criteria andEditreasonLessThan(String value) {
            addCriterion("atworkorder.editreason <", value, "editreason");
            return this;
        }

        public Criteria andEditreasonLessThanOrEqualTo(String value) {
            addCriterion("atworkorder.editreason <=", value, "editreason");
            return this;
        }

        public Criteria andEditreasonLike(String value) {
            addCriterion("atworkorder.editreason like", value, "editreason");
            return this;
        }

        public Criteria andEditreasonNotLike(String value) {
            addCriterion("atworkorder.editreason not like", value, "editreason");
            return this;
        }

        public Criteria andEditreasonIn(List<String> values) {
            addCriterion("atworkorder.editreason in", values, "editreason");
            return this;
        }

        public Criteria andEditreasonNotIn(List<String> values) {
            addCriterion("atworkorder.editreason not in", values, "editreason");
            return this;
        }

        public Criteria andEditreasonBetween(String value1, String value2) {
            addCriterion("atworkorder.editreason between", value1, value2,
                    "editreason");
            return this;
        }

        public Criteria andEditreasonNotBetween(String value1, String value2) {
            addCriterion("atworkorder.editreason not between", value1, value2,
                    "editreason");
            return this;
        }

        public Criteria andIsgrantedIsNull() {
            addCriterion("atworkorder.isgranted is null");
            return this;
        }

        public Criteria andIsgrantedIsNotNull() {
            addCriterion("atworkorder.isgranted is not null");
            return this;
        }

        public Criteria andIsgrantedEqualTo(Boolean value) {
            addCriterion("atworkorder.isgranted =", value, "isgranted");
            return this;
        }

        public Criteria andIsgrantedNotEqualTo(Boolean value) {
            addCriterion("atworkorder.isgranted <>", value, "isgranted");
            return this;
        }

        public Criteria andIsgrantedGreaterThan(Boolean value) {
            addCriterion("atworkorder.isgranted >", value, "isgranted");
            return this;
        }

        public Criteria andIsgrantedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("atworkorder.isgranted >=", value, "isgranted");
            return this;
        }

        public Criteria andIsgrantedLessThan(Boolean value) {
            addCriterion("atworkorder.isgranted <", value, "isgranted");
            return this;
        }

        public Criteria andIsgrantedLessThanOrEqualTo(Boolean value) {
            addCriterion("atworkorder.isgranted <=", value, "isgranted");
            return this;
        }

        public Criteria andIsgrantedIn(List<Boolean> values) {
            addCriterion("atworkorder.isgranted in", values, "isgranted");
            return this;
        }

        public Criteria andIsgrantedNotIn(List<Boolean> values) {
            addCriterion("atworkorder.isgranted not in", values, "isgranted");
            return this;
        }

        public Criteria andIsgrantedBetween(Boolean value1, Boolean value2) {
            addCriterion("atworkorder.isgranted between", value1, value2,
                    "isgranted");
            return this;
        }

        public Criteria andIsgrantedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("atworkorder.isgranted not between", value1, value2,
                    "isgranted");
            return this;
        }

        public Criteria andRevisionreasonIsNull() {
            addCriterion("atworkorder.revisionreason is null");
            return this;
        }

        public Criteria andRevisionreasonIsNotNull() {
            addCriterion("atworkorder.revisionreason is not null");
            return this;
        }

        public Criteria andRevisionreasonEqualTo(String value) {
            addCriterion("atworkorder.revisionreason =", value,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonNotEqualTo(String value) {
            addCriterion("atworkorder.revisionreason <>", value,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonGreaterThan(String value) {
            addCriterion("atworkorder.revisionreason >", value,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonGreaterThanOrEqualTo(String value) {
            addCriterion("atworkorder.revisionreason >=", value,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonLessThan(String value) {
            addCriterion("atworkorder.revisionreason <", value,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonLessThanOrEqualTo(String value) {
            addCriterion("atworkorder.revisionreason <=", value,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonLike(String value) {
            addCriterion("atworkorder.revisionreason like", value,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonNotLike(String value) {
            addCriterion("atworkorder.revisionreason not like", value,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonIn(List<String> values) {
            addCriterion("atworkorder.revisionreason in", values,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonNotIn(List<String> values) {
            addCriterion("atworkorder.revisionreason not in", values,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonBetween(String value1, String value2) {
            addCriterion("atworkorder.revisionreason between", value1, value2,
                    "revisionreason");
            return this;
        }

        public Criteria andRevisionreasonNotBetween(String value1, String value2) {
            addCriterion("atworkorder.revisionreason not between", value1,
                    value2, "revisionreason");
            return this;
        }

        public Criteria andRevisionreasoneksternalIsNull() {
            addCriterion("atworkorder.revisionreasoneksternal is null");
            return this;
        }

        public Criteria andRevisionreasoneksternalIsNotNull() {
            addCriterion("atworkorder.revisionreasoneksternal is not null");
            return this;
        }

        public Criteria andRevisionreasoneksternalEqualTo(String value) {
            addCriterion("atworkorder.revisionreasoneksternal =", value,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalNotEqualTo(String value) {
            addCriterion("atworkorder.revisionreasoneksternal <>", value,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalGreaterThan(String value) {
            addCriterion("atworkorder.revisionreasoneksternal >", value,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalGreaterThanOrEqualTo(
                String value) {
            addCriterion("atworkorder.revisionreasoneksternal >=", value,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalLessThan(String value) {
            addCriterion("atworkorder.revisionreasoneksternal <", value,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalLessThanOrEqualTo(String value) {
            addCriterion("atworkorder.revisionreasoneksternal <=", value,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalLike(String value) {
            addCriterion("atworkorder.revisionreasoneksternal like", value,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalNotLike(String value) {
            addCriterion("atworkorder.revisionreasoneksternal not like", value,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalIn(List<String> values) {
            addCriterion("atworkorder.revisionreasoneksternal in", values,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalNotIn(List<String> values) {
            addCriterion("atworkorder.revisionreasoneksternal not in", values,
                    "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalBetween(String value1,
                String value2) {
            addCriterion("atworkorder.revisionreasoneksternal between", value1,
                    value2, "revisionreasoneksternal");
            return this;
        }

        public Criteria andRevisionreasoneksternalNotBetween(String value1,
                String value2) {
            addCriterion("atworkorder.revisionreasoneksternal not between",
                    value1, value2, "revisionreasoneksternal");
            return this;
        }

        public Criteria andCancellationfeeIsNull() {
            addCriterion("atworkorder.cancellationfee is null");
            return this;
        }

        public Criteria andCancellationfeeIsNotNull() {
            addCriterion("atworkorder.cancellationfee is not null");
            return this;
        }

        public Criteria andCancellationfeeEqualTo(BigDecimal value) {
            addCriterion("atworkorder.cancellationfee =", value, "cancellationfee");
            return this;
        }

        public Criteria andCancellationfeeNotEqualTo(BigDecimal value) {
            addCriterion("atworkorder.cancellationfee <>", value, "cancellationfee");
            return this;
        }

        public Criteria andCancellationfeeGreaterThan(BigDecimal value) {
            addCriterion("atworkorder.cancellationfee >", value, "cancellationfee");
            return this;
        }

        public Criteria andCancellationfeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.cancellationfee >=", value, "cancellationfee");
            return this;
        }

        public Criteria andCancellationfeeLessThan(BigDecimal value) {
            addCriterion("atworkorder.cancellationfee <", value, "cancellationfee");
            return this;
        }

        public Criteria andCancellationfeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("atworkorder.cancellationfee <=", value, "cancellationfee");
            return this;
        }

        public Criteria andCancellationfeeIn(List<BigDecimal> values) {
            addCriterion("atworkorder.cancellationfee in", values, "cancellationfee");
            return this;
        }

        public Criteria andCancellationfeeNotIn(List<BigDecimal> values) {
            addCriterion("atworkorder.cancellationfee not in", values, "cancellationfee");
            return this;
        }

        public Criteria andCancellationfeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("atworkorder.cancellationfee between", value1, value2, "cancellationfee");
            return this;
        }

        public Criteria andCancellationfeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("atworkorder.cancellationfee not between", value1, value2,
                    "cancellationfee");
            return this;
        }

        public Criteria andCancellationtcurrencyfkIsNull() {
            addCriterion("atworkorder.cancellationtcurrencyfk is null");
            return this;
        }

        public Criteria andCancellationtcurrencyfkIsNotNull() {
            addCriterion("atworkorder.cancellationtcurrencyfk is not null");
            return this;
        }

        public Criteria andCancellationtcurrencyfkEqualTo(Long value) {
            addCriterion("atworkorder.cancellationtcurrencyfk =", value, "tcurrencyFk");
            return this;
        }

        public Criteria andCancellationtcurrencyfkNotEqualTo(Long value) {
            addCriterion("atworkorder.cancellationtcurrencyfk <>", value, "tcurrencyFk");
            return this;
        }

        public Criteria andCancellationtcurrencyfkGreaterThan(Long value) {
            addCriterion("atworkorder.cancellationtcurrencyfk >", value, "tcurrencyFk");
            return this;
        }

        public Criteria andCancellationtcurrencyfkGreaterThanOrEqualTo(Long value) {
            addCriterion("atworkorder.cancellationtcurrencyfk >=", value, "tcurrencyFk");
            return this;
        }

        public Criteria andCancellationtcurrencyfkLessThan(Long value) {
            addCriterion("atworkorder.cancellationtcurrencyfk <", value, "tcurrencyFk");
            return this;
        }

        public Criteria andCancellationtcurrencyfkLessThanOrEqualTo(Long value) {
            addCriterion("atworkorder.cancellationtcurrencyfk <=", value, "tcurrencyFk");
            return this;
        }

        public Criteria andCancellationtcurrencyfkIn(List<Long> values) {
            addCriterion("atworkorder.cancellationtcurrencyfk in", values, "tcurrencyFk");
            return this;
        }

        public Criteria andCancellationtcurrencyfkNotIn(List<Long> values) {
            addCriterion("atworkorder.cancellationtcurrencyfk not in", values,
                    "tcurrencyFk");
            return this;
        }

        public Criteria andCancellationtcurrencyfkBetween(Long value1, Long value2) {
            addCriterion("atworkorder.cancellationtcurrencyfk between", value1, value2,
                    "tcurrencyFk");
            return this;
        }

        public Criteria andCancellationtcurrencyfkNotBetween(Long value1, Long value2) {
            addCriterion("atworkorder.cancellationtcurrencyfk not between", value1,
                    value2, "tcurrencyFk");
            return this;
        }

        public Criteria setAndCustomSQL(String value) {
            andCustomSQL = value;
            return this;
        }

        public Criteria setOrCustomSQL(String value) {
            orCustomSQL = value;
            return this;
        }
    }
}