package com.ckb.wo.client.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WorkOrder implements Serializable {

    private String nextApprovalName;

    public String getNextApprovalName() {
        return nextApprovalName;
    }

    public void setNextApprovalName(String nextApprovalName) {
        this.nextApprovalName = nextApprovalName;
    }
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.tworkorder_pk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long tworkorderPk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.nomorwo
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String nomorwo;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.tvendorservice_fk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long tvendorserviceFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.adhoc
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Boolean adhoc;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.origintlocation_fk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long origintlocationFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.destinationtlocation_fk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long destinationtlocationFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.tservicemode_fk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long tservicemodeFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.torder_fk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long torderFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.tservicetype_fk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long tservicetypeFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.tvendor_fk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long tvendorFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.maxlevel
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Integer maxlevel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.totalweight
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private BigDecimal totalweight;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.totalvolume
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private BigDecimal totalvolume;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.tdeliveryterm_fk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long tdeliverytermFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.charge
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private BigDecimal charge;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.tcurrency_fk
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Long tcurrencyFk;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.agreementdate
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Date agreementdate;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.agreementno
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String agreementno;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.pph
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private BigDecimal pph;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.ppn
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private BigDecimal ppn;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.executiondate
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Date executiondate;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.editcounter
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Integer editcounter;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.revisioncounter
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Integer revisioncounter;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.lasttlevel
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Integer lasttlevel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.nexttlevel
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Integer nexttlevel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.createddate
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Date createddate;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.createdbyemployeeid
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String createdbyemployeeid;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.wostatus
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String wostatus;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.approvalreason
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String approvalreason;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.cancelreason
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String cancelreason;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.editreason
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String editreason;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.isgranted
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private Boolean isgranted;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.revisionreason
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String revisionreason;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.revisionreasoneksternal
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String revisionreasoneksternal;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.deliverynote
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String deliverynote;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.gooddescription
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String gooddescription;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database column tworkorder.validationnote
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private String validationnote;
    private BigDecimal cancellationfee;
    private Long cancellationtcurrencyfk;

    public Long getCancellationtcurrencyfk() {
        return cancellationtcurrencyfk;
    }

    public void setCancellationtcurrencyfk(Long cancellationtcurrencyfk) {
        this.cancellationtcurrencyfk = cancellationtcurrencyfk;
    }

    public BigDecimal getCancellationfee() {
        return cancellationfee;
    }

    public void setCancellationfee(BigDecimal cancellationfee) {
        this.cancellationfee = cancellationfee;
    }
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds
     * to the database table tworkorder
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.tworkorder_pk
     *
     * @return the value of tworkorder.tworkorder_pk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getTworkorderPk() {
        return tworkorderPk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.tworkorder_pk
     *
     * @param tworkorderPk the value for tworkorder.tworkorder_pk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTworkorderPk(Long tworkorderPk) {
        this.tworkorderPk = tworkorderPk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.nomorwo
     *
     * @return the value of tworkorder.nomorwo
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getNomorwo() {
        return nomorwo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.nomorwo
     *
     * @param nomorwo the value for tworkorder.nomorwo
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setNomorwo(String nomorwo) {
        this.nomorwo = nomorwo == null ? null : nomorwo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.tvendorservice_fk
     *
     * @return the value of tworkorder.tvendorservice_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getTvendorserviceFk() {
        return tvendorserviceFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.tvendorservice_fk
     *
     * @param tvendorserviceFk the value for tworkorder.tvendorservice_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTvendorserviceFk(Long tvendorserviceFk) {
        this.tvendorserviceFk = tvendorserviceFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.adhoc
     *
     * @return the value of tworkorder.adhoc
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Boolean getAdhoc() {
        return adhoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.adhoc
     *
     * @param adhoc the value for tworkorder.adhoc
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setAdhoc(Boolean adhoc) {
        this.adhoc = adhoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.origintlocation_fk
     *
     * @return the value of tworkorder.origintlocation_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getOrigintlocationFk() {
        return origintlocationFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.origintlocation_fk
     *
     * @param origintlocationFk the value for tworkorder.origintlocation_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setOrigintlocationFk(Long origintlocationFk) {
        this.origintlocationFk = origintlocationFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.destinationtlocation_fk
     *
     * @return the value of tworkorder.destinationtlocation_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getDestinationtlocationFk() {
        return destinationtlocationFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.destinationtlocation_fk
     *
     * @param destinationtlocationFk the value for
     * tworkorder.destinationtlocation_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setDestinationtlocationFk(Long destinationtlocationFk) {
        this.destinationtlocationFk = destinationtlocationFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.tservicemode_fk
     *
     * @return the value of tworkorder.tservicemode_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getTservicemodeFk() {
        return tservicemodeFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.tservicemode_fk
     *
     * @param tservicemodeFk the value for tworkorder.tservicemode_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTservicemodeFk(Long tservicemodeFk) {
        this.tservicemodeFk = tservicemodeFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.torder_fk
     *
     * @return the value of tworkorder.torder_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getTorderFk() {
        return torderFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.torder_fk
     *
     * @param torderFk the value for tworkorder.torder_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTorderFk(Long torderFk) {
        this.torderFk = torderFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.tservicetype_fk
     *
     * @return the value of tworkorder.tservicetype_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getTservicetypeFk() {
        return tservicetypeFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.tservicetype_fk
     *
     * @param tservicetypeFk the value for tworkorder.tservicetype_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTservicetypeFk(Long tservicetypeFk) {
        this.tservicetypeFk = tservicetypeFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.tvendor_fk
     *
     * @return the value of tworkorder.tvendor_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getTvendorFk() {
        return tvendorFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.tvendor_fk
     *
     * @param tvendorFk the value for tworkorder.tvendor_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTvendorFk(Long tvendorFk) {
        this.tvendorFk = tvendorFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.maxlevel
     *
     * @return the value of tworkorder.maxlevel
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Integer getMaxlevel() {
        return maxlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.maxlevel
     *
     * @param maxlevel the value for tworkorder.maxlevel
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setMaxlevel(Integer maxlevel) {
        this.maxlevel = maxlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.totalweight
     *
     * @return the value of tworkorder.totalweight
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public BigDecimal getTotalweight() {
        return totalweight;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.totalweight
     *
     * @param totalweight the value for tworkorder.totalweight
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTotalweight(BigDecimal totalweight) {
        this.totalweight = totalweight;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.totalvolume
     *
     * @return the value of tworkorder.totalvolume
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public BigDecimal getTotalvolume() {
        return totalvolume;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.totalvolume
     *
     * @param totalvolume the value for tworkorder.totalvolume
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTotalvolume(BigDecimal totalvolume) {
        this.totalvolume = totalvolume;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.tdeliveryterm_fk
     *
     * @return the value of tworkorder.tdeliveryterm_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getTdeliverytermFk() {
        return tdeliverytermFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.tdeliveryterm_fk
     *
     * @param tdeliverytermFk the value for tworkorder.tdeliveryterm_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTdeliverytermFk(Long tdeliverytermFk) {
        this.tdeliverytermFk = tdeliverytermFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.charge
     *
     * @return the value of tworkorder.charge
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public BigDecimal getCharge() {
        return charge;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.charge
     *
     * @param charge the value for tworkorder.charge
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setCharge(BigDecimal charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.tcurrency_fk
     *
     * @return the value of tworkorder.tcurrency_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Long getTcurrencyFk() {
        return tcurrencyFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.tcurrency_fk
     *
     * @param tcurrencyFk the value for tworkorder.tcurrency_fk
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setTcurrencyFk(Long tcurrencyFk) {
        this.tcurrencyFk = tcurrencyFk;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.agreementdate
     *
     * @return the value of tworkorder.agreementdate
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Date getAgreementdate() {
        return agreementdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.agreementdate
     *
     * @param agreementdate the value for tworkorder.agreementdate
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setAgreementdate(Date agreementdate) {
        this.agreementdate = agreementdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.agreementno
     *
     * @return the value of tworkorder.agreementno
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getAgreementno() {
        return agreementno;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.agreementno
     *
     * @param agreementno the value for tworkorder.agreementno
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setAgreementno(String agreementno) {
        this.agreementno = agreementno == null ? null : agreementno.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.pph
     *
     * @return the value of tworkorder.pph
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public BigDecimal getPph() {
        return pph;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.pph
     *
     * @param pph the value for tworkorder.pph
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setPph(BigDecimal pph) {
        this.pph = pph;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.ppn
     *
     * @return the value of tworkorder.ppn
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public BigDecimal getPpn() {
        return ppn;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.ppn
     *
     * @param ppn the value for tworkorder.ppn
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setPpn(BigDecimal ppn) {
        this.ppn = ppn;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.executiondate
     *
     * @return the value of tworkorder.executiondate
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Date getExecutiondate() {
        return executiondate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.executiondate
     *
     * @param executiondate the value for tworkorder.executiondate
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setExecutiondate(Date executiondate) {
        this.executiondate = executiondate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.editcounter
     *
     * @return the value of tworkorder.editcounter
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Integer getEditcounter() {
        return editcounter;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.editcounter
     *
     * @param editcounter the value for tworkorder.editcounter
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setEditcounter(Integer editcounter) {
        this.editcounter = editcounter;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.revisioncounter
     *
     * @return the value of tworkorder.revisioncounter
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Integer getRevisioncounter() {
        return revisioncounter;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.revisioncounter
     *
     * @param revisioncounter the value for tworkorder.revisioncounter
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setRevisioncounter(Integer revisioncounter) {
        this.revisioncounter = revisioncounter;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.lasttlevel
     *
     * @return the value of tworkorder.lasttlevel
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Integer getLasttlevel() {
        return lasttlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.lasttlevel
     *
     * @param lasttlevel the value for tworkorder.lasttlevel
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setLasttlevel(Integer lasttlevel) {
        this.lasttlevel = lasttlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.nexttlevel
     *
     * @return the value of tworkorder.nexttlevel
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Integer getNexttlevel() {
        return nexttlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.nexttlevel
     *
     * @param nexttlevel the value for tworkorder.nexttlevel
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setNexttlevel(Integer nexttlevel) {
        this.nexttlevel = nexttlevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.createddate
     *
     * @return the value of tworkorder.createddate
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.createddate
     *
     * @param createddate the value for tworkorder.createddate
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.createdbyemployeeid
     *
     * @return the value of tworkorder.createdbyemployeeid
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getCreatedbyemployeeid() {
        return createdbyemployeeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.createdbyemployeeid
     *
     * @param createdbyemployeeid the value for tworkorder.createdbyemployeeid
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setCreatedbyemployeeid(String createdbyemployeeid) {
        this.createdbyemployeeid = createdbyemployeeid == null ? null
                : createdbyemployeeid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.wostatus
     *
     * @return the value of tworkorder.wostatus
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getWostatus() {
        return wostatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.wostatus
     *
     * @param wostatus the value for tworkorder.wostatus
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setWostatus(String wostatus) {
        this.wostatus = wostatus == null ? null : wostatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.approvalreason
     *
     * @return the value of tworkorder.approvalreason
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getApprovalreason() {
        return approvalreason;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.approvalreason
     *
     * @param approvalreason the value for tworkorder.approvalreason
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setApprovalreason(String approvalreason) {
        this.approvalreason = approvalreason == null ? null : approvalreason.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.cancelreason
     *
     * @return the value of tworkorder.cancelreason
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getCancelreason() {
        return cancelreason;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.cancelreason
     *
     * @param cancelreason the value for tworkorder.cancelreason
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setCancelreason(String cancelreason) {
        this.cancelreason = cancelreason == null ? null : cancelreason.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.editreason
     *
     * @return the value of tworkorder.editreason
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getEditreason() {
        return editreason;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.editreason
     *
     * @param editreason the value for tworkorder.editreason
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setEditreason(String editreason) {
        this.editreason = editreason == null ? null : editreason.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.isgranted
     *
     * @return the value of tworkorder.isgranted
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public Boolean getIsgranted() {
        return isgranted;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.isgranted
     *
     * @param isgranted the value for tworkorder.isgranted
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setIsgranted(Boolean isgranted) {
        this.isgranted = isgranted;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.revisionreason
     *
     * @return the value of tworkorder.revisionreason
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getRevisionreason() {
        return revisionreason;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.revisionreason
     *
     * @param revisionreason the value for tworkorder.revisionreason
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setRevisionreason(String revisionreason) {
        this.revisionreason = revisionreason == null ? null : revisionreason.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.revisionreasoneksternal
     *
     * @return the value of tworkorder.revisionreasoneksternal
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getRevisionreasoneksternal() {
        return revisionreasoneksternal;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.revisionreasoneksternal
     *
     * @param revisionreasoneksternal the value for
     * tworkorder.revisionreasoneksternal
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setRevisionreasoneksternal(String revisionreasoneksternal) {
        this.revisionreasoneksternal = revisionreasoneksternal == null ? null
                : revisionreasoneksternal.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.deliverynote
     *
     * @return the value of tworkorder.deliverynote
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getDeliverynote() {
        return deliverynote;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.deliverynote
     *
     * @param deliverynote the value for tworkorder.deliverynote
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setDeliverynote(String deliverynote) {
        this.deliverynote = deliverynote == null ? null : deliverynote.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.gooddescription
     *
     * @return the value of tworkorder.gooddescription
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getGooddescription() {
        return gooddescription;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.gooddescription
     *
     * @param gooddescription the value for tworkorder.gooddescription
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setGooddescription(String gooddescription) {
        this.gooddescription = gooddescription == null ? null : gooddescription.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns
     * the value of the database column tworkorder.validationnote
     *
     * @return the value of tworkorder.validationnote
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public String getValidationnote() {
        return validationnote;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the
     * value of the database column tworkorder.validationnote
     *
     * @param validationnote the value for tworkorder.validationnote
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    public void setValidationnote(String validationnote) {
        this.validationnote = validationnote == null ? null : validationnote.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @param that
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof WorkOrder)) {
            return false;
        }
        WorkOrder other = (WorkOrder) that;
        return this.getTworkorderPk() == null ? other == null : this.getTworkorderPk().equals(other.getTworkorderPk())
                && this.getNomorwo() == null ? other == null : this.getNomorwo().equals(other.getNomorwo())
                && this.getTvendorserviceFk() == null ? other == null : this.getTvendorserviceFk().equals(other.getTvendorserviceFk())
                && this.getAdhoc() == null ? other == null : this.getAdhoc().equals(other.getAdhoc())
                && this.getOrigintlocationFk() == null ? other == null : this.getOrigintlocationFk().equals(other.getOrigintlocationFk())
                && this.getDestinationtlocationFk() == null ? other == null : this.getDestinationtlocationFk().equals(other.getDestinationtlocationFk())
                && this.getTservicemodeFk() == null ? other == null : this.getTservicemodeFk().equals(other.getTservicemodeFk())
                && this.getTorderFk() == null ? other == null : this.getTorderFk().equals(other.getTorderFk())
                && this.getTservicetypeFk() == null ? other == null : this.getTservicetypeFk().equals(other.getTservicetypeFk())
                && this.getTvendorFk() == null ? other == null : this.getTvendorFk().equals(other.getTvendorFk())
                && this.getMaxlevel() == null ? other == null : this.getMaxlevel().equals(other.getMaxlevel())
                && this.getTotalweight() == null ? other == null : this.getTotalweight().equals(other.getTotalweight())
                && this.getTotalvolume() == null ? other == null : this.getTotalvolume().equals(other.getTotalvolume())
                && this.getTdeliverytermFk() == null ? other == null : this.getTdeliverytermFk().equals(other.getTdeliverytermFk())
                && this.getCharge() == null ? other == null : this.getCharge().equals(other.getCharge())
                && this.getTcurrencyFk() == null ? other == null : this.getTcurrencyFk().equals(other.getTcurrencyFk())
                && this.getAgreementdate() == null ? other == null : this.getAgreementdate().equals(other.getAgreementdate())
                && this.getAgreementno() == null ? other == null : this.getAgreementno().equals(other.getAgreementno())
                && this.getPph() == null ? other == null : this.getPph().equals(other.getPph())
                && this.getPpn() == null ? other == null : this.getPpn().equals(other.getPpn())
                && this.getExecutiondate() == null ? other == null : this.getExecutiondate().equals(other.getExecutiondate())
                && this.getEditcounter() == null ? other == null : this.getEditcounter().equals(other.getEditcounter())
                && this.getRevisioncounter() == null ? other == null : this.getRevisioncounter().equals(other.getRevisioncounter())
                && this.getLasttlevel() == null ? other == null : this.getLasttlevel().equals(other.getLasttlevel())
                && this.getNexttlevel() == null ? other == null : this.getNexttlevel().equals(other.getNexttlevel())
                && this.getCreateddate() == null ? other == null : this.getCreateddate().equals(other.getCreateddate())
                && this.getCreatedbyemployeeid() == null ? other == null : this.getCreatedbyemployeeid().equals(other.getCreatedbyemployeeid())
                && this.getWostatus() == null ? other == null : this.getWostatus().equals(other.getWostatus())
                && this.getApprovalreason() == null ? other == null : this.getApprovalreason().equals(other.getApprovalreason())
                && this.getCancelreason() == null ? other == null : this.getCancelreason().equals(other.getCancelreason())
                && this.getEditreason() == null ? other == null : this.getEditreason().equals(other.getEditreason())
                && this.getIsgranted() == null ? other == null : this.getIsgranted().equals(other.getIsgranted())
                && this.getRevisionreason() == null ? other == null : this.getRevisionreason().equals(other.getRevisionreason())
                && this.getRevisionreasoneksternal() == null ? other == null : this.getRevisionreasoneksternal().equals(other.getRevisionreasoneksternal())
                && this.getDeliverynote() == null ? other == null : this.getDeliverynote().equals(other.getDeliverynote())
                && this.getGooddescription() == null ? other == null : this.getGooddescription().equals(other.getGooddescription())
                && this.getValidationnote() == null ? other == null : this.getValidationnote().equals(other.getValidationnote());
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method
     * corresponds to the database table tworkorder
     *
     * @ibatorgenerated Mon Aug 02 20:50:40 SGT 2010
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getTworkorderPk() != null) {
            hash *= getTworkorderPk().hashCode();
        }
        if (getNomorwo() != null) {
            hash *= getNomorwo().hashCode();
        }
        if (getTvendorserviceFk() != null) {
            hash *= getTvendorserviceFk().hashCode();
        }
        if (getAdhoc() != null) {
            hash *= getAdhoc().hashCode();
        }
        if (getOrigintlocationFk() != null) {
            hash *= getOrigintlocationFk().hashCode();
        }
        if (getDestinationtlocationFk() != null) {
            hash *= getDestinationtlocationFk().hashCode();
        }
        if (getTservicemodeFk() != null) {
            hash *= getTservicemodeFk().hashCode();
        }
        if (getTorderFk() != null) {
            hash *= getTorderFk().hashCode();
        }
        if (getTservicetypeFk() != null) {
            hash *= getTservicetypeFk().hashCode();
        }
        if (getTvendorFk() != null) {
            hash *= getTvendorFk().hashCode();
        }
        if (getMaxlevel() != null) {
            hash *= getMaxlevel().hashCode();
        }
        if (getTotalweight() != null) {
            hash *= getTotalweight().hashCode();
        }
        if (getTotalvolume() != null) {
            hash *= getTotalvolume().hashCode();
        }
        if (getTdeliverytermFk() != null) {
            hash *= getTdeliverytermFk().hashCode();
        }
        if (getCharge() != null) {
            hash *= getCharge().hashCode();
        }
        if (getTcurrencyFk() != null) {
            hash *= getTcurrencyFk().hashCode();
        }
        if (getAgreementdate() != null) {
            hash *= getAgreementdate().hashCode();
        }
        if (getAgreementno() != null) {
            hash *= getAgreementno().hashCode();
        }
        if (getPph() != null) {
            hash *= getPph().hashCode();
        }
        if (getPpn() != null) {
            hash *= getPpn().hashCode();
        }
        if (getExecutiondate() != null) {
            hash *= getExecutiondate().hashCode();
        }
        if (getEditcounter() != null) {
            hash *= getEditcounter().hashCode();
        }
        if (getRevisioncounter() != null) {
            hash *= getRevisioncounter().hashCode();
        }
        if (getLasttlevel() != null) {
            hash *= getLasttlevel().hashCode();
        }
        if (getNexttlevel() != null) {
            hash *= getNexttlevel().hashCode();
        }
        if (getCreateddate() != null) {
            hash *= getCreateddate().hashCode();
        }
        if (getCreatedbyemployeeid() != null) {
            hash *= getCreatedbyemployeeid().hashCode();
        }
        if (getWostatus() != null) {
            hash *= getWostatus().hashCode();
        }
        if (getApprovalreason() != null) {
            hash *= getApprovalreason().hashCode();
        }
        if (getCancelreason() != null) {
            hash *= getCancelreason().hashCode();
        }
        if (getEditreason() != null) {
            hash *= getEditreason().hashCode();
        }
        if (getIsgranted() != null) {
            hash *= getIsgranted().hashCode();
        }
        if (getRevisionreason() != null) {
            hash *= getRevisionreason().hashCode();
        }
        if (getRevisionreasoneksternal() != null) {
            hash *= getRevisionreasoneksternal().hashCode();
        }
        if (getDeliverynote() != null) {
            hash *= getDeliverynote().hashCode();
        }
        if (getGooddescription() != null) {
            hash *= getGooddescription().hashCode();
        }
        if (getValidationnote() != null) {
            hash *= getValidationnote().hashCode();
        }
        return hash;
    }
    public static final String INPROGRESS_STATUS = "IN_PROGRESS";
    public static final String VALIDATION_STATUS = "VALIDATION";
    public static final String APPROVED_STATUS = "APPROVED";
    public static final String PRINTED_STATUS = "PRINTED";
    public static final String CANCELLED_STATUS = "CANCELLED";
    public static final String EDIT_STATUS = "EDIT";
    public static final String RECEIVED_AP = "RECEIVED_AP";
    public static final String RECEIVED_STATUS = "RECEIVED";
    public static final String CANCEL_RECEIVED_AP = "CANCEL_RECEIVED_AP";
    public static final String CANCELLED_AP = "CANCELLED_AP";
    public static final String CANCEL_RECEIVED_STATUS = "CANCEL_RECEIVED";
    public static final String REVISION_STATUS = "REVISED";
    public static final String NEW_STATUS = "NEW";
    private List<WorkOrderDA> workOrderDA = new ArrayList<>();
    private List<WorkOrderManifest> workOrderManifest = new ArrayList<>();
    private List<WorkOrderServiceModeDetail> workOrderServiceModeDetail = new ArrayList<>();
    private Vendor vendor;
    private Currency currency;
    private Location origin;
    private Location destination;
    private DeliveryTerm deliveryTerm;
    private Level level;
    private Date approvedDate;
    private User creatorUser;
    private static final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private static final String EMPTY_STRING = "";
    private Order order;
    private ServiceType serviceType;

    public List<WorkOrderDA> getWorkOrderDA() {
        return workOrderDA;
    }

    public void setWorkOrderDA(List<WorkOrderDA> workOrderDA) {
        this.workOrderDA = workOrderDA;
    }

    public List<WorkOrderManifest> getWorkOrderManifest() {
        return workOrderManifest;
    }

    public void setWorkOrderManifest(List<WorkOrderManifest> workOrderManifest) {
        this.workOrderManifest = workOrderManifest;
    }

    public List<WorkOrderServiceModeDetail> getWorkOrderServiceModeDetail() {
        return workOrderServiceModeDetail;
    }

    public void setWorkOrderServiceModeDetail(
            List<WorkOrderServiceModeDetail> workOrderServiceModeDetail) {
        this.workOrderServiceModeDetail = workOrderServiceModeDetail;
    }

    public Vendor getVendor() {
        if (vendor == null) {
            return new Vendor();
        }
        return vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public Currency getCurrency() {
        if (currency == null) {
            return new Currency();
        }
        return currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    public Location getOrigin() {
        if (origin == null) {
            return new Location();
        }
        return origin;
    }

    public void setOrigin(Location origin) {
        this.origin = origin;
    }

    public Location getDestination() {
        if (destination == null) {
            return new Location();
        }
        return destination;
    }

    public void setDestination(Location destination) {
        this.destination = destination;
    }

    public DeliveryTerm getDeliveryTerm() {
        if (deliveryTerm == null) {
            return new DeliveryTerm();
        }
        return deliveryTerm;
    }

    public void setDeliveryTerm(DeliveryTerm deliveryTerm) {
        this.deliveryTerm = deliveryTerm;
    }

    public Level getLevel() {
        if (level == null) {
            return new Level();
        }
        return level;
    }

    public void setLevel(Level level) {
        this.level = level;
    }

    public Date getApprovedDate() {
        return approvedDate;
    }

    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    public User getCreatorUser() {
        return creatorUser;
    }

    public void setCreatorUser(User creatorUser) {
        this.creatorUser = creatorUser;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public ServiceType getServiceType() {
        return serviceType;
    }

    public void setServiceType(ServiceType serviceType) {
        this.serviceType = serviceType;
    }

    public String getChanges(WorkOrder workOrder) {
        if (workOrder == null) {
            return null;
        }
        StringBuilder sb = new StringBuilder();
        sb.append("changes on : ");

        //adhoc
        if (isChanged(this.getAdhoc(), workOrder.getAdhoc())) {
            sb.append("regular/handling,");
        }
        if (isChanged(this.getTvendorserviceFk(), workOrder.getTvendorserviceFk())) {
            sb.append("vendor rate,");
        }
        if (isChanged(this.getOrigintlocationFk(), workOrder.getOrigintlocationFk())) {
            sb.append("origin,");
        }
        if (isChanged(this.getDestinationtlocationFk(), workOrder.getDestinationtlocationFk())) {
            sb.append("destination,");
        }
        if (isChanged(this.getTservicemodeFk(), workOrder.getTservicemodeFk())) {
            sb.append("servicemode,");
        }
        if (isChanged(this.getTorderFk(), workOrder.getTorderFk())) {
            sb.append("order,");
        }
        if (isChanged(this.getTservicetypeFk(), workOrder.getTservicetypeFk())) {
            sb.append("servicetype,");
        }
        if (isChanged(this.tvendorFk, workOrder.getTvendorFk())) {
            sb.append("vendor,");
        }
        if (isChanged(this.maxlevel, workOrder.getMaxlevel())) {
            sb.append("approvaltype,");
        }
        if (isChanged(this.totalweight, workOrder.getTotalweight())) {
            sb.append("total weight,");
        }
        if (isChanged(this.totalvolume, workOrder.getTotalvolume())) {
            sb.append("total volume,");
        }
        if (isChanged(this.tdeliverytermFk, workOrder.getTdeliverytermFk())) {
            sb.append("delivery term,");
        }
        if (isChanged(this.charge, workOrder.getCharge())) {
            sb.append("rate,");
        }
        if (isChanged(this.tcurrencyFk, workOrder.getTcurrencyFk())) {
            sb.append("currency,");
        }
        if (isChanged(this.agreementdate, workOrder.getAgreementdate())) {
            sb.append("agreement date,");
        }
        if (isChanged(this.agreementno, workOrder.getAgreementno())) {
            sb.append("agreement no,");
        }
        if (isChanged(this.pph, workOrder.getPph())) {
            sb.append("pph,");
        }
        if (isChanged(this.ppn, workOrder.getPpn())) {
            sb.append("ppn,");
        }
        if (isChanged(this.executiondate, workOrder.getExecutiondate())) {
            sb.append("execution date,");
        }
        if (isChanged(this.deliverynote, workOrder.getDeliverynote())) {
            sb.append("delivery note,");
        }
        if (isChanged(this.gooddescription, workOrder.getGooddescription())) {
            sb.append("Good's description,");
        }
        if (isChanged(this.getWorkOrderDA(), workOrder.getWorkOrderDA())) {
            sb.append("DA,");
        }
        if (isChanged(this.getWorkOrderManifest(), workOrder.getWorkOrderManifest())) {
            sb.append("Manifest,");
        }
        if (isChanged(this.getWorkOrderServiceModeDetail(), workOrder.getWorkOrderServiceModeDetail())) {
            sb.append("ServiceModeDetail,");
        }
        return sb.toString();
    }

    public boolean isChanged(Object o1, Object o2) {
        if (isBothOfThemNull(o1, o2)) {
            return false;
        }
        if (isOneofThemNull(o1, o2)) {
            return true;
        }
        if (o1 instanceof List && o2 instanceof List) {
            List l1 = (List) o1;
            List l2 = (List) o2;
            if (l1.size() != l2.size()) {
                return true;
            } else {
                for (Object obj : l1) {
                    if (!l2.contains(obj)) {
                        return true;
                    }
                }
                return false;
            }
        }
        return o1.equals(o2);
    }

    private boolean isOneofThemNull(Object o1, Object o2) {
        if (o1 == null && o2 != null) {
            return true;
        }
        return o2 == null && o1 != null;
    }

    private boolean isBothOfThemNull(Object o1, Object o2) {
        return o1 == null && o2 == null;
    }

    public String getExecutionDateFormatted() {
        if (getExecutiondate() == null) {
            return EMPTY_STRING;
        }
        return sdf.format(getExecutiondate());
    }

    public void setExecutionDateFormatted(String date) throws ParseException {
        setExecutiondate(sdf.parse(date));
    }

    @Override
    public String toString() {
        return "WorkOrder{" + "nextApprovalName=" + nextApprovalName + ", tworkorderPk=" + tworkorderPk + ", nomorwo=" + nomorwo + ", tvendorserviceFk=" + tvendorserviceFk + ", adhoc=" + adhoc + ", origintlocationFk=" + origintlocationFk + ", destinationtlocationFk=" + destinationtlocationFk + ", tservicemodeFk=" + tservicemodeFk + ", torderFk=" + torderFk + ", tservicetypeFk=" + tservicetypeFk + ", tvendorFk=" + tvendorFk + ", maxlevel=" + maxlevel + ", totalweight=" + totalweight + ", totalvolume=" + totalvolume + ", tdeliverytermFk=" + tdeliverytermFk + ", charge=" + charge + ", tcurrencyFk=" + tcurrencyFk + ", agreementdate=" + agreementdate + ", agreementno=" + agreementno + ", pph=" + pph + ", ppn=" + ppn + ", executiondate=" + executiondate + ", editcounter=" + editcounter + ", revisioncounter=" + revisioncounter + ", lasttlevel=" + lasttlevel + ", nexttlevel=" + nexttlevel + ", createddate=" + createddate + ", createdbyemployeeid=" + createdbyemployeeid + ", wostatus=" + wostatus + ", approvalreason=" + approvalreason + ", cancelreason=" + cancelreason + ", editreason=" + editreason + ", isgranted=" + isgranted + ", revisionreason=" + revisionreason + ", revisionreasoneksternal=" + revisionreasoneksternal + ", deliverynote=" + deliverynote + ", gooddescription=" + gooddescription + ", validationnote=" + validationnote + ", cancellationfee=" + cancellationfee + ", cancellationtcurrencyfk=" + cancellationtcurrencyfk + ", workOrderDA=" + workOrderDA + ", workOrderManifest=" + workOrderManifest + ", workOrderServiceModeDetail=" + workOrderServiceModeDetail + ", vendor=" + vendor + ", currency=" + currency + ", origin=" + origin + ", destination=" + destination + ", deliveryTerm=" + deliveryTerm + ", level=" + level + ", approvedDate=" + approvedDate + ", creatorUser=" + creatorUser + ", order=" + order + ", serviceType=" + serviceType + '}';
    }
}
